### ISSUE TITLE
cy.go() does not accurately navigate to different domain names.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#106]
cy.go() does not navigate accurately to different domain names when going back or forward through the history.

**Example Code**

``` javascript
cy.visit('http://localhost:8080/foo/bar')
cy.visit('https://www.google.com')
cy.go('back') // this navigates to 'https://www.google.com/foo/bar'
```

**Comment by brian-mann** [comment]
This should be working in [`0.17.0`](https://github.com/cypress-io/cypress/wiki/changelog#0170-08302016) now, but I'm not sure we had any specific tests for this. Can you verify?

**Comment by jennifer-mann** [comment]
This is still failing although with different behavior.

**Example Code**
```javascript
cy.visit('https://example.cypress.io/commands/navigation')
cy.visit('https://docs.cypress.io')
cy.go('back') // this navigates to about:blank, but on snapshot hover the url says docs.cypress.io
```

**Example Command Log**
![screen shot 2016-08-31 at 12 05 56 pm](https://cloud.githubusercontent.com/assets/1271364/18136420/4e8797d6-6f73-11e6-8af9-dfae21ce9cc2.png)

**Comment by jennifer-shehane** [comment]
Works in 1.0.2. 

```js
describe('Test', function() {
  it('goes back', function() {
    cy.visit('https://example.cypress.io/commands/navigation')
    cy.visit('https://docs.cypress.io')
    cy.url().should('eq', 'https://docs.cypress.io/')
    cy.go('back')
    cy.url().should('eq', 'https://example.cypress.io/commands/navigation')
  })
})
```
