### ISSUE TITLE
Cypress errors on cy.type in an input type='tel'

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#141]
When writing the following code, an error displays saying cy.type can't be used on the specified input:

**Example Code**
```
cy.type('#tel').type('1234567')
```

**Error**
```
CypressError: .type() can only be called on textarea or :text!
```

**Command Log**
![screen shot 2016-05-12 at 12 00 56 pm](https://cloud.githubusercontent.com/assets/1271364/15221529/ca5e25fa-1839-11e6-99fa-2ef5cccac72b.png)

There's no special logic for the formatting of type='tel' inputs (like type date or time), it needs to be whitelisted to allow typing into similar to types text, search, url, etc.

**Comment by jennifer-mann** [comment]
Fixed in upcoming `0.16.0`.

**Comment by khiettran** [comment]
I still get the bug in version 0.19.4 

I have the input

>  <input type="int" maxlength="9" minlength="9" name="healthInsuranceIk" value="" data-test-component-name="renderInputElement" class="renderInputElement";">

get error when execute the command:
`cy.get('input[name=healthInsuranceIk]').type("1231231")`

**Comment by hypeofpipe** [comment]
If type is ' ', I get the same error. I think, absence of type - is type too.
