### ISSUE TITLE
Tests run in Chrome with baseUrl set navigate directly to baseUrl instead of Test Runner URL

### ISSUE THREAD

**Issue by StormPooper** [cypress-io/cypress#1777]
### Current behavior:
When I set a `baseUrl` and attempt to run the tests in Chrome, instead of the test runner it attempts to directly go to that URL. 
![image](https://user-images.githubusercontent.com/1657182/40555835-4de270b4-6042-11e8-8e99-7c4444a4cac8.png)
Removing the `baseUrl` property will load Cypress as normal, as does having a value set but running the tests using Electron.

### Desired behavior:
When I run the tests with Chrome, it should navigate to Cypress running on localhost and show me the Cypress Test Runner. This is how it behaves when using Electron as the browser.

### Steps to reproduce:

1. Add `"baseUrl": "https://doesntmatteranyurl"` to `Cypress.json`
2. Open Cypress
3. Set browser to Chrome
4. Run any tests

### Versions
**Cypress:** 2.1.0 (happened on previous versions too)
**OS:** Windows 10 1803

**Comment by jennifer-shehane** [comment]
This is the intended behavior of `baseUrl` as outlined [here](https://docs.cypress.io/guides/references/best-practices.html#Setting-a-global-baseUrl)

How are you seeing the main url in the Electron browser? - the main url bar does not display for me in Electron. 

Are you having an issue running the tests in Chrome versus Electron? Are the tests not running / displaying an error?

**Comment by jennifer-shehane** [comment]
I'm unable to recreate this in my environment using Cypress 2.1.0 on Mac. Tried Chrome 66, Chromium 65, Canary 68 and Electron 59. The only other obvious difference I see is Windows, which I would have to test.

Do you have any other configuration set up? Anything in your `cypress.json` or env vars?

**Comment by StormPooper** [comment]
It could be, my colleages also had it but they were all running Windows 7 or 10 too.

Here's the full `cypress.json`, no environment variables set.
```json
{
    "baseUrl": "https://e2e-webapp-dev-brighthr.azurewebsites.net",
    "viewportWidth": 1440,
    "viewportHeight": 900,
    "env": {
        "apiUrl": "https://e2e-brighthr-api-dev.azurewebsites.net",
        "region": "uk"
    },
    "reporter": "mochawesome",
    "reporterOptions": {
        "inline": true,
        "reportDir": "cypress/report",
        "reportFilename": "e2e.html",
        "configFile": "cypress.json"
    },
    "reporterEnabled": "mochawesome,@cypress/mocha-teamcity-reporter",
    "mochawesomeReporterOptions": {
        "inline": true,
        "json": false,
        "quiet": true,
        "reportDir": "test-results/e2e",
        "reportFilename": "index.html"
    }
}
```

**Comment by StormPooper** [comment]
@jennifer-shehane: Just asked a colleague on a Mac to run it and it's fine for them, so it appears to be a Windows issue. Here's what I see:
![image](https://user-images.githubusercontent.com/1657182/40648872-5e535c1e-6327-11e8-9e9f-023155ed00db.png)

And here's what my colleague sees (note the Test Runner UI in the background):
![image](https://user-images.githubusercontent.com/1657182/40648914-80e1533a-6327-11e8-8e09-be4907c2d664.png)

**Comment by StormPooper** [comment]
Still an issue on 3.0.1.

**Comment by astehlik** [comment]
I'm experiencing the same issue on **Fedora 28**:

With **Chrome 68**: the `baseUrl` is opened instead of the test runner and I get a 404 error.

When I use **Chromium 67** or **Electron 59** everything is working as expected.

**Comment by astehlik** [comment]
Another hint: the error occurs in Cypress version `2.1.0` (where it already worked before) and in version `3.0.3`.

This seems to indicate that something changed in a newer Chrome version which causes the problem.

**Comment by jennifer-shehane** [comment]
Oftentimes Windows has a different major Chrome release version than Linux/Mac machines, so while it is only happening on Windows - it may be a specific Chrome version issue - would need full versions of Chrome it is happening on.

I'm still unable to replicate on: 
- Chrome Version 70.0.3518.0
- Chrome Version 68.0.3440.106
- Chrome Version 67.0.3396.0

These just happen to be the chrome versions on my machine at the moment though.

**Comment by TPiddy** [comment]
I have the same issue...

Chrome 68, Cypress 3.1.0, Mac OS.

**Comment by StormPooper** [comment]
Still an issue with Cypress 3.1.4 and Chrome 71.0.3578.98 (Official Build) (64-bit) on Windows 10 1803.

**Comment by Ycaglayan** [comment]
I have this issue as well on Windows 7, Cypress 3.1.4 and 71.0.3578.98 (Official Build) (32-bit).

**Comment by jennifer-shehane** [comment]
Can any of you experiencing this issue, try to add the code below and respond whether it fixes the issue or not?

Add the code below to your `cypress/plugins/index.js` file:

```js
module.exports = (on) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') { 
      // ^ make sure this is your browser name, you may 
      // be using 'canary' or 'chromium' for example, so change it to match!
      args.push('--proxy-bypass-list=<-loopback>')
      return args
    }
  })
}
```

**Comment by renefs** [comment]
Hi @jennifer-shehane, I confirm that adding these lines fixes the issue :D

**Comment by StormPooper** [comment]
@jennifer-shehane yes, that seems to fix it for me.

**Comment by jennifer-shehane** [comment]
This PR will automatically pass these flags through to Chrome and should resolve this issue when released: https://github.com/cypress-io/cypress/pull/3049

**Comment by StormPooper** [comment]
@jennifer-shehane interestingly, this doesn't work for every machine I have. It worked on my home machine yesterday, but when I try it on my work machine I'm still getting this. I've tried with and without your code snippet and tried 3.1.5 too, but no luck. I've also upgraded to Chrome 72.0.3626.81 (Official Build) (64-bit), reinstalled it from scratch and completely wiped Chrome's settings, but no change.

**Comment by jennifer-shehane** [comment]
Hey @StormPooper, can you try setting `"modifyObstructiveCode": false` in your `cypress.json`? Does that fix the issue?

**Comment by StormPooper** [comment]
@jennifer-shehane just tried it, no difference.

**Comment by MarinoPoletine** [comment]
This issue happens to me also. The only way to get around is restarting my machine. I am using a MacBook

**Comment by Betree** [comment]
Had the same issue with the following `browser`:

```es6
{ 
  isChosen: true,
  majorVersion: '73',
  name: 'chromium',
  path: 'chromium-browser',
  version: '73.0.3683.75',
  isHeaded: true,
  isHeadless: false 
}
```

https://github.com/cypress-io/cypress/issues/1777#issuecomment-458842728 doesn't solve it for me.

It also happens when I select Electron 59 instead of Chromium in the cypress client.

The line that causes the issue is:
> cy.visit('http://localhost:1080');

**Config**

- My `baseUrl` is set to `http://localhost:3000`
- Tested on Cypress 3.1.5 and 3.2.0
- Ubuntu 18.04

**Preview**

![Peek 03-04-2019 16-18](https://user-images.githubusercontent.com/1556356/55486677-08a41980-562d-11e9-9bff-db0bac9ea129.gif)

**Comment by Betree** [comment]
For those who really need to move forward, here is my to cents hack to bypass this issue:

```es6
/**
 * Open a link not covered by `baseUrl`.
 * See https://github.com/cypress-io/cypress/issues/1777
 */
Cypress.Commands.add('openExternalLink', url => {
  cy.visit('/').then(window => {
    const linkIdentifier = `__TMP_CY_EXTERNAL_LINK__${btoa(url)}`;
    const link = window.document.createElement('a');
    link.innerHTML = linkIdentifier;
    link.setAttribute('href', url);
    link.setAttribute('id', linkIdentifier);
    window.document.body.appendChild(link);
    cy.get(`#${linkIdentifier}`).click();
  });
});
```

**Comment by jennifer-shehane** [comment]
I'm not able to replicate this issue by simply visiting 2 localhosts, with 1 of the localhosts being set as my `baseUrl`. 

In Chrome Version 73.0.3683.86

![](http://g.recordit.co/WX2Fddp2Ha.gif)

**test code**

```js
it('visits 3030 port', () => {
  cy.visit('http://localhost:3030')
})

it('visits 2222 port', () => {
  cy.visit('http://localhost:2222')
})
```

**cypress.json**

```json
{
  "baseUrl": "http://localhost:3030"
}
```

Can you verify that visiting the second localhost directly - with no baseUrl set - loads the page properly? I want to make sure there is not some misdirection - that the page loads usually within Cypress. 

Anyways, we will need a reproducible example in order to reopen the issue unfortunately.

**Comment by alastair-todd** [comment]
I have similar issue - I can visit my baseUrl, but not with a relative path

<img width="1152" alt="cypress" src="https://user-images.githubusercontent.com/595192/58246120-2862de80-7d4e-11e9-9d37-fe2f0afaa951.png">

```
      cy.visit("http://localhost:4200/index.html"); //OK
      cy.visit("index.html"); // fails
```

cypress.json:

```
{
  "baseUrl": "http://localhost:4200"
}
```

**Comment by alastair-todd** [comment]
so it appears I have missed a subtle difference between `cy.request` and `cy.visit`

beginner's error!

**Comment by CodeSwimBikeRunner** [comment]
I'm having the issue where my baseUrl is `http://localhost:4200/myapp`
But cypress with chrome is opening `http://localhost:4200/` which nothing exists there.

![image](https://user-images.githubusercontent.com/8485314/109863613-74cb9580-7c27-11eb-994c-f67cc742411e.png)
