### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by nancy-tache** [cypress-io/cypress#18464]
### Current behavior

    1) Select of Lenguage
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 8.6.0

### Desired behavior

run the tests correctly

### Test code to reproduce

n/a is private

### Cypress Version

8.6.0

### Other

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 8.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functional-test@1.0.0 scripts: `cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functional-test@1.0.0 scripts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by jmoses** [comment]
I'm also seeing this with Cypres 8.6.0

**Comment by MaaikeFox** [comment]
I got the same error after upgrading to 8.6.0
Downgrading to 8.5.0 fixed the crashes.

**Comment by mjhenkes** [comment]
@MaaikeFox, is there a specific spec that causes the failure? Is it possible to create a minimally reproducible test case?

**Comment by saadidrees711** [comment]
@jennifer-shehane Continues to be an issue on cypress 9.1.1
[https://github.com/AltaPay/plugin-magento2-community/actions/runs/1581368560](https://github.com/AltaPay/plugin-magento2-community/actions/runs/1581368560)

**Comment by MaaikeFox** [comment]
@mjhenkes I'see if I can see how it is reproducible.
It did not seem spec related, but I'll do a set of test runs on a never Cypress version to see what happens. For now I'm still stuck on version 8.5.0

I've seen online someone who experienced the same while using circleCI, so it is not just Azure Devops where this happens.
Quite some people are now stuck at an older Cypress version:
https://stackoverflow.com/questions/69658152/cypress-test-runner-unexpectedly-exited-via-a-exit-event-with-signal-sigsegv-in

**Comment by MaaikeFox** [comment]
I don't see this error happening anymore on 9.1.1 and 9.2.0
I did not see something on the change logs that looked like a fix for this, but maybe it did get fixed?

**Comment by ughunoup** [comment]
I experienced the same problem with version 9.1.1 in azure pipeline.

**Comment by MaaikeFox** [comment]
Still not seen this error again after using 9.2.0
Issue can therefore maybe be closed

**Comment by sakulstra** [comment]
Made a super weird observation on that.
Setting `video: true` seems to "solve" the issue for me (slowing down the ci quite a bit though) - very weird as this seems pretty much unrelated.

**Comment by MaaikeFox** [comment]
Hmm really @sakulstra . I've also set video to true in the mean time... So maybe that then solved it? For me it is good for now, so I will not test this through. But for the future it would be good if cypress heroes would still fix this regression on 8.6.0

btw Lucas, you can limit the slowing down by video recording by adding to your cypress.json
{
  "videoCompression": false,
  "videoUploadOnPasses": false,
}

**Comment by alrasch** [comment]
I'm having the same problem on 9.2.0.

```
node_modules/.bin/cypress open
[13867:0110/043736.889023:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13867:0110/043736.889078:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[14022:0110/043736.956598:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
[14022:0110/043736.956763:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
[13867:0110/043737.013936:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13867:0110/043737.042670:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

I've also tried the same with `--browser chromium`, and a few other browsers, but always the same result.

Version info:

```
/node_modules/.bin/cypress --version
Cypress package version: 9.2.0
Cypress binary version: 9.2.0
Electron version: 15.2.0
Bundled Node version: 16.5.0
```

```
npm -v && node -v
8.3.0
v17.3.0
```

The failure happens on an Arch machine, but succeeds with the same parameters on an Ubuntu box. I'm finding it hard to troubleshoot though. There's not much to go on, as far as I can see.

**Comment by a11smiles** [comment]
Interestingly enough this may be an issue with Electron, not Cypress, which could be why people are having intermittent issues regardless of what version of Cypress they're running.

I was getting the same errors for each spec file. I then added '--browser chrome' as a parameter. Now, I only get the error when Cypress first "opens" in my CI pipeline, but all of my spec files run without issue now.

**Comment by kutenai** [comment]
I just tried to upgrade from 8.5.0 to 9.3.1, and the problem, which I've had before, started again.
Reverted back to 8.5.0.

I suspect it's not a problem with Cypress per-se, but with something related that cypress uses. I'm not sure how to check all of the 'other stuff', but it seems outside of the cypress code base.. well, at least partially. 

What changed after 8.5.0 in what cypress accesses?? What tools/versions/options does cypress use that might have been modified then?

**Comment by Papooch** [comment]
The [Changelog for Cypress 8.6.0](https://docs.cypress.io/guides/references/changelog#8-6-0) states that they updated from electon 13 to 14. That might be a clue.

**Comment by choonkeat** [comment]
thanks @a11smiles! `--browser chrome` worked for me. `7.6.0` and `9.5.0` on GitHub Action
yes it was running electron

**Comment by LucaNerlich** [comment]
This seems fixed with 9.6.0

**Comment by Radmess** [comment]
Fixed by installing chrome on the Docker and running --browser chrome as well.

**Comment by xeger** [comment]
Still happening to me with 9.6.0, every single time I exit Cypress runner cleanly on my M1 Mac.

```
[10796:0506/204452.034373:ERROR:node_controller.cc(567)] Trying to re-add dropped peer D6582E1017EA117A.F702DEDCA4F22104
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 178.
The Test Runner unexpectedly exited via a exit event with signal SIGABRT
```

**Comment by magnolia93** [comment]
I ran into this issue when running cypress 9.5.3 on jenkins using cypress/base:14.17.3 docker image.
Deleteing `video: false` from cypress.json as @sakulstra said fixed the problem. So weird...

**Comment by Santas** [comment]
Still happens on:
Cypress: 10.3.0
Browser: Electron 100 (headless)
Node Version: v16.13.2
MacOS: 12.4
M1

Workaround with removing video: false helps.

**Comment by DaveMyth** [comment]
Hello everyone,
                       I am facing the same issue while running a test using cypress 12:
                       - Cypress package version: 12.3.0
                       - Cypress binary version: 12.3.0
                       - Electron version: 21.0.0
                       - Bundled Node version: 16.16.0
                       - Platform: linux-x64 (Debian - 11.6)
                       
  I wish to use the latest version (at least above 10). 
                          - I tried running the test with **cypress run --browser chrome**
                          - In the config file, video is set to true by default, 
                        but I am still getting a **The Test Runner unexpectedly exited via a exit event with signal SIGSEGV** with no logs, neither are the tests running. Can anyone please help me with this issue? Thanks in advance!

**Comment by wmiklasewicz** [comment]
I have the same issue for version 12.6.0/12.5.1, this is soo annoying...

**Comment by PhilippeMorier** [comment]
I ran Cypress with `DEBUG=cypress:*` in my `nx` repo, i.e.:

```bash
DEBUG=cypress:* npx nx e2e components-e2e
```

Which printed out that the system is `Missing X server or $DISPLAY`. Sounds like a quite clear message :sweat_smile:. Unfortunately, I don't understand yet why it is missing, since I am installing the [dependencies](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies), especially `xvfb` :thinking:.

```bash
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

```bash
cypress:snapshot:info Caching 3372, defining 4275 modules! Using cache +0ms
cypress:snapshot:debug initializing packherd require +0ms
cypress:server:appdata path: /root/.config/Cypress/cy/production/browsers +0ms
cypress:server:cypress starting cypress with argv [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--', '--run-project', 'apps/components-e2e', '--browser', 'chrome', '--config', '{"e2e":{}}', '--config-file', 'cypress.config.ts', '--env', '{}', '--output-path', '/tmp/tmp-6853-LshH3v8EE3cI', '--record', 'false', '--testing-type', 'e2e', '--cwd', '/pwd/of/project', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '16.15.1' ] +0ms
cypress:server:args argv array: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--run-project', 'apps/components-e2e', '--browser', 'chrome', '--config', '{"e2e":{}}', '--config-file', 'cypress.config.ts', '--env', '{}', '--output-path', '/tmp/tmp-6853-LshH3v8EE3cI', '--record', 'false', '--testing-type', 'e2e', '--cwd', '/pwd/of/project', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '16.15.1' ] +0ms
cypress:server:args parsed argv options { options: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, 'run-project': 'apps/components-e2e', runProject: 'apps/components-e2e', browser: 'chrome', config: '{"e2e":{}}', 'config-file': 'cypress.config.ts', configFile: 'cypress.config.ts', env: '{}', 'output-path': '/tmp/tmp-6853-LshH3v8EE3cI', outputPath: '/tmp/tmp-6853-LshH3v8EE3cI', record: 'false', 'testing-type': 'e2e', testingType: 'e2e', cwd: '/pwd/of/project', userNodePath: '/usr/bin/node', userNodeVersion: '16.15.1' } } +1ms
cypress:server:args argv parsed: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, runProject: 'apps/components-e2e', browser: 'chrome', config: { e2e: {} }, configFile: 'cypress.config.ts', env: {}, outputPath: '/tmp/tmp-6853-LshH3v8EE3cI', record: false, testingType: 'e2e', cwd: '/pwd/of/project', userNodePath: '/usr/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true } +4ms
cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' } +0ms
cypress:server:args options { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, runProject: 'apps/components-e2e', browser: 'chrome', config: { e2e: {}, env: {} }, configFile: 'cypress.config.ts', outputPath: '/tmp/tmp-6853-LshH3v8EE3cI', record: false, testingType: 'e2e', cwd: '/pwd/of/project', userNodePath: '/usr/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true } +2ms
cypress:server:args argv options: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, runProject: 'apps/components-e2e', browser: 'chrome', config: { e2e: {}, env: {} }, configFile: 'cypress.config.ts', outputPath: '/tmp/tmp-6853-LshH3v8EE3cI', record: false, testingType: 'e2e', cwd: '/pwd/of/project', userNodePath: '/usr/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, projectRoot: '/pwd/of/project/apps/components-e2e' } +0ms
cypress:server:cypress from argv [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--run-project', 'apps/components-e2e', '--browser', 'chrome', '--config', '{"e2e":{}}', '--config-file', 'cypress.config.ts', '--env', '{}', '--output-path', '/tmp/tmp-6853-LshH3v8EE3cI', '--record', 'false', '--testing-type', 'e2e', '--cwd', '/pwd/of/project', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '16.15.1' ] got options { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, runProject: 'apps/components-e2e', browser: 'chrome', config: { e2e: {}, env: {} }, configFile: 'cypress.config.ts', outputPath: '/tmp/tmp-6853-LshH3v8EE3cI', record: false, testingType: 'e2e', cwd: '/pwd/of/project', userNodePath: '/usr/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, projectRoot: '/pwd/of/project/apps/components-e2e' } +9ms
cypress:server:cypress scaling electron app in headless mode +0ms
❗👀 [7037:0222/164743.498968:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY ❗👀
[7037:0222/164743.498998:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
<s> [webpack.Progress] 61% building 13/14 entries 95/95 dependencies 1796/71 modules
2023-02-22T16:47:44.408Z cypress:cli child event fired { event: 'exit', code: null, signal: 'SIGSEGV' }
2023-02-22T16:47:44.409Z cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' }
2023-02-22T16:47:44.484Z cypress:cli arm uname -m result: { stdout: 'x86_64' } 
2023-02-22T16:47:44.485Z cypress:cli child event fired { event: 'close', code: null, signal: 'SIGSEGV' }
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:
https://on.cypress.io

Check if there is a GitHub issue describing this crash:
https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 12.5.1
```

Due to some "internal" reasons we need to install the NVIDIA drivers (Tesla T4), X11, TurboVNC (for 2D X server) and [VirtualGL](https://www.virtualgl.org/) (for 3D X server) in our `Dockerfile`:

```dockerfile
ENV VGL_DISPLAY=:0.0
ENV DISPLAY=:1 ❗👀
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

# Install system dependencies.
RUN --mount=type=ssh,id=deploy_key --mount=type=secret,id=apt-auth.key,dst=/etc/apt/auth.conf.d/secret.conf,required \
  apt update && \
  #
  ## Install the NVIDIA drivers (Tesla T4 recommended), X11, VNC and VGL.
  apt install -y xserver-xorg-dev nvidia-driver-515 linux-headers-$(uname -r) xterm xinit ubuntu-desktop tigervnc-common && \
  nvidia-xconfig -a --use-display-device=None --virtual=1280x1024 && \
  wget https://sourceforge.net/projects/virtualgl/files/2.6.5/virtualgl_2.6.5_amd64.deb/download -O virtualgl_2.6.5_amd64.deb && \
  sudo dpkg -i virtualgl*.deb && \
  rm virtualgl*.deb && \
  wget https://sourceforge.net/projects/turbovnc/files/2.2.6/turbovnc_2.2.6_amd64.deb/download -O turbovnc_2.2.6_amd64.deb && \
  sudo dpkg -i turbovnc*.deb && \
  rm turbovnc*.deb && \
  /opt/VirtualGL/bin/vglserver_config -config +s +f -t && \
  chmod +x /root/gpu_runner/fix_xorg_conf.py && \
```

My feeling is that this installation conflicts with Cypress preventing it from finding/using an x server.

Does maybe someone have an idea to overcome that :bouquet:?
Maybe starting `xvfb` manually, like written in the [docs](https://docs.cypress.io/guides/continuous-integration/introduction#Xvfb)?

### Update

Indeed it looks like we needed to start `TurboVNC` manually with
`/opt/TurboVNC/bin/vncserver ${DISPLAY}`

The pipeline is green :heavy_check_mark: :tada:!

These are the new logs:

```bash
2023-02-23T09:04:23.393Z cypress:cli verifying Cypress app
2023-02-23T09:04:23.394Z cypress:cli checking environment variables
2023-02-23T09:04:23.394Z cypress:cli checking if executable exists /root/.cache/Cypress/12.5.1/Cypress/Cypress
2023-02-23T09:04:23.395Z cypress:cli Binary is executable? : true
2023-02-23T09:04:23.395Z cypress:cli binaryDir is  /root/.cache/Cypress/12.5.1/Cypress
2023-02-23T09:04:23.395Z cypress:cli Reading binary package.json from: /root/.cache/Cypress/12.5.1/Cypress/resources/app/package.json
2023-02-23T09:04:23.396Z cypress:cli Found binary version 12.5.1 installed in: /root/.cache/Cypress/12.5.1/Cypress
2023-02-23T09:04:23.405Z cypress:cli { verified: true }
2023-02-23T09:04:23.405Z cypress:cli is Verified ? true
2023-02-23T09:04:23.406Z cypress:cli:run processing run options { project: 'apps/components-e2e', configFile: 'cypress.config.ts', browser: 'chrome', env: '{}', tag: undefined, exit: true, headed: false, record: false, key: null, parallel: false, ciBuildId: undefined, group: undefined, config: '{"e2e":{}}', testingType: 'e2e', outputPath: '/tmp/tmp-7863-hXsTH84qDsef', spec: null, reporter: null, reporterOptions: null }
2023-02-23T09:04:23.406Z cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY
2023-02-23T09:04:23.406Z cypress:cli:run run to spawn.start args ["--run-project","apps/components-e2e","--browser","chrome","--config","{\"e2e\":{}}","--config-file","cypress.config.ts","--env","{}","--output-path","/tmp/tmp-7863-hXsTH84qDsef","--record",false,"--testing-type","e2e"]
2023-02-23T09:04:23.407Z cypress:cli DISPLAY environment variable is set to :1 on Linux
Assuming this DISPLAY points at working X11 server,
Cypress will not spawn own Xvfb
NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  see https://github.com/cypress-io/cypress/issues/4034
Solution: Unset the DISPLAY variable and try again:
  DISPLAY= npx cypress run ...
2023-02-23T09:04:23.407Z cypress:cli needs to start own Xvfb? false
2023-02-23T09:04:23.407Z cypress:cli spawning, should retry on display problem? true
2023-02-23T09:04:23.410Z cypress:cli passing DISPLAY :1
2023-02-23T09:04:23.411Z cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', 'apps/components-e2e', '--browser', 'chrome', '--config', '{"e2e":{}}', '--config-file', 'cypress.config.ts', '--env', '{}', '--output-path', '/tmp/tmp-7863-hXsTH84qDsef', '--record', false, '--testing-type', 'e2e', '--cwd', '/pwd/of/project', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '16.15.1' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
2023-02-23T09:04:23.411Z cypress:cli spawning Cypress with executable: /root/.cache/Cypress/12.5.1/Cypress/Cypress
2023-02-23T09:04:23.503Z cypress:cli piping child STDERR to process STDERR
```

**Comment by ArkaPrabhaChowdhury** [comment]
Still facing this issue...

**Comment by nagash77** [comment]
I know this is an old issue.  There are conflicting reports of the problem being resolved for some and not for others. Does anyone on this thread have a reproduction on a current version of Cypress they can share that would allow Cypress engineers to investigate?

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
