### ISSUE TITLE
Cancelled network requests fail to resolve with cy.wait

### ISSUE THREAD

**Issue by jeremydorne** [cypress-io/cypress#19326]
### Current behavior

If a network request is aliased and the network request is cancelled by the browser, `cy.wait` will timeout waiting for the network request.

### Desired behavior

`cy.wait` should complete with a failed network request and should convey that the request was cancelled.

### Test code to reproduce

```
// Intercept an outbound request with `cy.intercept` and set it to an alias
cy.intercept("route-to-request", req => {
     req.id = "cancelled-request-id"
     req.reply()
}

// Redirect to a new page before the request resolves
cy.visit('http://localhost:3000/path-to-new-url')

// Wait for the cancelled request to resolve
cy.wait("@cancelled-request-id")
```

### Cypress Version

9.1.1

**Comment by jeremydorne** [comment]
Poking around in the debugger, once cancelled intercepted requests get a response, they are marked with the state `ResponseReceived` but will never reach the `Complete` state.

**Comment by JosiahAllen** [comment]
Hitting this issue as well, seems to block my ability to catch subsequent completed requests as well.

**Comment by laurence-myers** [comment]
This is a problem for Single Page Applications. For example, in a Vue app that makes GraphQL requests using Apollo, navigating to different page will cancel any requests in progress.

If the tests are written as full E2E tests, hitting a real API and database, and each test clears & seeds data in the database, you might start to see intermittent database deadlocks. This is because some GraphQL query is still in progress and accessing the database, while the DB is attempting to truncate all tables.

When dealing with a large number of existing (legacy) tests, the quick solution is to intercept every GraphQL request in a `beforeEach()` hook, and wait for each request in an `afterEach()` hook. Unfortunately, this doesn't work, due to this issue with cancelled requests. A cancelled request will be intercepted, but attempting to wait for it will always fail.

**Comment by flotwig** [comment]
@mjhenkes this is fixed by #24709, right?

**Comment by NavyMint** [comment]
@flotwig looks like yes but still reproducible, im using 9.7 version

**Comment by flotwig** [comment]
@NavyMint try updating to Cypress 12, which is where that fix landed. We don't typically backport fixes to older versions.

**Comment by Sam152** [comment]
I seem to be able to reproduce this with 12.5.1 with the following test case:

```js
context('Waiting on cancelled requests', () => {

  it('waiting will resolve when a request is cancelled', () => {
    cy.intercept(/jsonplaceholder.cypress.io/).as('intercepted-example')

    cy.visit('https://example.cypress.io/commands/network-requests')
    cy.get('.network-btn').click();
    cy.visit('https://example.cypress.io/commands/network-requests');

    cy.wait('@intercepted-example');
  });
});

```

<img width="667" alt="Screenshot 2023-02-17 at 12 12 51 pm" src="https://user-images.githubusercontent.com/820219/219547657-6bfa8626-6a3d-49f6-8a19-b556b2baef8f.png">

**Comment by NogDar** [comment]
Issue still occurs on 12.17.4

**Comment by piotrpalek** [comment]
any updates here? 🙏

**Comment by AshMcConnell** [comment]
I'm having this issue on the latest Cypress.  We have a field that we type in and it fire off a network request with every few chars.  It's pretty normal to have cancelled requests.  We get this when the cancelled request happens: -

![image](https://github.com/cypress-io/cypress/assets/497941/de8b9bdb-fc39-42c0-850d-523bc41878d2)

Is there any way to ignore it?

**Comment by krzysieknd** [comment]
I have the same problem, is there any solution to ignore the canceled request?

**Comment by esetnik** [comment]
I have the same issue. Has anyone found a workaround?

**Comment by vaclavGabriel** [comment]
> I have the same issue. Has anyone found a workaround?

My workaround is to mock the status code of such requests:

```js
// adjust status code for each request to prevent
// cypress from skipping requests cancelled by the browser
cy.intercept(/trpc/, (req) => {
	if (req.url.includes('search.searchAll')) {
		req.alias = 'Search'
		req.reply({ statusCode: 200 })
	}
})
```

**Comment by esetnik** [comment]
It is still happening in the latest version.

**Comment by JeffSweetland** [comment]
This happens pretty consistently for us, it waits for all completed requests, but any cancelled ones timeout

![Image](https://github.com/user-attachments/assets/4fd9388b-fa1f-464a-bb12-f38ce90f0d9d)

![Image](https://github.com/user-attachments/assets/9d8820b7-f84f-4bc8-a578-0d40f5e9011a)

![Image](https://github.com/user-attachments/assets/075e0860-56cc-44f4-85ea-0658e47a5421)
