### ISSUE TITLE
Cypress breaks Chrome dev tools debugging

### ISSUE THREAD

**Issue by autozoom** [cypress-io/cypress#19436]
### Current behavior

When running my app within Cypress, Chrome dev tools debugger shows inconsistent behaviour on the app code.
As you can see from the screenshot, some code lines are greyed out making it impossibile to stop on them, and you cannot even inspect variables (ret in this example).
It seems the breakpoint is not consistent with where the code has really stopped.

Everything works perfectly when Chrome runs outside of Cypress.
![immagine](https://user-images.githubusercontent.com/15321669/146885428-5d0acb3e-6247-4339-be9b-ba5c27753086.png)

### Desired behavior

The Chrome debugger should work the same way it does outside Cypress.

### Test code to reproduce

It happens on any project run under Cypress.

### Cypress Version

9.1.1

**Comment by simfeld** [comment]
In case your scripts are placed inside the body this could be related to #19377 which is fixed in `9.2.0`.

**Comment by autozoom** [comment]
> In case your scripts are placed inside the body this could be related to #19377 which is fixed in `9.2.0`.

I updated to 9.2.0 and the problem is still there. Thanks anyway

**Comment by sainthkh** [comment]
Can you provide a reproducible code example? 

As we all know, debugging starts with reproducing it on the developer's environment.

**Comment by autozoom** [comment]
here is the way to reproduce it:

clone https://github.com/autozoom/cypress.debugger.git

    npm ci
    npm run e2e
    run spec.ts
    open Chrome dev tools
    place a breakpoint on one of the console.log statements in app.component.ts
    run the test again
    the debugger doesn't stop on the breakpoint

I am on node 16.13.1 and npm 8.1.2, WIndows 10 and Chrome 96.0.4664.110

**Comment by sainthkh** [comment]
Sorry for the late reply. I fixed the similar problem with #19424. Is it still not working with 9.2.0+?

**Comment by sainthkh** [comment]
I tested it on Ubuntu 20.04, but it works perfectly like below:

![Peek 2022-01-17 11-50](https://user-images.githubusercontent.com/8130013/149700850-7004293a-d94a-428e-b79f-f024132bf54f.gif)

Maybe it's working because it's Ubuntu. But is it still not working?

**Comment by autozoom** [comment]
Still not working, even on Windows 11 and WSL/Ubuntu 20.04

Have you tried re-running the test by hitting the refresh button in the Cypress console?
In my case the breakpoint works sometimes, let's say 30% of the times.

Please try re running the test again and again and see if it stops every single time.

![immagine](https://user-images.githubusercontent.com/15321669/149737917-260497de-7915-4867-b01f-558cf109a24e.png)
