### ISSUE TITLE
Cypress is not adhering to the same behaviour as Chrome when forwarding cookies with SameSite=Lax

### ISSUE THREAD

**Issue by thu2004** [cypress-io/cypress#19800]
### Current behavior

When navigate from https://localhost:3000 to an external site (like a login redirect), if this new site makes a new redirect to itself (same domain but other sub url) with some cookies set in the response header, these cookies which have SameSite=Lax, they will not be set when redirect to the new url. 

### Desired behavior

 these cookies which have SameSite=Lax, they will be set when redirect to the new url. 

### Test code to reproduce

Please checkout the repo https://github.com/thu2004/cypress-cookie-lax-issue and follow the README.md

### Cypress Version

9.3.1

### Other
Here are network inspection of requests show the cookie XSRF-TOKEN set correctly when run in Chrome browser.

![chrome_oauth](https://user-images.githubusercontent.com/160065/150434848-45ff73e7-ac16-403d-8421-383c2b3e3d92.png)

![chrome-oauth-login](https://user-images.githubusercontent.com/160065/150434855-3410183e-c8ea-4a17-88d0-3165abe365bc.png)

_No response_

**Comment by thu2004** [comment]
Here is the dirty fix I tried by replacing the Lax to None inside the cypress. Hope you will have a proper fix soon.

![cypress_workaround](https://user-images.githubusercontent.com/160065/150435395-9944f7d5-f608-44f5-a7bc-1e57c079d43a.png)

**Comment by thu2004** [comment]
@tbiethman Do you need my help when investigate the issue ?

**Comment by flaggskeppet** [comment]
What is the current status regarding this problem? This fix should be applied asap.

**Comment by amandaaddq** [comment]
I have the same problem :(

**Comment by alexvbg** [comment]
facing same problem =(

**Comment by ttomaszewski** [comment]
+1

**Comment by AtofStryker** [comment]
Hey @thu2004. Thank you for opening an issue. I believe this is an issue with cypress not supporting cross origin navigations at the time of logging of this issue, but should be solved with `cy.origin` in `10.10.0` with the release of #23872. The cookie may not be set in the browser, but will be simulated by our middleware and should be set appropriately. would you be willing to try this once `10.10.0` is released with `cy.origin`?

**Comment by jonasraoni** [comment]
Hi @AtofStryker, I can confirm the issue still exists. I'm using Cypress 10.10.0, and the intermediate cookie (set within a 302 redirect is getting discarded). This is what I've got with the `Cypress.Cookies.debug(true);`:

![image](https://user-images.githubusercontent.com/361921/196024891-72a2c3ac-a727-4143-a8b3-1d35e1bf7427.png)

I've reached the same workaround (changed the `SameSite`).

**Comment by AtofStryker** [comment]
It seems to be fixed when contained properly within the `cy.origin` command as expected with cypress `10.11.0`:
```js
describe('test redirect', () => {
  it('it', () => {
    cy.visit('https://localhost:3000');
    cy.get('button').click();
    cy.origin('https://oauth-simulator.mocklab.io', () => {
      cy.get('body').contains('The XSRF-TOKEN is pressent')
    })
  });
});
```
<img width="1767" alt="Screen Shot 2022-11-18 at 2 46 59 PM" src="https://user-images.githubusercontent.com/3980464/202789895-005f1b54-47c2-4980-a024-ca5b81c50dd2.png">

https://user-images.githubusercontent.com/3980464/202790662-110729d5-5c38-4d00-92c6-e68cc554cdc0.mp4

@jonasraoni I am wondering if you are experiencing a different issue. Do you have another issue open with a reproduction we can take a look at? Cookie capturing should work with cy.origin correctly, (in browser or proxy) but there are still some bugs happening with `cy.request`. I am going to close this one as it is fixed .

**Comment by thu2004** [comment]
Now it is fixed. I updated the repo https://github.com/thu2004/cypress-cookie-lax-issue as well. Thank you

**Comment by jonasraoni** [comment]
@AtofStryker Yep, I've just investigated this one deeper and it's definitely another issue.

```http
Cypress: 12.2.0
Windows: 10
Node: 18.11.0
```

Considering a simple:
```js
cy.visit('/');
```

And the HTTP response below:

```http
HTTP/1.1 302 Found
Host: 127.0.0.1:8080
Date: Sun, 08 Jan 2023 16:07:27 GMT
Connection: close
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: SESSION_ID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
Set-Cookie: SESSION_ID=new_cookie_value
Location: next-url
Content-type: text/html; charset=UTF-8
```

> Notice the `Set-Cookie`, first removing a cookie, then recreating it (which I consider an error, that should work nevertheless), and the presence of the `Location` header

When Cypress goes to the redirected URL, the cookie is lost (it works in the browser though) 🤔

It works if I remove the `Location` header and redirect with another `cy.visit(`/next-url`);` or if I drop the first `Set-Cookie` header.
