### ISSUE TITLE
Cypress hangs up if running with CI Pipeline

### ISSUE THREAD

**Issue by pontilicious** [cypress-io/cypress#19821]
### Current behavior

Hello all, 

we have the problem that Cypress local runs without problems. All tests are executed and the test run includes all test specs. 
If we run the same code in a pipeline with a Docker image, it doesn't work anymore. 
The problem is that Cypress doesn't do anything anymore except logging the CPU usage even though there are still test specs and tests to run. 
Sometimes this happens during the first test spec, sometimes after another one. It is always different. 

Via` DEBUG=cypress:* npx cypress run` I logged everything and before Cypress hangs, the following error appears in the log:

```
2022-01-21T18:08:43.963Z cypress:https-proxy Making intercepted connection to 39793
2022-01-21T18:08:43.964Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.965Z cypress:server:request aborting { requestId: 'request30243' }
2022-01-21T18:08:43.967Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.969Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.970Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.970Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.970Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.971Z cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Socket.ondata (internal/streams/readable.js:719:22) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23) { errno: -32, code: 'EPIPE', syscall: 'write' }, url: 'ourStagingURL:443' }
2022-01-21T18:08:43.971Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33392 }
2022-01-21T18:08:43.971Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33386 }
2022-01-21T18:08:43.971Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33342 }
2022-01-21T18:08:43.971Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33388 }
2022-01-21T18:08:43.971Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33390 }
2022-01-21T18:08:43.973Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 39522 }
2022-01-21T18:08:43.973Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33384 }
2022-01-21T18:08:43.974Z cypress:network:connect successfully connected { opts: { port: 39793, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2022-01-21T18:08:43.974Z cypress:https-proxy received upstreamSocket callback for request { port: 39793, hostname: 'localhost', err: undefined }
2022-01-21T18:08:43.974Z cypress:server:util:socket_allowed allowing socket { localPort: 33526 }
2022-01-21T18:08:44.057Z cypress:server:video capture stderr log { message: 'frame=27573 fps= 25 q=12.0 size=  190464kB time=00:18:22.60 bitrate=1415.1kbits/s dup=15393 drop=0 speed=1.01x    ' }
2022-01-21T18:08:45.581Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33412 }
2022-01-21T18:08:45.838Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33452 }
2022-01-21T18:08:46.662Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33434 }
2022-01-21T18:08:46.823Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33428 }
2022-01-21T18:08:46.823Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33448 }
2022-01-21T18:08:46.826Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33450 }
```

This happens in Chrome and Electron Browser. We have this Issue testet with Cypress `8.3.0` and `9.2.1`. 
i've tried `"video": false`, `"numTestsKeptInMemory": 1 and 0`, and 

```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.family === 'chrome') {
      console.log('Adding --disable-dev-shm-usage...')
      args.push('--disable-dev-shm-usage')
    }

    return args
  })
}

module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium') {
      launchOptions.args.push('--disable-dev-shm-usage');
    }

    return launchOptions;
  });
}
```
but nothing helps. Do you have another idea for a workaround? 

### Desired behavior

Cypress runner complete the test run without hanging up.

### Test code to reproduce

Since it fails on a different spec each time, it doesn't seem to be related to actual test code

### Cypress Version

8.3.0 / 9.2.1

**Comment by mrSingh007** [comment]
I did very basic test with Docker on local machine then with bitbucket pipeline and could successfully run the tests.
Here is source code example https://bitbucket.org/harvinderMand/cypress-demo/src/master/

**Comment by pontilicious** [comment]
this is a very annoying bug and from the logfiles there is no real reason why it aborts or does not start a new testspec. Just do not understand this. I've tried many Cypress versions with different browsers (Chrome and Electron) but the error always occurs again. We have a test suite with 21 test specs and it NEVER runs through. It always aborts. 

Have also tried it with: 

```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {

    //console.log(launchOptions.args)

    if (browser.family === 'chromium') {
      launchOptions.args.push('--disable-background-networking')
      launchOptions.args.push('--enable-features=NetworkService,NetworkServiceInProcess')
      launchOptions.args.push('--disable-background-timer-throttling')
      launchOptions.args.push('--disable-backgrounding-occluded-windows')
      launchOptions.args.push('--disable-breakpad')
      launchOptions.args.push('--disable-client-side-phishing-detection')
      launchOptions.args.push('--disable-default-apps')
      launchOptions.args.push('--disable-dev-shm-usage')
      launchOptions.args.push('--disable-extensions')
      launchOptions.args.push('--disable-features=site-per-process,TranslateUI')
      launchOptions.args.push('--disable-hang-monitor')
      launchOptions.args.push('--disable-ipc-flooding-protection')
      launchOptions.args.push('--disable-popup-blocking')
      launchOptions.args.push('--disable-prompt-on-repost')
      launchOptions.args.push('--disable-renderer-backgrounding')
      launchOptions.args.push('--disable-sync')
      launchOptions.args.push('--force-color-profile=srgb')
      launchOptions.args.push('--metrics-recording-only')
      launchOptions.args.push('--no-first-run')
      launchOptions.args.push('--safebrowsing-disable-auto-update')
      launchOptions.args.push('--enable-automation')
      launchOptions.args.push('--password-store=basic')
      launchOptions.args.push('--use-mock-keychain')
      launchOptions.args.push('--webview-disable-safebrowsing-support')
      return launchOptions.args
    }
  })
}
```

tried. but it does not work via bitbucket pipeline. 
If I start the tests local with me, then there are no problems. 
Just do not understand this.

**Comment by pontilicious** [comment]
[newChrome.txt](https://github.com/cypress-io/cypress/files/8185831/newChrome.txt)
here is the log file from my last test with settings above. there is no special reason viewable why the test hangs up. 
at some point the program just hangs up and only plays that out: 
`cypress:server:util:process_profiler current & mean memory and CPU usage by process group:`

**Comment by pontilicious** [comment]
i downgraded the cypress version until `cypress/included:6.8.0` and the pipeline still hangs up at some point.

**Comment by pontilicious** [comment]
its possible, that this problem is the same as #7174

**Comment by pontilicious** [comment]
we fixed the issue by excluding --disable-dev-shm-usage completely from the args

`plugins/index.js`
```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    launchOptions.args = launchOptions.args.filter(item => item !== "--disable-dev-shm-usage")
    return launchOptions;
  });
}
```

**Comment by pontilicious** [comment]
i've said that this issue is fixed with the above comment. 
So i made a new Issue: https://github.com/cypress-io/cypress/issues/22506

**Comment by GastonMujica** [comment]
Hey! To anyone still having this issue, this might help you out! 
We've tried almost everything, from reducing the amount of tests in memory, to the` --ipc=host` to` disable-dev-shm-usage`. Nothing worked. At the end we where able to **fix this issue by cleaning both the cache and the cookies.** 

```
export const clearCache = () => {
  cy.wrap(
    Cypress.automation('remote:debugger:protocol', {
      command: 'Network.clearBrowserCache',
    }),
  );
};

export const clearCookies = () => {
  cy.clearCookies();
};
```

Hope it helps!

**Comment by kavyapriya154** [comment]
Where we need to put this piece of code

export const clearCache = () => {
  cy.wrap(
    Cypress.automation('remote:debugger:protocol', {
      command: 'Network.clearBrowserCache',
    }),
  );
};

export const clearCookies = () => {
  cy.clearCookies();
};

**Comment by GastonMujica** [comment]
> Where we need to put this piece of code
> 
> export const clearCache = () => { cy.wrap( Cypress.automation('remote:debugger:protocol', { command: 'Network.clearBrowserCache', }), ); };
> 
> export const clearCookies = () => { cy.clearCookies(); };

Hey, good morning! 
I usually create functions on another file and export them into the test. If not, you can do something like this

```
const clearCache = () => {
cy.wrap(
Cypress.automation('remote:debugger:protocol', {
command: 'Network.clearBrowserCache',
}),
);
};

const clearCookies = () => {
cy.clearCookies();
};

describe('Your scenario here', () => {
  beforeEach(() => {
    clearCache();
    clearCookies(); })
})
```

Even so, this actually fixed the issue for only one of our specs. To fix the other we had to stop intercepting a request that was getting intercepted like 20 times. When we skipped the interception, the test stopped failing in the CI.
So check that too

**Comment by jreyn001** [comment]
@GastonMujica Thanks! This worked for us.  We upgraded from Cypress 11 to Cypress 12 and the tests would hang on Azure CI Pipeline with logs similar to @robrich7.  Adding this before each test solved it for us.

**Comment by MoSattler** [comment]
Should this issue really be closed? It's still an issue, and clearing everything before every test looks like a wonky workaround.

**Comment by MarkiyanPyts** [comment]
Especially if cookies is needed to maintain auth0 session.
