### ISSUE TITLE
Cannot read properties of null (reading 'append') - @cypress/vue

### ISSUE THREAD

**Issue by mmaietta** [cypress-io/cypress#20787]
### Current behavior

I've been unable to run any cypress tests that leverage @cypress/vue package. It always fails with `Cannot read properties of null (reading 'append')`
Related code in `node_modules/@cypress/vue/dist/cypress-vue.esm-bundler.js`
```
        var document = cy.state('document');
        var el = document.getElementById(ROOT_ID);
        var componentNode = document.createElement('div');
        el.append(componentNode);
```
Via: `yarn cypress open`
![Screen Shot 2022-03-25 at 10 52 13 AM](https://user-images.githubusercontent.com/5238867/160200716-68ce36ce-42b2-4722-a92b-8020261191b8.png)

Via: `yarn cypress run`
```
  1) HelloWorld
       renders a message:
     TypeError: Cannot read properties of null (reading 'append')
      at Context.eval (http://localhost:58195/__cypress/tests?p=cypress/integration/hello-world.spec.js:382:8)
```

I've been banging my head against this error message for days. Am I missing something obvious? Any help is greatly appreciated.

Sample repo provided

### Desired behavior

Be able to successfully run the Hellow World cypress test

### Test code to reproduce

https://github.com/mmaietta/cypress-test-tiny

```
yarn install
yarn cypress open
```

### Cypress Version

9.5.2

**Comment by mmaietta** [comment]
Note: I can also repro this with `@cypress/react` :/
Not sure how to proceed with visual testing of my application, or any hello world one. 
![Screen Shot 2022-03-28 at 1 35 02 PM](https://user-images.githubusercontent.com/5238867/160482600-3f9dddae-937d-4455-87df-94ef69b783dd.png)

**Comment by ZachJW34** [comment]
@mmaietta have you setup the dev-server for serving your components? You can check out the docs [here](https://docs.cypress.io/guides/component-testing/framework-configuration#Vue-Vue-CLI).

There are also some examples [here](https://github.com/cypress-io/cypress-component-testing-examples)

CT testing requires a dev-server to be configured before it can serve your components.

**Comment by mmaietta** [comment]
Unfortunately, none of the docs/examples seem to specify the process specifically for projects with custom webpack configurations. My project was not created with CRA, vue cli, vite, etc. and just uses a vanilla, non-extended, webpack config.

I was able to get it working though! The dev server was already set up, but it never would connect.
I was finally able to resolve the issue in my work project though by zero-ing out my `devServer` config.
```
const webpackConfig: webpack.Configuration = {
  ...vanillaConfig,
  devServer: {}
}
startDevServer({ options, webpackConfig })
```
That allowed `open-ct` and `run-ct` to actually execute tests. That was incorrectly testing with `open` and `run`, because `-ct` commands weren't running at all, those just hung (presumably because the dev server wouldn't start/connect)

I'll try and update my test repo to exemplify the fix. Once I do, would you be willing to include it as an example?

**Comment by skjnldsv** [comment]
I have the same issue :/
@mmaietta, were you able to find a solution?

**Comment by skjnldsv** [comment]
Ah, found the issue, `ROOT_ID` expect a root element with the ID `__cy_root`
![image](https://user-images.githubusercontent.com/14975046/172906664-ada06340-b209-47c9-9bf2-2cd6d2caf87c.png)

Editing the `component-index.html` to this fixed it
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Components App</title>
  </head>
  <body>
    <div id="__cy_root"></div>
  </body>
</html>```

**Comment by arielrahmane** [comment]
For Vue 2 users: this is solved by using [@cypress/vue2](https://www.npmjs.com/package/@cypress/vue2)

**Comment by ZachJW34** [comment]
We have drastically overhauled CT testing with 10.0 and have new [docs](https://docs.cypress.io/guides/component-testing/writing-your-first-component-test) showing how to get up and running with frameworks and projects that are using a raw webpack config.

When migrating to 10.0, we have an onboarding experience that should handle most of the config and scaffolding. If you are able, I would recommend upgrading to 10.0. We have internalized a bunch of the dependencies that were previously required so depending on your project you shouldn't have to install any additional dependencies (and can in fact remove most of them).

We have a bunch of examples [here](https://github.com/cypress-io/cypress-component-testing-apps) if you would like to see CT in action. If we are missing a use-case, please let us know!

**Comment by Craig1f** [comment]
Confirmed this is fixed by modifying the auto-generated `component-index..html`, line 10 from:

`<div data-cy-root></div>`
to 
`<div data-cy-root id="__cy_root"></div>`

**Comment by lmiller1990** [comment]
Cy 10 fixed a lot of issues in CT.

The OP does

```
        var document = cy.state('document');
        var el = document.getElementById(ROOT_ID);
        var componentNode = document.createElement('div');
        el.append(componentNode);
```

Which is not really recommended - use `mount` via `import { mount } from 'cypress/vue` - that will handle everything (including cleanup before each test).

If you really need something custom, you can build your own mount function using the same APIs we do. There's a guide here: https://github.com/cypress-io/cypress/tree/develop/npm/mount-utils

**Comment by skjnldsv** [comment]
@lmiller1990 I also used `mount` via `import { mount } from 'cypress/vue'` and still experienced the same issue.

**Comment by lmiller1990** [comment]
Are you on Vue 2 or Vue 3?

- Vue 2 -> `import { mount } from 'cypress/vue2'`
- Vue 3 -> `import { mount } from 'cypress/vue'`

From Cypress 10 onwards, it should scaffold everything for you though - so it should "just work".

If this still does not help, can you share a minimal reproduction? I've got Vue 2 & 3 projects working fine, but it sounds like you've hit some kind of unexpected snag.

**Comment by skjnldsv** [comment]
It was vue2 with `cypress/vue2`

**Comment by lmiller1990** [comment]
You may need to share a minimal reproduction. I created a Vue 2 app using the Vue CLI and added Cypress and it's working correctly for me.

If you can share a minimal reproduction, I can reopen the issue and investigate it. Thanks!

**Comment by jdbdnz** [comment]
> Ah, found the issue, `ROOT_ID` expect a root element with the ID `__cy_root` ![image](https://user-images.githubusercontent.com/14975046/172906664-ada06340-b209-47c9-9bf2-2cd6d2caf87c.png)
> 
> Editing the `component-index.html` to this fixed it
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width,initial-scale=1.0">
>     <title>Components App</title>
>   </head>
>   <body>
>     <div id="__cy_root"></div>
>   </body>
> </html>
> ```

I did the guided upgrade and ran into this issue, then this solution worked for me.
