### ISSUE TITLE
.type() negative number into input not working

### ISSUE THREAD

**Issue by equistx** [cypress-io/cypress#2173]
### Current behavior:

When typing negative number into input **with type "number" set**, minus is ignored and possitive number is typed instead.

used method: `cy.type()`

![numbertypebug](https://user-images.githubusercontent.com/5154014/42937195-96441e52-8b4e-11e8-89f0-f7f366f0dce5.PNG)

### Desired behavior:

Type negative number.

### Steps to reproduce:

![html](https://user-images.githubusercontent.com/5154014/42937265-cff2d0a8-8b4e-11e8-8e05-9cd86ecfcc0e.PNG)

### Versions

Cypress: 3.0.2
Windows 10
Chrome 67

**Comment by Bkucera** [comment]
Hi, @equistx ,
This issue should be fixed in an upcoming 3.0.3 release, via this PR #2016

**Comment by Fenopiu** [comment]
In version 3.3.0 this bug is still on.
![Schermata 2019-05-22 alle 15 29 12](https://user-images.githubusercontent.com/33492735/58178539-ae2b4f00-7ca6-11e9-9615-226e397d853c.png)

**Comment by Bkucera** [comment]
> In version 3.3.0 this bug is still on.

@Fenopiu your screenshot and test code don't indicate this has anything to do with failing to type negative numbers

**Comment by jennifer-shehane** [comment]
@Fenopiu You likely want to assert on the 'value' inside of the span, not the span itself. Something like.

```js
it("Should be max 10", () => {
  cy.get(".count").invoke('text').then((text) => {
    expect(text).to.be.lessThan(11);
  })
})
```

**Comment by TheBestPessimist** [comment]
in v 3.4.0 i can confirm this bug still appears

**Comment by TheBestPessimist** [comment]
Also related: https://github.com/cypress-io/cypress/issues/480

**Comment by Bkucera** [comment]
@TheBestPessimist  

> in v 3.4.0 i can confirm this bug still appears.

0--? That's zero
0---12345? What?

**Comment by TheBestPessimist** [comment]
Here's the relevant piece of code:
```javascript
  cy.get('.form-field-MovementQty')
    .find('input')
    .type('{selectall}')
    .type(`-222`)
    .type('{enter}');

```

Here's a gif showing that instead of `-222`, cypress types `222` along with the request sent to the backend:
![cypress minus bug](https://user-images.githubusercontent.com/4482210/61512017-49b81200-aa01-11e9-8f18-5e4a3dbc6099.gif)


Here's the body of the frontend request: `[{"op":"replace","path":"MovementQty","value":"222"}]`, where it should have been `"value": "-222"`

**Comment by Bkucera** [comment]
@TheBestPessimist Ah I see the issue, we don't take into account that the input has a selection. You can workaround this by doing .clear() before .type() for now. I'll open an issue to fix this
