### ISSUE TITLE
Occasional TCP.get errors causing failing specs since updating to Cypress 10

### ISSUE THREAD

**Issue by liambutler** [cypress-io/cypress#22380]
### Current behavior

I'm very confused by a Cypress/lodash error I've been encountering since updating to Cypress 10. The end result is that the test fails and the job times out on the Cypress Dashboard.

No screenshots or recording because the spec never completed. Here's the Cypress Dashboard error message:

<img width="843" alt="Screenshot 2022-06-17 at 15 56 28" src="https://user-images.githubusercontent.com/24389501/174312722-f536bfcb-4e50-4c27-b511-524446b398a5.png">

And the lack of video/screenshots:
<img width="443" alt="Screenshot 2022-06-17 at 15 57 59" src="https://user-images.githubusercontent.com/24389501/174313128-ed681f94-fa99-42ce-9362-292e7b7b9151.png">

We're running our tests via Jenkins, with orchestration courtesy of the Cypress Dashboard. Here's the output for one of the affected jobs:

```
12:20:37  Cannot read properties of null (reading 'reading')
12:20:37  TypeError: Cannot read properties of null (reading 'reading')
12:20:37      at TCP.get [as reading] (node:_tls_wrap:634:27)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2730:27
12:20:37      at arrayEach (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
12:20:37      at baseClone (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
12:20:37      at arrayEach (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
12:20:37      at baseClone (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
12:20:37      at arrayEach (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
12:20:37      at baseClone (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
12:20:37      at arrayEach (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
12:20:37      at baseClone (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
12:20:37      at arrayEach (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
12:20:37      at baseClone (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
12:20:37      at Function.cloneDeep (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/lodash/lodash.js:11156:14)
12:20:37      at HttpBuffers.set (/app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/proxy/lib/http/util/buffers.js:26:32)
12:20:37      at Http.setBuffer (/app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/proxy/lib/http/index.js:221:29)
12:20:37      at NetworkProxy.setHttpBuffer (/app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/proxy/lib/network-proxy.js:19:19)
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/server/lib/server-e2e.js:248:103
12:20:37      at /app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/network/lib/concat-stream.js:22:16
12:20:37      at ConcatStream.<anonymous> (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/concat-stream/index.js:37:43)
12:20:37      at ConcatStream.emit (node:events:402:35)
12:20:37      at ConcatStream.emit (node:domain:475:12)
12:20:37      at finishMaybe (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:630:14)
12:20:37      at endWritable (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:638:3)
12:20:37      at ConcatStream.Writable.end (/app/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:594:41)
12:20:37      at Duplexify.onend (/app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:646:10)
12:20:37      at Object.onceWrapper (node:events:509:28)
12:20:37      at Duplexify.emit (node:events:390:28)
12:20:37      at Duplexify.emit (node:domain:475:12)
12:20:37      at endReadableNT (/app/.cache/Cypress/10.0.2/Cypress/resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
12:20:37      at processTicksAndRejections (node:internal/process/task_queues:83:21)
12:20:37      at runNextTicks (node:internal/process/task_queues:65:3)
12:20:37      at processImmediate (node:internal/timers:437:9)
```

I don't use lodash at all in my Cypress tests. And given that this started after updating to Cypress 10, I don't believe the issue is due to the specs themselves.

In the stack trace above, I see mentions of Duplexify. We definitely aren't using that in our tests, so I suspect that this is something to do with refactored video/screenshot upload logic in the newest Cypress

Just a hunch, but I noticed that [this file changed recently](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-e2e.ts). It's mentioned in the stack trace and it also uses lodash. Could it be something to do with that?

### Desired behavior

Desired outcome would be to no longer have this issue affecting our Jenkins runs and timing out on the Cypress Dashboard 

### Test code to reproduce

It'll be difficult for me to provide a reproducible example, as the issue seems dependent on Cypress' `TCP.get` not receiving a response from Cypress Dashboard.

I'd be happy to turn on debugging for one of our Jenkins jobs so that you have some more information, though. Just let me know what to add to give you the info you need, and I'll email it to Cypress.

### Cypress Version

10.1.0

**Comment by AtofStryker** [comment]
Hey @liambutler. Thank you for opening an issue and I'm sorry you are running into this. I am starting to take a look into this one and have a few ideas. In the meantime, would you be able to provide me with what version of Node is installed in Jenkins as well as what operating system? 

The error itself looks to be thrown from the cypress server [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-e2e.ts#L316) as you pointed out. From what I can see, we try to set the http buffer through the http proxy [here](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/index.ts#L336), which uses lodash to [clone the buffer object](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/buffers.ts#L35). It almost looks like this cloning process is failing due to some properties on the buffer object and shouldn't be directly related to lodash. I wonder if this is related to some of the issues we are seeing with the node TLS package in node version `16.13.2`, which is the version Cypress currently uses due to electron (ref #22291) 

To get some additional information, would you be able to run cypress with some debug flags on in Jenkins? I think we should be able to get good information with setting the `DEBUG` variable to `DEBUG=cypress:server:server-e2e,cypress-verbose:proxy:http,cypress:proxy:http:util:buffers npx cypress run …`. Could you take the console output from that and attach it to this issue?

**Comment by AtofStryker** [comment]
@liambutler what version of Cypress were you on before 10.x? I am curious if you used [9.7](https://docs.cypress.io/guides/references/changelog#9-7-0) before upgrading and noticed this issue, since we upgraded Electron then and might be a good signal for what the issue is/isn't.

**Comment by liambutler** [comment]
Hi @AtofStryker, thanks for looking into this!

- Node version for our Jenkins is `v16.5.0`. We're running it on Ubuntu, but not sure which version. Let me know if you need me to find out.
- Previous Cypress versions I was using were `9.5.4` and `9.6.1` (I maintain tests for a couple of projects). Never updated to 9.7, instead jumped straight to 10.
- I'll run a job with those `DEBUG` commands and send it over via email. Does it need to be from a failing job, or will any suffice?

**Comment by AtofStryker** [comment]
> Hi @AtofStryker, thanks for looking into this!
> 
> * Node version for our Jenkins is `v16.5.0`. We're running it on Ubuntu, but not sure which version. Let me know if you need me to find out.

OK perfect. It might be good to bump Node to version `16.13.2` if you can to keep the version of node synced with Cypress, since some processes use the [system](https://docs.cypress.io/guides/references/configuration#Node-version) version. I don't think this is causing your issue, but it might be good to rule out anything that might be causing a hiccup.

> * Previous Cypress versions I was using were `9.5.4` and `9.6.1` (I maintain tests for a couple of projects). Never updated to 9.7, instead jumped straight to 10.

Interesting. Do you still have the branches/commits using `9.5.4` and `9.6.1`? I wonder what happens if you create a branch off the commit right before you upgraded to `v10`, update to 9.7, and run in CI. Would you be able to do that or would that process be too involved?

> * I'll run a job with those `DEBUG` commands and send it over via email. Does it need to be from a failing job, or will any suffice?

@liambutler Should be from a failing/problematic job, since we want to be able to potentially see some options being set in the buffer to see if anything raises concern.

**Comment by AtofStryker** [comment]
@liambutler another thing we noticed that we found interesting is that the test seems to keep going, even though the failure is present it the logs, but the recorder is timing out. It might be good to add `cypress:server:record*` to the `DEBUG` logs as well. We are thinking the issue is trying to clone the buffer/TLSSocket when we cache the initial request for `cy.visit`. We might not actually need to clone this buffer object any longer, and am exploring removing the clone to see if there are any downstream impacts.

**Comment by liambutler** [comment]
@AtofStryker I've updated the node version to `16.13.2`. Was simple enough as we're running our cypress machines in containers.

Also got an example of the failure with the extra debug logs. I'll send them over

**Comment by gkreitz** [comment]
> @liambutler what version of Cypress were you on before 10.x? I am curious if you used [9.7](https://docs.cypress.io/guides/references/changelog#9-7-0) before upgrading and noticed this issue, since we upgraded Electron then and might be a good signal for what the issue is/isn't.

Just to add a data point to your investigation - I've just run into the exact same error. Still on 9.7, running cypress in the official docker image `cypress/included:9.7.0`.

**Comment by liambutler** [comment]
Good to know. Thanks for the additional context, @gkreitz!

**Comment by fsnopek** [comment]
Started to notice these as well on **10.1.0** when running on **Electron**. After switching to **Chrome** this error disappeared
Another issue with maybe same root cause? https://github.com/cypress-io/cypress/issues/22291

**Workaround:**
Run tests using Chrome

**Comment by GreenRover** [comment]
I see the same with: 9.7.0

**Comment by natapg** [comment]
> Started to notice these as well on **10.1.0** when running on **Electron**. After switching to **Chrome** this error disappeared Another issue with maybe same root cause? #22291
> 
> **Workaround:** Run tests using Chrome

in that same issue  #22291 there are people who use Chrome and Chromium and have the same problem, so it's not a workaround to use chrome

**Comment by GreenRover** [comment]
For me changing to electron -> chromium improved the situation.
With electron 4 of 5 tests are showing the issue.
With chromium now 4 tests passed in row

**Comment by Viserius** [comment]
We are running into the same issue here, also on Jenkins. We are on version 9.7.0 and experience the same on v10.
The exceptions seem to be very random in nature. Sometimes, the exception does not occur, and sometimes it does on the same test.

**Comment by verheyenkoen** [comment]
Same issue on GitHub Actions with latest release 10.2: https://github.com/ugent-library/lludss-interface-tests/runs/7000368233 (seen it on 10.1 as well)

**Comment by AtofStryker** [comment]
> @AtofStryker We're running the `cypress/base:16.13.2` image, so I'll need to try with one of the images that includes Chrome. I'll get back to you tomorrow
> 

@liambutler the [cypress/browsers:node16.13.2-chrome100-ff98](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node16.13.2-chrome100-ff98) image in this case might work really well here. 

> My only concern with this as a long-term workaround is that Chrome requires much more resources to run, or is that not correct?

It's possible, but it shouldn't require a ton more resources than headless chromium since they are based off the same engine. The goal here would be to have this a short-term work around to use chrome to circumvent the error while we work as a team to prioritize the Electron version 19 upgrade, which we are hoping solves some of these issues since it bumps the node version that fixes some of the known issues with the `node_tls` wrapper. That being said, I want to be sure that this is something comfortable with you.

**Comment by AtofStryker** [comment]
> Same issue on GitHub Actions with latest release 10.2: https://github.com/ugent-library/lludss-interface-tests/runs/7000368233 (seen it on 10.1 as well)

@verheyenkoen that unfortunately sounds correct. This is very likely an issue with the node version that is packages with electron `18.x`, which Cypress uses. Likely the fix for this would be for us to upgrade Electron to `19.x`, which bumps the node version that hopefully fixes some of the issues we are seeing. That being said, a reproduction would be incredibly useful here so we could test it with the upgrade to confirm our suspicions.

**Comment by liambutler** [comment]
> That being said, a reproduction would be incredibly useful here so we could test it with the upgrade to confirm our suspicions.

@AtofStryker If you've got a build that I can access, I can run it on my Jenkins Job to give you some confidence

**Comment by verheyenkoen** [comment]
@AtofStryker We don't have it consistently. Around one in 5 or 10 runs.

**Comment by AtofStryker** [comment]
> > That being said, a reproduction would be incredibly useful here so we could test it with the upgrade to confirm our suspicions.
> 
> @AtofStryker If you've got a build that I can access, I can run it on my Jenkins Job to give you some confidence

We are going to work to get something together hopefully within the next few weeks that works on Electron v19 that may confirm that it fixes the issue. It does seem weird that the issue does happen intermittently, almost like a CI box has some stale dependencies. @emilyrohrbough has a bit of a hunch that openSSL (I guess in this case boringSSL) might be out of date, which is causing the buffer clone to fail when doing a `cy.visit` since the stream might have terminated early, which is also a plausible explanation for this type of behavior. Hopefully we can start ruling some things out once we are a bit closer to having an upgrade available.

**Comment by AtofStryker** [comment]
> @AtofStryker We don't have it consistently. Around one in 5 or 10 runs.

Even if it is an intermittent reproduction it could be really useful. As long as we can hopefully see the error 😄 . And it completely goes away when you are running Chrome? What version of chrome is being used that completely eliminates the problem?

**Comment by verheyenkoen** [comment]
I guess you could just fork [our repo](https://github.com/ugent-library/lludss-interface-tests/) then. It's public code and runs against a public website. Just create another Cypress dashboard project, change the projectId and configure the secure record token.

**Comment by AtofStryker** [comment]
@verheyenkoen that sounds like a plan! When I get some availability, I am going to give it a shot with forking, setting up CI, and updating configurations. This should give us a reproducible example.

**Comment by zgrybus** [comment]
The same with `"cypress": "^10.2.0"` and npm `16.14.0` version :(

**Comment by VinothTesting7** [comment]
@AtofStryker @liambutler  Did you guys find any workaround for this? I am facing the same exact issue in Gitlab pipeline execution.   
 Cypress:        10.3.0                                                                         │
 Browser:        Electron 100 (headless)                                                        
 Node Version:   v16.14.0  . Please help me out. Thanks.

**Comment by zgrybus** [comment]
Any progress? 
@AtofStryker

**Comment by hydrapolic** [comment]
Same here, after upgrading from cypress 9.7 to 10.3 I've occasional failures:

```
18:10:34    ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
18:10:34    │ Cypress:        10.3.1                                                                         │
18:10:34    │ Browser:        Electron 100 (headless)                                                        │
18:10:34    │ Node Version:   v16.14.2 (/usr/local/bin/node)                                                 │
18:10:34    │ Specs:          4 found (00_meteorologicke_spravodajstvo.cy.js, 01_hydrologicke_spravodajstvo. │
18:10:34    │                 cy.js, 02_spravodajstvo_kvality_ovzdusia.cy.js, 03_klimatologicke_spravodajstv │
18:10:34    │                 o.cy.js)                                                                       │
18:10:34    │ Searched:       cypress**/*.cy.{js,jsx,ts,tsx}                                                 │
18:10:34    └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
18:11:37  Cannot read properties of null (reading 'reading')
18:11:37  TypeError: Cannot read properties of null (reading 'reading')
18:11:37      at TCP.get [as reading] (node:_tls_wrap:634:27)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2730:27
18:11:37      at arrayEach (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
18:11:37      at baseClone (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
18:11:37      at arrayEach (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
18:11:37      at baseClone (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
18:11:37      at arrayEach (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
18:11:37      at baseClone (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
18:11:37      at arrayEach (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
18:11:37      at baseClone (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
18:11:37      at arrayEach (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
18:11:37      at baseClone (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
18:11:37      at Function.cloneDeep (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/lodash/lodash.js:11156:14)
18:11:37      at HttpBuffers.set (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/proxy/lib/http/util/buffers.js:26:32)
18:11:37      at Http.setBuffer (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/proxy/lib/http/index.js:226:29)
18:11:37      at NetworkProxy.setHttpBuffer (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/proxy/lib/network-proxy.js:19:19)
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/server/lib/server-e2e.js:248:103
18:11:37      at /root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/network/lib/concat-stream.js:22:16
18:11:37      at ConcatStream.<anonymous> (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/concat-stream/index.js:37:43)
18:11:37      at ConcatStream.emit (node:events:402:35)
18:11:37      at ConcatStream.emit (node:domain:475:12)
18:11:37      at finishMaybe (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:630:14)
18:11:37      at endWritable (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:638:3)
18:11:37      at ConcatStream.Writable.end (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:594:41)
18:11:37      at Duplexify.onend (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:646:10)
18:11:37      at Object.onceWrapper (node:events:509:28)
18:11:37      at Duplexify.emit (node:events:390:28)
18:11:37      at Duplexify.emit (node:domain:475:12)
18:11:37      at endReadableNT (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/server/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
18:11:37      at processTicksAndRejections (node:internal/process/task_queues:83:21)
18:11:37      at runNextTicks (node:internal/process/task_queues:65:3)
18:11:37      at processImmediate (node:internal/timers:437:9)
```

Switching to chrome, hope it helps.

**Comment by AtofStryker** [comment]
> Any progress? @AtofStryker

I am back on rotation this week and next and am hoping to take a look into this!

**Comment by AtofStryker** [comment]
So far I have forked @verheyenkoen 's project and have run `yarn test` inside the project directory about 15 times. I haven't run into the issue yet, but I am also on node version `16.15.0`. I'm going to downgrade to `16.14.2` and try to continue to reproduce the issue. 

In the meantime, would anyone be able to upgrade to Cypress `10.4.0` and try this out? #22291 was related to a known issue that was patched in Node `16.14.2`, and am wondering if the subprocess Electron is using is the packaged node version (see https://github.com/cypress-io/cypress/issues/22291#issuecomment-1154782275), (which I believe is `16.13.2` from #22775). However, I haven't been able to find an issue in [node](https://github.com/nodejs/node) that would suggest this is an issue, but want to possibly rule this hunch out.

**Comment by verheyenkoen** [comment]
@AtofStryker Haven't had the issue since the upgrade but we've only had 4 runs since (so the upstream of the test repo has been upgraded to 10.4).

**Comment by pfiorentino-zendesk** [comment]
We currently are on the `10.3.1` and the issue is still happening.

I plan to upgrade our Cypress to `10.4.0` very soon (early next week 🙏).
I originally planned to do it today, but... heh... you know... day-to-day emergencies ¯\_(ツ)_/¯ 

Once done, I will keep you posted (we use to have 5 to 10 runs a day, if the issue persists, it should be spotted quickly)

**Comment by pfiorentino-zendesk** [comment]
Ok, folks!

I deployed the `10.4.0` on our side yesterday in the morning (9 AM UTC).
We had 15 green runs and 0 red since.

I will keep an eye on the logs for another day or two, but it's very promising!

I'll keep you posted!

**Comment by pfiorentino-zendesk** [comment]
I can confirm the issue seems to be solved 😎.

Since the upgrade to `v10.4.0` we had 35+ green runs, and 0 red.

Thanks folks 😊👍

**Comment by zgrybus** [comment]
The same :) It has been fixed

**Comment by AtofStryker** [comment]
Great news to hear from those where the problem seems to resolve with the electron upgrade. We decided to close the issue as we believe it is resolved, but if it is still an issue for anyone please let us know!

**Comment by StaNov** [comment]
The issue is still occuring in our environment.

We use `cypress/included:10.7.0` image, running in GitLab CI, both on-premise runners and Kubernetes runner in Google Cloud.

It happens intermittently, approx. in one of twenty runs.

```
TypeError: Cannot read properties of null (reading 'reading')
    at TCP.get [as reading] (node:_tls_wrap:634:27)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2730:27
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at Function.cloneDeep (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:11156:14)
    at HttpBuffers.set (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/http/util/buffers.js:28:32)
    at Http.setBuffer (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/http/index.js:211:29)
    at NetworkProxy.setHttpBuffer (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/network-proxy.js:19:19)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/server-e2e.js:241:103
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/network/lib/concat-stream.js:24:16
    at ConcatStream.<anonymous> (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (node:events:402:35)
    at finishMaybe (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
TypeError: Cannot read properties of null (reading 'reading')
    at TCP.get [as reading] (node:_tls_wrap:634:27)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2730:27
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:530:11)
    at baseClone (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:2727:7)
    at Function.cloneDeep (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lodash/lodash.js:11156:14)
    at HttpBuffers.set (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/http/util/buffers.js:28:32)
    at Http.setBuffer (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/http/index.js:211:29)
    at NetworkProxy.setHttpBuffer (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/proxy/lib/network-proxy.js:19:19)
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/server-e2e.js:241:103
    at /root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/network/lib/concat-stream.js:24:16
    at ConcatStream.<anonymous> (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (node:events:402:35)
    at finishMaybe (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
```

**Comment by AtofStryker** [comment]
@StaNov it looks like the version of Cypress that is running here is `9.7.0` from the cache. Have you tried clearing the cached installs or verify `10.7.0` is installed?

**Comment by StaNov** [comment]
@AtofStryker Thank you for your response.

I tried to pull the image again and it really looks like a mistake on the Cypress side - there is version `9.7.0` pushed as `10.7.0`.

I tried the new one `10.8.0` and it looks that it works so far.

**Comment by AtofStryker** [comment]
@StaNov glad that bumping to `10.8.0` fixes your issue. It does look like `10.7.0` is installed in the [image](https://github.com/cypress-io/cypress-docker-images/blob/master/included/10.7.0/Dockerfile#L36). I'm interested to see if you run into this problem again, but it seems odd that a cached `9.7.0` would exist inside a fresh docker image. Either way, if you run into the issue again, please let us know!

**Comment by StaNov** [comment]
Hi @AtofStryker, I am sorry for creating this confusion.

The issue was that I missed that we were installing Cypress via npm on the image, so the native `10.7.0` got replaced by `9.7.0`.
