### ISSUE TITLE
"Cookies are disabled" issue with Epic Hyperspace in Cypress 10.3.0

### ISSUE THREAD

**Issue by ganeshac123** [cypress-io/cypress#22670]
### Current behavior

Cookies are disabled. Please enable cookies to log in to Hyperspace with a browser.

Note: take a look at the screenshot for reference.

<img width="1792" alt="Screenshot 2022-07-04 at 9 58 43 AM" src="https://user-images.githubusercontent.com/89897004/177082760-356cdbb2-75f7-4289-9ddd-aef0be7bae22.png">
<img width="1792" alt="Screenshot 2022-07-04 at 9 58 56 AM" src="https://user-images.githubusercontent.com/89897004/177082773-9a59b626-41b0-4fa5-9ed8-a7f444e2171e.png">

Cypress Version
10.3.0

### Desired behavior

Cypress should allow cross origin as I am using recent version of cypress(10.3.0) this issue reportedly solved.

### Test code to reproduce

Test code to reproduce
describe('Note creation flow for Epic user tests', function () {
  it('cy.get() - Login to Suki as a Physician', function () {

    cy.login(USER_PERSONA.EPICUSER)
      .wait(2000)
      .xpath('(//button[@type="button"])[2]').click()
      .wait(6000)

    cy.origin("https://apporchard.epic.com/HSWeb_aocurprd/", ()=>{
      cy.get('#txtUserID').should('be.visible').type('****')
      .get('#txtPassword').should('be.visible').type('******')
      .get('#btnLogin').click()
    })
})

### Cypress Version

10.3.0

### Other

In recent version of cypress that is 10.3.0, cypress team members informed us that this cookie issue will be solved but it is not solved yet, reference of old bug: https://github.com/cypress-io/cypress/issues/20685

**Comment by ganeshac123** [comment]
Hi Chris,

For MacOS (Intel) I install cypress using link give by you, but I not able
to open the application, Can you please guide to how to install it?

**Comment by chrisbreiding** [comment]
It might be easiest to install it globally:

```
npm install -g https://cdn.cypress.io/beta/npm/10.3.1/darwin-x64/develop-a9476ecb3d43f628b689e060294a1952937cb1a7/cypress.tgz
```
 
Then the cypress cli will be available globally and you can run:

```
cypress open --e2e --project <path to your project>
```

**Comment by ganeshac123** [comment]
When I above command folder is not getting created rather yarn.locn,
package.json are installed in my file path.

**Comment by ganeshac123** [comment]
Both ways, generally use npm command is--> npm run cypress:open to open

**Comment by chrisbreiding** [comment]
In that case, install it non-globally (no `-g`) within your project's directory (where the package.json is):

```
npm install https://cdn.cypress.io/beta/npm/10.3.1/darwin-x64/develop-a9476ecb3d43f628b689e060294a1952937cb1a7/cypress.tgz
```

It will replace the local copy of cypress and you can run `npm run cypress:open` to open it. If it's working correctly, it will say `It looks like this is your first time using Cypress: 10.3.1` in the terminal and then you'll see `10.3.1` in the top-right of Cypress's UI. That way you'll know it's running the pre-release version.

**Comment by ganeshac123** [comment]
I have installed recent cypress version 10.3.1 and ran test which was
giving error, still I am getting same error, Please see the attached
screenshot for reference.

**Comment by ganeshac123** [comment]
Yes, same error please find attached file(screenshot)  to see error..


Before visiting epic I visit : https://app.suki-test.com/


code to reproduce:

  it('cy.get() - Login to Suki as a Physician', function () {
    cy.login(USER_PERSONA.EPICUSER)
      .reload(true)
      .wait(2000)

      .***@***.***="button"])[2]').click()
      .wait(6000)

    cy.origin("https://apporchard.epic.com/HSWeb_aocurprd/", ()=>{
      cy.get('#txtUserID').should('be.visible').type('SUKIAIR')
      .get('#txtPassword').should('be.visible').type('4kx*nEgmVBzBuPGXS?eJ')
      .get('#btnLogin').click()

    })
})

**Comment by chrisbreiding** [comment]
Can you share the code for your `cy.login()` custom command implementation?

**Comment by ganeshac123** [comment]
cy.visit(https://app.suki-test.com/)
        .clearLocalStorage()
        .get('[data-cy=textfield-username]', { timeout: 90000 }).type(id ||
Cypress.env('ciuser'))
        .get('[data-cy=textfield-password]').type(pwd ||
window.atob(Cypress.env('cipwd')))
        .get('[data-cy=btn-login]').click()
})

**Comment by ganeshac123** [comment]
No, I can't.

**Comment by ganeshac123** [comment]
After logging in, we are navigated to Epic web page this is where I am
facing that issue.

**Comment by chrisbreiding** [comment]
> No, I can't.

I completely understand.

> After logging in, we are navigated to Epic web page this is where I am facing that issue.

If I directly visit the Epic web page, it shows an error immediately and not the login fields. It seems the initial login is necessary to recreate the issue.

If you can provide a way to reliably reproduce the issue without using credentials, I can look further into it. Otherwise, it will be difficult to find a path forward debugging this.

**Comment by ganeshac123** [comment]
Here is Creds for intital login:

email: ***@***.***

password: NTC-gzg9ypc_tpb6brg



Please look into this, let me know the resolution for it as soon as
possible.


Thank you,

Ganesh

**Comment by chrisbreiding** [comment]
I think GitHub auto-redacted the email address you sent. It appears as `***@***.***`. Might need to send it in a form like `foo [at] bar [dot] com` instead.

**Comment by ganeshac123** [comment]
Any updates?

**Comment by chrisbreiding** [comment]
I still can't see the email address you sent. If you send it in the format `foo [at] bar [dot] com`, it should come through in a way I can read it.

**Comment by ganeshac123** [comment]
email: testepicin [at] suki[dot] ai ***@***.***>

password: NTC-gzg9ypc_tpb6brg

**Comment by ganeshac123** [comment]
email: testepicin [at] suki[dot] ai

**Comment by ganeshac123** [comment]
@chrisbreiding Please check now

**Comment by ganeshac123** [comment]
Waiting for solution

**Comment by mjhenkes** [comment]
@ganeshac123, I was able to reproduce the issue and have a reproduction in this repo: https://github.com/mjhenkes/epic-cookie-22670, it is private as it contains usernames and passwords. We'll now route this to the e2e auth team for prioritization.

**Comment by ganeshac123** [comment]
Great, thanks for the update.

**Comment by ganeshac123** [comment]
@mjhenkes How long it takes? Is there any update on this issue?

**Comment by mjhenkes** [comment]
I dug into this issue today. It appears that we have a race condition between the Epic javascript that executes synchronously on load that checks the presence of the cookies and the the Cypress logic that applies the cookies asynchronously after load.
https://github.com/cypress-io/cypress/blob/41a0271c345c0e4191b5ab7645d64be0b340d2db/packages/driver/src/cypress/cy.ts#L386-L400

We don't apply the cookies during load because Firefox will not allow us to set anything via automation during load.

We might need to see if Firefox supports enough of the cookies CDP api for us to switch to it. That might allow us to set cookies before the page loads, though it’s also possible Firefox still won’t allow that even with CDP.

**Comment by ganeshac123** [comment]
Ok, thanks for the clarification. Please update the proposed solution soon.

**Comment by ganeshac123** [comment]
@mjhenkes Any update on this,  If firefox is problem we can go ahead with chrome and electron we don't need firefox

**Comment by ganeshac123** [comment]
@mjhenkes Hi Any updates

**Comment by ganeshac123** [comment]
@mjhenkes @chrisbreiding Hi Any updates, waiting from 10 days for the update on this ticket

**Comment by ganeshac123** [comment]
@mjhenkes @chrisbreiding Hi Any updates, waiting from 10 days for the update on this ticket

**Comment by AtofStryker** [comment]
@ganeshac123 apologizes for the delay. We should be looking into cookie issues this sprint.

**Comment by ganeshac123** [comment]
Ok, thanks for the update. Please give resolution to this issue, This has
been pending from many months now

**Comment by mschile** [comment]
Hi @ganeshac123, thank you for your patience. We are actively working on cookie issues and plan to have them released in a little over two weeks.

**Comment by ganeshac123** [comment]
@chrisbreiding @nagash77 Hi Any updates on this ? you had only 2 weeks but we are already passed 4 weeks? please let us know if you are not able fix this because this ticket opened 3 months still no update on this?

**Comment by ganeshac123** [comment]
@chrisbreiding @nagash77 @cy-veronica @mschile @cypress-app-bot  Hi Any updates on this ? you had only 2 weeks but we are already passed 4 weeks? please let us know if you are not able fix this because this ticket opened 3 months still no update on this?

**Comment by mschile** [comment]
@ganeshac123, thank you for your continued patience. I know it can be frustrating waiting for updates/changes but I can assure you we are continually working on cookie improvements. I do have some good news, using the reproduction project [here](https://github.com/cypress-io/cypress/issues/22670#issuecomment-1190668162), I was able to test your workflow using the changes from PR https://github.com/cypress-io/cypress/pull/23872 and did not receive the "Missing service token" error. We expect this PR to be merged very soon and at that point you can install the [pre-release version](https://docs.cypress.io/guides/references/advanced-installation#Install-pre-release-version) to verify your issue is resolved.

**Comment by ganeshac123** [comment]
Please let me know when the PR is merged or when the pre release version is available @mschile

**Comment by mschile** [comment]
@ganeshac123, clicking the link above for the PR will show you the status. It was merged 3 days ago. You can install any of the pre-releases since then. Here is the latest one https://github.com/cypress-io/cypress/commit/3e014743909b35f54b697d2a759e4a2c5b67b5b7#comments

linux (x64): `npm install https://cdn.cypress.io/beta/npm/10.10.0/linux-x64/develop-3e014743909b35f54b697d2a759e4a2c5b67b5b7/cypress.tgz`

linux (arm64): `npm install https://cdn.cypress.io/beta/npm/10.10.0/linux-arm64/develop-3e014743909b35f54b697d2a759e4a2c5b67b5b7/cypress.tgz`

MacOS (M1/M2): `npm install https://cdn.cypress.io/beta/npm/10.10.0/darwin-arm64/develop-3e014743909b35f54b697d2a759e4a2c5b67b5b7/cypress.tgz`

MacOS (Intel): `npm install https://cdn.cypress.io/beta/npm/10.10.0/darwin-x64/develop-3e014743909b35f54b697d2a759e4a2c5b67b5b7/cypress.tgz`

Windows: `npm install https://cdn.cypress.io/beta/npm/10.10.0/win32-x64/develop-3e014743909b35f54b697d2a759e4a2c5b67b5b7/cypress.tgz`

**Comment by AtofStryker** [comment]
Closing as complete with https://github.com/cypress-io/cypress/pull/23872. @ganeshac123 this should be release `10.10.0` this afternoon EST. Can you confirm once the release is available that this issue is fixed?

**Comment by ganeshac123** [comment]
Ok, tomorrow Morning My time will and let you know.

**Comment by ganeshac123** [comment]
Hi Bell,

I tested this issue with Cypress 10.0.0 new version, still this issue is
not fixed check attached screenshot for your reference.

Please look into this asap, We are waiting for this fix for 6 months but
still no proper update from the Cypress team even after many escalations.
Let us know if you are not able to fix from your end?

**Comment by AtofStryker** [comment]
Hey @ganeshac123 . I'm sorry to hear this didn't fix your issue. Just to clarify, you tested with `10.10.0`? I cannot see an attached screenshot which could be very useful here.

**Comment by ganeshac123** [comment]
Yeah, I did tested with 10.10.0.

**Comment by AtofStryker** [comment]
@ganeshac123 OK Thank you for confirming. We thought the issue was fixed because it happens intermittently for us, but we think we have an idea what is going on with the initial cookies set by hyperspace. We are working on a solution and will keep you updated.

**Comment by AtofStryker** [comment]
@ganeshac123 With the implementation of #23531 & #23643 this should unblock the epic login issues to the point where it gets passed "cookies are disabled" and should be in the release next week for Cypress `10.11.0`

**Comment by ganeshac123** [comment]
Thanks for the update, please let me know once the issue resolved.

**Comment by AtofStryker** [comment]
@ganeshac123 it should be resolved with Tuesday's release. I am hoping you can download Cypress 10.11.0 at that time and confirm the issue is resolved for you.

**Comment by chrisbreiding** [comment]
@ganeshac123, thanks for your patience as we've worked through this. Cypress 10.11.0 is now out, which should resolve your issue. Please let us know if you can confirm that you no longer encounter the `Browser cookies were cleared` alert.

**Comment by ganeshac123** [comment]
Hi @chrisbreiding @AtofStryker  downloaded Cypress 10.11.0 from cypress website, tested browser cookies issue. Looks like issue is not resolved yet.

<img width="1792" alt="Screenshot 2022-11-08 at 10 25 44 AM" src="https://user-images.githubusercontent.com/89897004/200540887-2071633c-a7a0-43f2-836a-775caa865261.png">

**Comment by ganeshac123** [comment]
Hi @chrisbreiding @AtofStryker downloaded Cypress 10.11.0 from cypress website, tested browser cookies issue. i

hi Guys any updates on this, waiting for this issue to solved from one year? Let us know if @cypress-github-team-services-sa is not able to solve it, we can do something from our end?

**Comment by AtofStryker** [comment]
Hi @ganeshac123 are you running the binary directly? I am running the following test in `11.1.0` installed from npm:
```
  cy.visit('https://app.suki-test.com')
  .clearLocalStorage()
  .get('[data-cy=textfield-username]', { timeout: 90000 }).type('****')
  .get('[data-cy=textfield-password]').type('****')
  .get('[data-cy=btn-login]').click()

  cy.wait(2000)
  .get('.ant-btn-primary').click()

  cy.origin("https://appmarket.epic.com", ()=>{
    cy.get('#txtUserID').should('be.visible').type('****')
    .get('#txtPassword').should('be.visible').type('*****')
    .get('#btnLogin').click()
  })
```
I have run this multiple times and am unable to reproduce the issue. Is there something about our test set up that is different? It doesn't like like a `cy.origin` block is declared in the screenshot above, which is needed to patch the cookie context correctly. Is that the case?
![epic-working](https://user-images.githubusercontent.com/3980464/202247051-5f45f429-4d24-4521-9948-230a7aa5e6d2.gif)

**Comment by ganeshac123** [comment]
Where did you enable "experimentalSessionAndOrigin" flag? If I don't enable this flag I am getting error asking for enabling this, If I enable this flag in cypress config, I am not able to any files

**Comment by AtofStryker** [comment]
> Where did you enable "experimentalSessionAndOrigin" flag? If I don't enable this flag I am getting error asking for enabling this,

@ganeshac123 I have `experimentalSessionAndOrigin` enabled in my `cypress.config.js` since it needs to be enabled at launch of the server to handle `cy.origin`. To get cookies to work in this scenario, the `experimentalSessionAndOrigin` flag needs to be enabled. 

> If I enable this flag in cypress config, I am not able to any files

What do you mean by this? I am not sure I understand completely.

**Comment by ganeshac123** [comment]
I have enabled experimentalSessionAndOrigin flag in cypress.config.js file, after enabling this I am not able to run any files in cypress application(web app downloaded from cypress.io)

**Comment by AtofStryker** [comment]
@ganeshac123 I'm sorry but I'm still not entirely sure what that means. Is there an error being thrown? Could you share a screenshot?

**Comment by ganeshac123** [comment]
Check the screenshot for error is displayed when trying to run file.
<img width="1634" alt="Screenshot 2022-11-21 at 10 54 41 AM" src="https://user-images.githubusercontent.com/89897004/202972163-a91fe25c-fa8f-4066-aea0-9b5e376baab1.png">

**Comment by AtofStryker** [comment]
@ganeshac123 this just means you need to change this:
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  experimentalSessionAndOrigin: true,
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

to this:

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    experimentalSessionAndOrigin: true,
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

can you try that and report back to let us know if it fixed your issue?

**Comment by ganeshac123** [comment]
Now it's working. This issue is resolved now, it was pending from long long time.. Thanks for fixing this @AtofStryker 👍

**Comment by AtofStryker** [comment]
That's great to hear! Thank you for patience and helping us get this working. Let us know if you run into other trouble!
