### ISSUE TITLE
Upload CI Result Error: "Cannot complete same instance multiple times"

### ISSUE THREAD

**Issue by HeyDaniyar** [cypress-io/cypress#2469]
### Current behavior:

Our `Jenkins CI` job's result cannot not be uploaded to Cypress CI Dashboard. 

```
Jenkins CI logs:
  (Uploading Results)

Warning: We encountered an error talking to our servers.

This run will not be recorded.

This error will not alter the exit code.

StatusCodeError: 400 - "Cannot complete same instance multiple times"

================================================================================
  (Run Finished)


      Spec                                    Tests  Pass…  Fail…  Pend…  Skip… 
  ┌────────────────────────────────────────────────────────────────────────────┐
  │ ✖ ads_html5_sdk.js               1:38:…    175    167      8      -      - │
  └────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)              1:38…    175    167      8      -      -  


───────────────────────────────────────────────────────────────────────────────────
                                                                                   
  Recorded Run: https://dashboard.cypress.io/#/projects/f92sa3/runs/6             
```

Cypress Dashboard:
![image](https://user-images.githubusercontent.com/5592808/45525989-e325fe80-b807-11e8-95f5-687bc7103fef.png)

### Desired behavior:
Normally, the triggered jenkin's job  would upload its result to CI dashboard before. But after the CI dashboard uploaded, we cannot  make this happened with the `Cannot complete same instance multiple times`  error.

### Versions

Cypress 3.1.0

**Comment by jennifer-shehane** [comment]
Hi, can you include the arguments you used to run cypress? So, flags after `cypress run`.

This should not happen though.

**Comment by HeyDaniyar** [comment]
This is the arguments we uesed to run cypress, besides record key, we passed an environment variable to our case.
``` shell
> cypress run "--env" "ipList=[\"167.114.174.45\"]" "--record" "--key" "b34e1f4f-b684-4def-92e8-fac7fb98e8c4"

It looks like this is your first time using Cypress: 3.1.0

[02:07:35]  Verifying Cypress can run /root/.cache/Cypress/3.1.0/Cypress [started]
[02:07:37]  Verifying Cypress can run /root/.cache/Cypress/3.1.0/Cypress [completed]

Opening Cypress...

================================================================================

  (Run Starting)
```

**Comment by jennifer-shehane** [comment]
@HeyDaniyar Are you still encountering this error? 

I ran a run with the same flag arguments and I do not think that is the problem. 

Can you share anything more about your Jenkin's setup?

**Comment by katsiaryna-yurasova-zefr** [comment]
Hello. I also face this issue at the Jenkins side.
I use the Jenkins file to run cypress. This is a piece of it:
...
 stage('Testing Install and Run') {
      when {
        equals expected: "master", actual: env.BRANCH_NAME
      }
      steps{
        script{
          docker.image('cypress/base:8').inside('--ipc=host -u root'){
            sh("npm install")
            sh("npx cypress run --record --key ${usage_key} || true")
          }
        }
      }
      post {
        failure {
          script {
            overview.add "Error: Testing Stage"
          }
        }
      }
    }
...

**Comment by katsiaryna-yurasova-zefr** [comment]
I would like to pay attention that docker is run with a flag:
docker run --ipc=host
because previously I fixed an issue with docker crashes:
https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772

It fixed the crash itself but the issue of this kind started to reproduced. As a result, test execution is completed but takes to long: 5h against 31min.

**Comment by muslaydin** [comment]
So how to fix this problem?
![fail](https://user-images.githubusercontent.com/43794444/50025252-e80c7100-fff5-11e8-9e32-50351493c74d.png)

**Comment by jennifer-shehane** [comment]
We've made many improvements to our processes handling recording that should resolve most cases of this error.

Please comment in this issue if you see an occurrence of this error in the future and we will reopen the issue.

**Comment by sergeyKhristenko** [comment]
Seems like I'm seeing the same error now

**Comment by jennifer-shehane** [comment]
@sergeyKhristenko Can you open a new issue detailing the env vars, settings, and config you have running when you get this error?

**Comment by jennifer-shehane** [comment]
Reopening. We've had a couple of users report this same error again when attempting to record CI results. The API team is investigating.

**Comment by andy-lindberg** [comment]
Been seeing a similar issue with our environment as well today 😞

**Comment by trydionel** [comment]
We released a fix for one of the edge cases that would trigger this. It went out July 24, so hopefully it addressed your issues @sergeyKhristenko and @andy-lindberg! If you continue seeing this failure, would you mind to share your CI logs?

Closing this issue pending additional reports.

**Comment by sorokosergey** [comment]
Hello everyone! test runs are timing out at the 2hr 6min mark consistently. Is there a timeout limit that can be set for this? I launch the test run locally. I have the following logs 
![image](https://user-images.githubusercontent.com/58261406/70889117-ddaef980-1ff2-11ea-9469-e5bf637f0700.png)
![image](https://user-images.githubusercontent.com/58261406/70889223-1b138700-1ff3-11ea-8e07-1c533ea60f8e.png)

**Comment by mhudson** [comment]
HI @trydionel, this issue persists in Cypress **3.6.1**

`Cannot find unclaimed instance for spec: tests\\e2e\\specs\\01-customer\\04-life\\NewUser.spec.js`

Looks like Windows 10 path issue discussed elsewhere, but the fault appears to lie within Cypress on Windows. Cypress is converting our spec path :`tests/e2e/specs/*/04-life/*.spec.js` to  path (with double-slashes) `tests\\e2e\\specs\\01-customer\\04-life\\...`

We're running:
`yarn run e2e:04-life-all --record --reporter teamcity --group LIFE --ci-build-id 1912.0.0.75`

which expands to: 
`cypress run --browser chrome --spec 'tests/e2e/specs/*/04-life/*.spec.js' --record --reporter teamcity --group LIFE --ci-build-id 1912.0.0.75`

**Comment by jennifer-shehane** [comment]
@mhudson We are unaware of an issue involving the Windows path causing this error. We have a lot of Windows users, so if it were the path alone, we would likely have seen it by now. Likely there is something else more specific involved causing this error for your project. 

Can you email us the `projectId` this error is occurring within to support@cypress.io. This will help us track down any failed requests. You can find this id in the `cypress.json` file of the project.

**Comment by jennifer-shehane** [comment]
Our team is currently working to deploy a fix that should address both @mhudson and @sorokosergey errors seeing the "Cannot complete same instance multiple times". 

I will close this issue as soon as that fix is released.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
