### ISSUE TITLE
Cypress install fails during download; 530 error status

### ISSUE THREAD

**Issue by brettdh** [cypress-io/cypress#25876]
### Current behavior

A CI job that was successfully downloading Cypress yesterday failed today, with no related changes. The error appears the same as #23527, but I don't see any issues reported on https://www.cypressstatus.com/ today.

### Debug logs

```Text
$ yarn install
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /builds/my/project/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /builds/my/project/node_modules/cypress
Output:
Installing Cypress (version: 7.7.0)
[STARTED] Task without title.
[FAILED] The Cypress App could not be downloaded.
[FAILED] 
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
[FAILED] 
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] URL: https://download.cypress.io/desktop/7.7.0?platform=linux&arch=x64
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 530
[FAILED] Response message:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux (Amazon Linux - 2 (Karoo))
[FAILED] Cypress Version: 7.7.0
The Cypress App could not be downloaded.
Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
Otherwise, please check network connectivity and try again:
----------
URL: https://download.cypress.io/desktop/7.7.0?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 530
Response message:
----------
Platform: linux (Amazon Linux - 2 (Karoo))
Cypress Version: 7.7.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Cypress Version

7.7.0

### Node version

v16.17.1

### Package Manager

yarn

### Package Manager Version

v1.22.4

### Operating system

Linux

### Operating System Version

Docker: mlupin/docker-lambda:python3.9-build-x86_64

### Other

A direct download of the URL mentioned in the logs appears to work (using the same docker image, but on my laptop instead of in Gitlab CI). Docker image is based on [mlupin/docker-lambda](https://hub.docker.com/r/mlupin/docker-lambda):python3.9-build-x86_64

```
docker run --rm -it reg.example.com/my/ci:lambda-py3.9-node16 bash

bash-4.2# curl -L --output cypress.download  "https://download.cypress.io/desktop/7.7.0?platform=linux&arch=x64"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    80  100    80    0     0    306      0 --:--:-- --:--:-- --:--:--   306
100  197M  100  197M    0     0  2915k      0  0:01:09  0:01:09 --:--:-- 3144k
bash-4.2# 
```

**Comment by brettdh** [comment]
Also tested running the same Docker image and curl command on my Gitlab CI runner host (i.e. `docker run` command, outside Gitlab CI); succeeded.

Something weird is going on - it seems like something upstream (Cloudflare?) is rejecting only the requests that come from within my CI job within the CI context. And it only started failing today.

The workaround of setting `CYPRESS_INSTALL_BINARY=0` seems to work for now - though I'm not sure if the `yarn cypress install` in the later job that actually runs Cypress is going to fail (though it uses one of the `cypress/browsers` docker images).

**Comment by marktnoonan** [comment]
Thanks for reporting this @brettdh. I don't see any incidents recorded that would explain this, it might have been a very specific blip. 

> I'm not sure if the yarn cypress install in the later job that actually runs Cypress is going to fail (though it uses one of the cypress/browsers docker images).

How did this turn out, do you still experience the problem?

**Comment by brettdh** [comment]
I've now gotten a pipeline to run to the point where it successfully runs `yarn cypress install` and runs all of my specs, so I guess the issue is resolved? 😅

**Comment by marktnoonan** [comment]
I think that's probably the right move. This will still appear in search results if similar issues appear in the future and gives us an extra datapoint.
