### ISSUE TITLE
How to wait for component re-render on click()?

### ISSUE THREAD

**Issue by andrecasal** [cypress-io/cypress#26075]
### Current behavior

I think I have a race condition:
```ts
cy.findAllByLabelText('7 - 8').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('17 - 18').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('23 - 24').should('have.length', 7).click({ multiple: true }) // 👈 fires a React re-render on the whole <form>
cy.intercept('POST', '**/profile/scheduleinfo*').as('updateSchedule')
cy.findByText('Guardar').click() // 👈 doesn't fire a form submission because React will re-render
cy.wait('@updateSchedule') // 👈 test fails because this network request never happens
```

I'm wondering:
1. Should clicking on a form's checkbox re-render the whole `<form>`? I'm using [remix-validity-state](https://github.com/brophdawg11/remix-validity-state) and it may not be doing the right thing.
2. Either way, how can I ask Cypress to wait for the form's re-render without using cy.wait(some_time)?

### Desired behavior

Wait for the component to re-render.

### Test code to reproduce

On this React component in Remix:
```tsx
import type { InputDefinition } from 'remix-validity-state'
import { useValidatedInput } from 'remix-validity-state'

type formSchema = {
	inputs: {
		schedule: InputDefinition
	}
}

const formDefinition = {
	inputs: {
		schedule: {
			validationAttrs: {
				type: 'checkbox',
			},
		},
	},
} satisfies formSchema

export const ScheduleInfo = () => {
	const { getInputAttrs, getLabelAttrs } = useValidatedInput<typeof formDefinition>({ formDefinition, name: 'schedule' })

	// Since we'll share these attributes across all checkboxes we call these
	// once here to avoid calling per-input.  And since we put the input inside
	// the label we don't need the `for` attribute
	const labelAttrs = getLabelAttrs({ htmlFor: undefined })
	const inputAttrs = getInputAttrs()

	return (
		<form method="post">
			<input {...inputAttrs} />
			<button type="submit">Save</button>
		</form>
	)
}
```

Clicking the checkbox, re-renders the whole form. From my real component:
![Screenshot 2023-03-10 at 13 09 00](https://user-images.githubusercontent.com/22457463/224324217-03f669a0-d7c3-4dd2-9991-5877638bbd5b.png)

### Cypress Version

12.7.0

### Node version

v18.2.0

### Operating System

macOS Ventura 13.1

### Debug Logs

```shell
Error:    CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `updateSchedule`. No request ever occurred.
    at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:154814:18)
    at Object.errByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:154869:10)
    at checkForXhr (http://localhost:3000/__cypress/runner/cypress_runner.js:141777:92)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:141800:28)
From previous event:
    at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:146732:65)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:146173:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/spec.cy.ts:108:6)
```

**Comment by mike-plummer** [comment]
Hi @andrecasal , thanks for opening an issue and thanks for using Cypress! This one will be tricky to help you diagnose without being able to execute the code since so much is reliant on how your components are structured. Are you able to share this project? I'll do my best to address your questions given what you've shared so far:

1. **Should clicking on a form's checkbox re-render the whole form?**
Without seeing your code I can't say for certain but this sort of behavior is common with controlled form libraries, particularly with grouped checkboxes. I'm assuming each set of checkboxes shares the same name, so a change to one of them will trigger the whole group to revalidate and rerender. Normally it's not a huge issue unless you're doing extra processing or have a *lot* of form fields so most devs probably never worry about it, but it's not ideal. In any event, it's a behavior of the form library you're using and how you're using it.

2. **How can I ask Cypress to wait for the form's re-render?**
Cypress is built around interacting with your components the way a user would in real life, so this sort of question is typically answered by asking "how would a user know when the form was ready to submit"? There isn't a specific command or method of waiting for re-renders, it would rely on identifying a way to know when your component is in a settled state. React is designed to be able to rerender very very frequently, so if rerenders are causing issues it indicates you are likely doing some heavy processing in the wrong place or are failing to reflect a "long processing" state to the user via a wait spinner or other method.

To your specific issue, what exactly are you seeing in the Cypress Command Log? These are the first two troubleshooting steps I would take to start narrowing this down:

1. If you add a `cy.wait` before clicking the submit button to get past the form re-render/validation does the test succeed? That will help us verify you have the correct path on your `cy.intercept` command and help isolate the problem down a bit.
2. Is it possible the button *is* being clicked, but the form validation is preventing it from being submitted (bad intermediate state)? You may want to look at adding some logging to your validation or using the [`cy.submit`](https://docs.cypress.io/api/commands/submit) command which can sometimes give you additional insight into form validation. Are you reflecting the form's validation status by enabling/disabling the submit button?

**Comment by andrecasal** [comment]
Hey @mike-plummer thank you so much for your reply. I've figured out what the problem was: the server was taking a long time to send a response back and the cy.wait('@updateSchedule') was timing out.

I fixed it with `cy.wait('@updateSchedule', { timeout: 10000 })`.

However, what's confusing is that the error says `No request ever occurred`:
![Screenshot 2023-03-10 at 15 15 44](https://user-images.githubusercontent.com/22457463/224352883-7ca1f2ca-789d-4a95-b844-339461f04af1.png)

Shouldn't it say `request occurred but **response** never arrived`?

**Comment by mike-plummer** [comment]
@andrecasal Glad you found a fix! Your screenshot is interesting and makes me think you may still have some front-end behaviors to work out. I set up a quick reproduction case which submits a form with a server-side delay and got the correct message when the `cy.wait` times out on the `intercept` alias. Note that in my screenshot the command log shows the in-progress network call between the `click` and the test failure, but this is missing in your screenshot which tells me the call didn't happen that time or wasn't intercepted

![Image](https://user-images.githubusercontent.com/11482842/224359545-c2a7f3c8-fa8c-4765-b221-a561cadb72b2.png)

**Comment by andrecasal** [comment]
Yeah, that is indeed weird. What's the best way to proceed, should I create a repo with a reproduction or paste some code here?

**Comment by andrecasal** [comment]
Funny that `intercept()` only fails with the `click({multiple: true})` before it:

```ts
/* cy.findAllByLabelText('7 - 8').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('17 - 18').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('23 - 24').should('have.length', 7).click({ multiple: true }) */
cy.intercept('POST', '**/profile/scheduleinfo*').as('updateSchedule')
cy.findByText('Guardar').click()
cy.wait('@updateSchedule') // Success ✅
```

**Comment by andrecasal** [comment]
This works:

```ts
/* cy.findAllByLabelText('7 - 8').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('17 - 18').should('have.length', 7).click({ multiple: true })
cy.findAllByLabelText('23 - 24').should('have.length', 7).click({ multiple: true }) */
cy.findAllByLabelText('23 - 24').spread((first, second) => {
	first.click()
	second.click()
})
cy.intercept('POST', '**/profile/scheduleinfo*').as('updateSchedule')
cy.findByText('Guardar').click()
cy.wait('@updateSchedule')
```

I wonder why the `.click({ multiple: true })` makes the form submission fail 🤔

**Comment by mike-plummer** [comment]
@andrecasal If you're willing to create one, a repo with a reproduction is always the easiest for us to diagnose and help with.

Regarding the `.click({ multiple: true })` killing your test, there are a couple things that could be going on. This effectively does a Cypress `click` serially for each matching element, whereas the `.spread` gives you the raw jQuery wrapper for each element. This means the click isn't happening exactly the same way (doesn't wait for actionability, doesn't retry, doesn't show up in the command log, etc). Without being able to see the code and step through it I can't say for sure why the `multiple` approach isn't working. At a minimum you would need to do something like this to make sure all the same elements were being clicked by each approach:

```js
cy.findAllByLabelText('23 - 24').spread((...checkboxes) => {
  checkboxes.forEach((checkbox) => checkbox.click())
})
```

My best guess is that it's building form values that are considered invalid by your HTML form validation which would prevent the submit from actually happening - you could try setting [`novalidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#novalidate) on your form to see if that's the case.

**Comment by andrecasal** [comment]
I tried the noValidate and the test still fails with `.click({multiple: true})`.

I'll create a reproduction repo.

**Comment by andrecasal** [comment]
Just figured that if the checkboxes are `checked` on the test, it passes. If they are `unchecked` on the test, it fails.

**Comment by andrecasal** [comment]
Here's a [minimal reproduction](https://github.com/andrecasal/cypress-intercept-error).

**Comment by mike-plummer** [comment]
@andrecasal Thanks for the reproduction but it doesn't appear to demonstrate the issue you describe. I had to make a small tweak for it to be valid (the `cy.intercept` path in the spec doesn't match the route the form submits to), but once I renamed `_index.tsx` to `my-path.tsx` and updated the intercept path to `cy.intercept('POST', '**/my-path*').as('updateSchedule')` the test works perfectly with `cy.click({ multiple: true })`. I'm using the exact same OS and Node version as you, and I tried with multiple browsers, so I'm at a loss what else I might be missing. Can you verify the repro case is doing what you think it is?

**Comment by andrecasal** [comment]
@mike-plummer when I saw that error: "Aha! Reproduced it!" but seems like I jumped the gun on that one, thanks for catching and fixing the route mistake. Also seems like I can't create a reproduction short of recreating the same page. Would be giving you access to my repo an option or should update the public repo?

Once again, thank you so much for your help, I appreciate your support!

**Comment by mike-plummer** [comment]
@andrecasal Whichever approach you're most comfortable with is fine with me

**Comment by andrecasal** [comment]
I gave you access to the [repo](https://github.com/andrecasal/estuda-comigo.com) :)

**Comment by mike-plummer** [comment]
@andrecasal I pulled down your repo and took a look - I had to hack apart quite a bit of Prisma and environment variable setup to get things working so it's possible I changed something in the process. Assuming the "Edits a user schedule" test is the one you're having trouble with it appears to work perfectly on my system:

![Image](https://user-images.githubusercontent.com/11482842/224795382-552662db-8f74-430e-b0f8-9d61261a08fa.png)

I had to modify the Prisma setup to use a local sqlite instance (I don't have access to your Postgres instance and didn't want to install one), bypass db seeding, and also had to stub out the Email subscription API key and Session Secret values. Maybe one of those items is related to your test failure, but based on what you told me (test works doing individual clicks but fails when doing `click({ multiple: true })` I don't see how they could be related. The only issue I can think of is that the test runs slower against your Postgres DB which causes commands to time out, but I can't validate that and is easily worked around by customizing the command `timeout` value when submitting the form and waiting on the service call intercept.

**Comment by andrecasal** [comment]
Waw, you did a lot, thanks so much! I spent quite a bit of time trying to create a reproduction deleting code, but always got to a point where the problem disappeared, so I'm going to delete code slowly while having Cypress re-run the test and seeing where that change happens.

It's weird the app seems to hang while Cypress is listening for the fetch. As soon as Cypress times out, the fetch starts and returns quickly.

**Comment by andrecasal** [comment]
@mike-plummer I've created the `issue126` branch and cleaned it up:
- Clone, `npm i`, and `git checkout andrecasal/issue126`
- `npm run dev`
- `npm run cypress`

Notice the first test passes, but the second and onwards fail.


**Update**:  Going from `unchecked` -> `checked` succeeds and going from `checked` -> `unchecked` fails.

**Comment by mike-plummer** [comment]
> Notice the first test passes, but the second and onwards fail.

@andrecasal I only see one spec file and it contains a single test - did you forget to commit something, perhaps?

> Going from unchecked -> checked succeeds and going from checked -> unchecked fails.

The one test that is there appears to be going from `checked` -> `unchecked` and is passing on my system

**Comment by andrecasal** [comment]
@mike-plummer I removed all tests except the one that's failing from that branch.

Is it always passing or just on the first test run?

**Comment by andrecasal** [comment]
[Here's](https://youtu.be/-HaQh1NtECw) a video showing the test failing.

**Comment by mike-plummer** [comment]
@andrecasal Okay, I think we're getting somewhere now. That test does pass for me (5 runs in a row passed just fine), but there is a noticeable delay on the form submission where the browser has the request queued for several seconds before actually sending the network call. I imagine your computer is either less powerful than mine or is running extra stuff in the background, so a 3 second delay on my machine may be longer on yours and cause the command to time out.

The root cause appears to be a combination of using Tailwind and the complexity of your form in combination with how Cypress snapshots the DOM when running tests in `open` mode. Tailwind uses a custom SVG for the "checked" state of each checkbox. If you open your browser devtools during the test you can see *thousands* of dataURL requests coming through as each checkbox loads this image as a data URI. Even though it's an efficient data URI the browser still has to process it, and Cypress generates snapshots before & after each command (including each individual click) which multiplies the number of times it's being processed - 119 checkboxes * 21 before & after click events + other stuff in the test results in a lot of svgs. It's all local & in memory so there's no real bandwidth usage, but the sheer number seem to back up the network queue and delay your form submission. I'll need to put together a simpler reproduction to remove Remix and other stuff to validate my hypothesis, but all the pieces fit.

I can suggest a couple workarounds:

1. In my local testing, removing `@tailwindcss/forms` from `tailwind.config.js` seems to solve the problem. The test runs really fast and I don't see the extra dataURL requests. Obviously this isn't ideal since you want that styling, but just mentioning it as an option.
2. Reduce the complexity of the test (maybe just check/uncheck a couple boxes instead of full rows)
3. Add an extended timeout to your `cy.wait('@updateSchedule')` to give the browser time to catch up on the dataURL requests - not recommended, but it is *technically* an option
4. Add some logic to your test to remove the Tailwind SVG at runtime:
    ```js
    cy.findByTestId('schedule-form').within(() => {
      // Grab all checkboxes...
      cy.get('input[type="checkbox"]').each(($checkbox) => {
        //...override their `background-image` css prop so the SVG isn't used
        $checkbox.css('background-image', 'unset')
      })

      cy.get('label:contains("7 - 8")').click({ multiple: true })
      ...
    ```
5. Only run the test in `run` mode - we don't generate snapshots in run mode

Option 2 is probably the "right" approach since it doesn't rely on altering your UI during setup or runtime, but Option 4 might be a "good enough" if you need a complex test case.

**Comment by andrecasal** [comment]
Wow, I totally overlooked those network requests as I wrongly assumed that had to do with Cypress. I should have paid attention to the `Initiator` column in the DevTools.

Ok, I see, there are almost 9615 (cached) network requests for that SVG. This doesn't happen on the app itself, only when Cypress tests it. Am I right to assume the Cypress snapshots are forcing those SVG requests? If so, why is that the case?

**Comment by andrecasal** [comment]
I pushed a solution: I hid the `<input type="checkbox">`, and gave the labels a background color based on `checked`/`unchecked`, which is what we have on the design. This creates zero requests for that SVG.

We can go ahead and close this, thank you so much for your help @mike-plummer!

**Comment by mike-plummer** [comment]
No problem @andrecasal . I appreciate for your patience and putting together the repro - glad you found a solution that works for you.

Thanks for using Cypress!

**Comment by andrecasal** [comment]
@mike-plummer if you end up making a reproduction for this please let me know, I'm interesting in understanding why Cypress forces those network requests so I can avoid this class of problems in the future.

"Going from `unchecked` -> `checked` succeeds and going from `checked` -> `unchecked` fails." I've also realized it was not about **going** from `unchecked` to `checked`, but about the **number** of previously checked inputs.
