### ISSUE TITLE
Change of origin fails on all browsers except Firefox

### ISSUE THREAD

**Issue by aangelinsf** [cypress-io/cypress#26398]
### Current behavior

In the attached spec I'm registering at my site then attempting to log into https://ethereal.email to check for the registration email. The registration succeeds but logging into Ethereal fails with "Error invalid csrf token" at the Ethereal site using any browser other than Firefox.

### Desired behavior

Logging into Ethereal.email should succeed after the registration process on all browsers.

### Test code to reproduce

1. Using the attached script, rename .txt to .js.
2. Use a baseURL of https://test-hecho-en-todos-santos.pantheonsite.io
3. Create an account at Ethereal and change this line in the spec:
    const userEmail = 'adaline.littel54@ethereal.email'
4. Run the script with a browser other than Firefox.
5. You should see the error. But if you restart back at line 3 and use Firefox it will work.

[origin_test.cy.txt](https://github.com/cypress-io/cypress/files/11133410/origin_test.cy.txt)

[CypressOriginProblem.log.txt](https://github.com/cypress-io/cypress/files/11133438/CypressOriginProblem.log.txt)

### Cypress Version

12.9.0

### Node version

16.16.0

### Operating System

macOS 13.3.

### Debug Logs

```shell
Debug output included above.
```

**Comment by emilyrohrbough** [comment]
@aangelinsf I appreciate the reproduction and the debug logs. It is super helpful! Can you share the correct expected behavior?Since I am unfamiliar with the desired outcome, it's hard to use the debug logs to identify what went wrong. Screenshots/video snippets would be helpful.

**Comment by aangelinsf** [comment]
Hi, Emily. Thanks for looking into this.
The goal is to have a correct login that brings the user to the Ethereal dashboard rather than the login failing with the Error invalid csrf token message. I've attached two screenshots showing both outcomes plus the login screen.

Please let me know how else I can help.

![EtherealSuccess](https://user-images.githubusercontent.com/194045/229649059-d3595aa5-a1dc-4eff-b7eb-7351754f5b85.jpg)
![EtherealFailed](https://user-images.githubusercontent.com/194045/229649064-f0484bb8-d13e-4981-aa76-75e50b935a91.jpg)

![EtherealLogin](https://user-images.githubusercontent.com/194045/229649383-d732e48c-daa2-4e15-aba4-24f5a6826167.jpg)

**Comment by emilyrohrbough** [comment]
@aangelinsf Thanks for this info! I was finding the randomly generated password in the example you provided was causing auth errors in login which was why I wasn't sure what the expected behavior was. I also had to comment out the account creation to re-run this test with the hard-coded values.

When comparing the run in Firefox compared to Chrome, I am noticing the Session is not being created when visiting `https://ethereal.email/login`. I found this when comparing network logs for the login request triggered when clicking the login button.
| Firefox (see cookies sent on request) |Chrome (no cookies sent)
| -- | --|
| <img width="526" alt="Screen Shot 2023-04-05 at 2 22 37 PM" src="https://user-images.githubusercontent.com/14099737/230200063-0fbf1fc9-eb84-4af6-89a3-c8d08587e01a.png"> |  <img width="953" alt="Screen Shot 2023-04-05 at 2 23 27 PM" src="https://user-images.githubusercontent.com/14099737/230200071-97034c4e-e123-4469-ad66-2757e233a6d7.png"> | 
| <img width="738" alt="Screen Shot 2023-04-05 at 3 20 05 PM" src="https://user-images.githubusercontent.com/14099737/230201153-22c25a27-95c0-4733-a500-1cbf3066b46d.png">| <img width="740" alt="Screen Shot 2023-04-05 at 3 20 41 PM" src="https://user-images.githubusercontent.com/14099737/230201160-3fce244e-6503-4ba2-9d2e-55bd2aca4559.png"> 

You can easily confirm the existence with this test addition (generally prob not needed): 

```js
describe.only('User registration and login tasks', { baseUrl: 'https://test-hecho-en-todos-santos.pantheonsite.io' }, () => {
  Cypress.on('uncaught:exception', (err) => {
    if (err.message.includes('sitekey')) {
      return false
    }
  })

  it("(PER-0000) Origin test", () => {
    cy.visit("")

    cy.origin('https://ethereal.email', () => {
      cy.visit('https://ethereal.email/login', true).then( () => {
        const userEmail = 'aidan.cole84@ethereal.email'
        const userPassword = '4WTrxM2T9vnPtqKYTA'

        // verify Session cookies
        cy.getCookie('_csrf').should('exist')
        cy.getCookie('webmail').should('exist')

        cy.pause() // used to generate 2nd row of screenshots in table above

        cy.get('#address').type(userEmail)
        cy.get('#password').type(userPassword)
        cy.get('form > :nth-child(5) > .btn').click()
        cy.contains('Logged in as ' + userEmail)
      })
    })
  })
})
```

Can you take a look at your application to see what may cause the Session to fail to establish? Its curious its an issue with the Chromium browsers, but this would help narrow down why this is behaving different when running Cypress, but not in the browser.

**Comment by aangelinsf** [comment]
Hi, @emilyrohrbough.  Unfortunately, ethereal.email isn't my app. It's a third-party fake SMTP service that accepts email such as registration, forgotten passwords and others from one's app. Then one logs into the service to confirm one sees the email that's expected. 

My app is actually the one that was registering at the beginning of the spec. I included that in case it was somehow the move from my app (standard WordPress) to Ethereal that was the problem given how the new origin-switching works. It seems that even after removing the registration the login to Ethereal is failing in non-Firefox browsers.

I just tried logging into Ethereal with Chrome 111.0.5563.146 (Official Build) (arm64) and it worked. (Regular Firefox 111.0.1 works, too.)

So it seems to me that the breakdown is between Cypress in Chrome/Blink and Ethereal because desktop Chrome logs in with no issue.

**Comment by emilyrohrbough** [comment]
@aangelinsf Ah I see. Good call. I have simplified your example down even further to see if testing the Ethereal login flow is an issue in Cypress.

This login appears it works fine outside of `cy.origin()`
```js
  it("ethreal login without cy.origin", () => {
    cy.visit('https://ethereal.email/login', true).then( () => {
      const userEmail = 'aidan.cole84@ethereal.email'
      const userPassword = '4WTrxM2T9vnPtqKYTA'

      cy.getCookie('_csrf').should('exist')
      cy.getCookie('webmail').should('exist')
      
      cy.get('#address').type(userEmail)
      cy.get('#password').type(userPassword)
      
      cy.get('form > :nth-child(5) > .btn').click()
      cy.contains('Logged in as ' + userEmail)
    })
```
It seems like something is getting dropped / missing when using `cy.origin()` specifically with visiting Ethereal. I will flag as a bug and route to the team.

**Comment by stavares843** [comment]
still happens

**Comment by aangelinsf** [comment]
Yep, just confirmed last week as well.

**Comment by aangelinsf** [comment]
@emilyrohrbough any idea when this will get on the docket?
Cheers,
André

**Comment by stavares843** [comment]
i've noticed that this works if you use [synpress](https://github.com/Synthetixio/synpress) plugin in Cypress

**Comment by aangelinsf** [comment]
> i've noticed that this works if you use [synpress](https://github.com/Synthetixio/synpress) plugin in Cypress

Do you mean working with Ethereal.email? @stavares843

**Comment by stavares843** [comment]
yes

here's a video 🔨 

https://github.com/cypress-io/cypress/assets/29093946/a6ffc10a-da5e-4283-acc3-b76a0ff79381

**Comment by aangelinsf** [comment]
Thanks. That's creating an account but my code breaks on logging in. Does it work there, too?

**Comment by stavares843** [comment]
https://github.com/cypress-io/cypress/assets/29093946/878398b4-0153-4d7e-8166-fe71fb64ba44

it also works when logging in as well

**Comment by aangelinsf** [comment]
Thanks again.

@emilyrohrbough perhaps this provides clues as to why this bug is occuring.

**Comment by stavares843** [comment]
btw I tried again now without synpress and worked, maybe it got fixed in their latest updates, does it work for you as well?

**Comment by aangelinsf** [comment]
@stavares843 sorry I missed your comment. I just tried with 13.2.0 and it's still failing.

@emilyrohrbough can we get this on the radar of the devs?

**Comment by alfonsodev** [comment]
any solution for this ? @stavares843 do you mind sharing what version / code did you use to make it work ? 
thanks!

**Comment by hankszeto** [comment]
@alfonsodev @aangelinsf


The hint is in the warning provided by Chrome:


> This Set-Cookie header didn't specify a "SameSite" attribute and was defaulted to "SameSite=Lax," and was blocked because it came from a cross-site response which was not the response to a top-level navigation. The Set-Cookie had to have been set with "SameSite=None" to enable cross-site usage.


![image](https://github.com/cypress-io/cypress/assets/13651300/7a1113fd-e87a-42ca-be97-60df09130776)


It looks like the reason why this is happening is because:
-  the domain on the cookies (`ethereal.email`) differs from the address in the URL bar of the Cypress test runner (which is the address of my local DDEV instance, `https://myway-3.ddev.site:8443/`)
- the Set-Cookie response from https://ethereal.email/login does not specify SameSite attribute, so "SameSite=Lax," is assumed and is therefore blocked in Chrome-based browsers.

```
set-cookie: _csrf=Trbhry3d5QoKO5KN5o89CzzC; Path=/
 set-cookie: webmail=s%3AFqzO0KxPAF2M0UR5ctxc3W6wSdkZrBoD.7n7e8mQ1IcvK4KXi7dgd%2Buw9j3KYuPgvZLpaoCj6yn0; Path=/; HttpOnly
```
I got this working by intercepting the Set-Cookies header and enforcing `SameSite=None; Secure`.

Here is the code:

```js
    cy.intercept('*', (req) => {
      req.on('response', (res) => {
        const setCookies = res.headers['set-cookie'];

        if (setCookies) {
          res.headers['set-cookie'] = (
            Array.isArray(setCookies) ? setCookies : [setCookies]
          )
            .map((cookie) => {
              // Override or add SameSite=None
              if (cookie.includes('SameSite')) {
                cookie = cookie.replace(/SameSite=(Lax|Strict|None)/i, 'SameSite=None');
              } else {
                cookie = `${cookie}; SameSite=None`;
              }

              // Add Secure if not present
              if (!cookie.includes('Secure')) {
                cookie = `${cookie}; Secure`;
              }

              return cookie;
            });
        }
      });
    });

    cy.origin('https://ethereal.email', { args: sentArgs }, ({
      userEmail, userPassword, searchSubjectLine,
    }) => {
.
.
.
```

**Comment by aangelinsf** [comment]
Thanks for providing this, @hankszeto. I just pinged Cypress in Discord to bring it to their attention, the goal being to get a solution into the main Cypress build.

**Comment by johannreboulleau** [comment]
Hello @aangelinsf ,
We have the same issue with `cypress:15.7.1`. 
Any news about the fix ?

**Comment by aangelinsf** [comment]
@johannreboulleau unfortunately no. After pinging their community manager several times on Discord to bring it to their attention, they closed the other issue they had opened without resolving it so I gave up.
