### ISSUE TITLE
CT onboarding hangs waiting for dependency installation

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26685]
### Current behavior

When dependencies have been installed during CT onboarding, the Cypress App continues to wait showing a spinner with the text "Waiting for you to install the dependencies...". It does not exit this condition and requires the Cypress App to be restarted to continue. After restart, the Front-end framework is detected and onboarding continues successfully.

![image](https://user-images.githubusercontent.com/66998419/236694082-f3c8745f-9b1f-4017-a1c7-94e874685706.png)

### Desired behavior

Onboarding should automatically and dynamically check dependency installation as it did up until Cypress [12.7.0](https://docs.cypress.io/guides/references/changelog#12-7-0).

After choosing a front-end framework during CT onboarding, for instance `Next.js`, the Cypress App displays a command, such as `npm install -D next react react-dom`, together with a spinner with the text "Waiting for you to install the dependencies...".

Now if the command to install packages is executed in a separate terminal window, the spinner and text disappear. The message displaying the command to execute disappears and is replaced with a text saying "You've successfully installed all required dependencies"

![image](https://user-images.githubusercontent.com/66998419/236694271-1992e431-efec-4ccf-8baa-4bf61d5a34b7.png)

### Test code to reproduce

```bash
git init
npm init -y
npm install cypress -D -E
npx cypress open
```

Select Component Testing
Select Next.js, click Next step

In a separate terminal window copy and paste
`npm install -D next react react-dom`

The Cypress App waits showing a spinner with the text "Waiting for you to install the dependencies...". This does not change even when the dependencies have been installed.

### Cypress Version

`12.11.0` (and `12.12.0`)

### Node version

`18.16.0`

### Operating System

Ubuntu `22.04` (also reproducible on Windows `11`)

### Debug Logs

```shell
`cypress:scaffold-config:frameworks` is not detecting the dependencies
```

### Other

- This is possibly related to changes in Cypress [12.8.0](https://docs.cypress.io/guides/references/changelog#12-8-0) made for issue https://github.com/cypress-io/cypress/issues/25782.

### Workaround

Kill then restart the Cypress App after installing dev dependencies.

**Comment by marktnoonan** [comment]
Thanks for the report... could not reproduce on Mac, I will try windows next!

![Screenshot 2023-05-09 at 4 04 35 PM](https://github.com/cypress-io/cypress/assets/8340719/3c366211-c576-4d39-b386-e9f0105bb06e)

**Comment by MikeMcC399** [comment]
@marktnoonan 

Your screenshot in https://github.com/cypress-io/cypress/issues/26685#issuecomment-1540820630 shows Cypress `12.7.0`. You need to be using at least `12.8.0`, better still `12.11.0`.

**Comment by marktnoonan** [comment]
My bad @MikeMcC399 it caught my global Cypress install, confirmed. Thanks again, routing to the team.

![Screenshot 2023-05-09 at 4 29 54 PM](https://github.com/cypress-io/cypress/assets/8340719/bb9e5f9a-69f4-4c23-8232-549e92afbc0e)

**Comment by marktnoonan** [comment]
Confirmed it appears to have been introduced in 12.8.0.

**Comment by marktnoonan** [comment]
~~Possibly related: https://github.com/cypress-io/cypress/pull/26033, https://github.com/cypress-io/cypress/pull/26066 which introduced changes related to detecting dependencies.~~

Noticed that refreshing the page seems to work, so this is an issue related to state not syncing correctly with GQL, not the "detecting" logic itself. A similar issue was noticed before and addressed in https://github.com/cypress-io/cypress/pull/26437. I wonder if we need a similar Subscription added to https://github.com/cypress-io/cypress/blob/develop/packages/launchpad/src/setup/InstallDependencies.vue.

Loom showing the problem and how refreshing fixes it: 

https://www.loom.com/share/3da252d62a5c4a9fb794edd4fd9d8374

**Comment by lmiller1990** [comment]
I suspect

- https://github.com/cypress-io/cypress/commit/189cd923f75a2c37a1c1be1f52d4df8202fe1e6c
- https://github.com/cypress-io/cypress/commit/cacdb1d0c3a0b8362b476794c73b23c2e8f47d7d

I will take a closer look.

Ok, https://github.com/cypress-io/cypress/commit/189cd923f75a2c37a1c1be1f52d4df8202fe1e6c is the culprit. I will see why.

**Comment by lmiller1990** [comment]
I fixed it in https://github.com/cypress-io/cypress/pull/26726

> Noticed that refreshing the page seems to work, so this is an issue related to state not syncing correctly with GQL

I wasn't able to reproduce this - I refreshed the page, but the dependency was not updated. I found it was related to a caching issue. I wonder if there is another unrelated issue.

**Comment by MikeMcC399** [comment]
Confirmed still an issue with Cypress `12.12.0` (I didn't expect otherwise).

None of the following changed the condition:
- `F5`
- `Ctrl+F5`
- `Ctrl+R`

Looking forward now to seeing the rollout of 
-  #26726

**Comment by lmiller1990** [comment]
Yep, it'll be broken in 12.12.0 too - the fix will be in the next release, just need a few reviews on #26726 . This should be in 2 weeks, unless we do a patch release earlier.
