### ISSUE TITLE
Add support to cy.type() for inputs of type date, time, month, week

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#27]
When I use command `cy.type()` for inputs of type date, time, month, and week the value is not updated for the input. The type command needs to do special logic to inject the values (or do special click / selects / types) due to the formatting / dropdown nature of these inputs. 

**Date Example**

``` html
<input name="birthday" type="date">
```

``` coffee
cy.get("input[name='birthday']").type("11151985").should("have.value", "1985-11-15")
```

This example's assertion will fail and say `expected input to have value of '1985-11-15', but got ''`

**Time Example**

``` html
<input name="appt" type="time">
```

``` coffee
cy.get("input[name='appt']").type("1215am").should("have.value", "00:15:00")
```

This example's assertion will fail and say `expected input to have value of '00:15:00', but got ''`

**Month Example**

``` html
<input id="month" type="month">
```

``` coffee
cy.get("#month").type("February 2012").should("have.value", "February 2012")
```

This example's assertion will fail and say `expected '<input#month.form-control>' to have value 'February 2012', but the value was ''`

**Week Example**

``` html
<input id="week" type="week">
```

``` coffee
cy.get("#week").type("20, 2016").should("have.value", "February 2012")
```

This example's assertion will fail and say `expected '<input#week.form-control>' to have value '20, 2016', but the value was ''`

**Comment by brian-mann** [comment]
[This is a known problem](https://github.com/cypress-io/cypress/wiki/type#known-issues) and will be fixed in the next few patch releases.

**Comment by wavesoft** [comment]
I also have an issue with `.type` on `type=number` input. In my case including `.` to the expression does the same thing as `{selectall}`.

For example: `.type('0.2')` results in `2`

**Comment by ashercoren** [comment]
Please fix this...

**Comment by thomas-p-wilson** [comment]
Will also note that the docs at https://docs.cypress.io/v1.0/docs/type#section-known-issues seem to be inconsistent with the behaviour I'm seeing. The docs suggest that to enter a date I may simply write `cy.get('<element>').type('17/04/2017')`, wherein I am typing the fully-formatted value of the input. However, doing so yields the same result as @jennifer-shehane, namely `expected input to have value of '17-04-2017', but got ''`.

If the docs are in fact out of sync with the behaviour of Cypress currently, it might be a good idea to update the docs to reflect that. If the docs are suggesting this might be the expected fix, then it might also be good to note that as well.

Of course, it would also be good to just get the issue fixed as well. Seems to me that as I can enter dates/numbers/special fields by hand just by tabbing and typing, the same should be easily accomplished with Cypress. I might try mucking about with tabbing a bit to see if it works with these special cases at all.

**Comment by thomas-p-wilson** [comment]
Will also point out that it has been 13 months since @jennifer-shehane brought this issue to light. Has there been _any_ movement on this?

**Comment by brian-mann** [comment]
There has actually. In fact this will be fixed in the next release (0.20.0)

**Comment by thomas-p-wilson** [comment]
Very cool! Thanks for the update @brian-mann. I presume it will be fixed in accordance with what the docs already specify? Namely, it'll require entering the preformatted final value?

**Comment by brian-mann** [comment]
Correct. It will require entering the final value that will actually get set per the spec. We'll validate it up front and fire the keystrokes, but the value won't **appear** until its all done.

**Comment by thomas-p-wilson** [comment]
Very cool. Thanks for the update!

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)

**Comment by sharandaa** [comment]
I still have an issue with this. If I let the user type in a date in the preformatted final value, I still get this error when I use should(): expected '<tr#opening_date_level_1..opening_date_container>' to have value '01-12-2022', but the value was ''.

**Comment by carloscfcortez** [comment]
@sharandaa try to use that 

```
cy.get('get-your-input').invoke('removeAttr', 'type')type('2022-12-01{enter}').trigger('change');

cy.get('get-your-input').invoke('attr', 'value', '2022-12-01').trigger('change');

cy.get('get-your-input').invoke('attr', 'type', 'date');
```

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-05-19 14-09-04](https://github.com/cypress-io/cypress/assets/65593381/ca8ac60a-c424-44a8-983b-c70cca0cfa7c)
how to input date
