### ISSUE TITLE
Getting logged out automatically while executing BDD tests with latest version 13th and similar execution is working on 11th

### ISSUE THREAD

**Issue by KalpeshJadhav25** [cypress-io/cypress#27936]
### Current behavior

Getting logged out automatically while executing BDD tests with latest version 13th and similar execution is working on 11th.
Usually if we log in with any user and test our flow then it should allow us to test it completely, but currently its logging out the user in between.  

### Desired behavior

Getting logged out automatically while executing BDD tests with latest version 13th and similar execution is working on 11th.
Usually if we log in with any user and test our flow then it should allow us to test it completely, but currently its logging out the user in between.  

### Test code to reproduce

Test

### Cypress Version

13

### Node version

v20.3.0

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@KalpeshJadhav25 In v12 we implemented automatic clearing of sessions with `testIsolation`. That's the only thing I can think of that may be relevant to what you're describing. You can test this by setting `testIsolation: false` in your Cypress config and see if this test case works. Please read the [v12 changelog](https://docs.cypress.io/guides/references/changelog#12-0-0) and migration guide carefully. We recommend updating your tests to account for test isolation.

**Comment by KalpeshJadhav25** [comment]
Hi @jennifer-shehane I have tried to execute my scripts using this flag, But its still failing with the same reason. Please do let me know if any other solution is available.

**Comment by KalpeshJadhav25** [comment]
Hi @jennifer-shehane Do we have any other solution for this issue? Also In previous versions I have faced same issue with other URL's, but that time it worked with storing local storage in previous step and then was restoring it and that time issue was resolved. If similar approach is available in later 13 versions, Then please let me know.

**Comment by jennifer-shehane** [comment]
@KalpeshJadhav25 The changes made were intentional, so you'll need to update your tests accordingly.
