### ISSUE TITLE
numTestsKeptInMemory always set to 0 during cypress run even with --no-exit

### ISSUE THREAD

**Issue by aloifolia** [cypress-io/cypress#2961]
### Current behavior:

If i start my tests with `cypress run` instead of `cypress open` the tests are executed as expected. However, the time travel feature does not work when I want to debug the failed tests afterwards.

Whenever I click on of the lines in the left box, the according state is pinned and the console is cleared. But no log appears and the preview of my app does not change, at all.

### Desired behavior:

Time travel should work in `run` mode as it does in `open` mode.

### Steps to reproduce: (app code and test code)

Start cypress with

```
./node_modules/.bin/cypress run --spec 'path.to.your.spec.js' --headed --no-exit --browser chrome
```

### Versions

Cypress package version: 3.1.3
Cypress binary version: 3.1.3
MacOS 10.14
Chrome 71.0.3578.98

**Comment by jennifer-shehane** [comment]
Hey @aloifolia, I am seeing this behavior also. It seems we disable time travel when running tests through `cypress run`. I thought this may be easily fixed by passed `--config numTestsKeptInMemory=50`, assuming that this number was set to `0` during `cypress run`, but this made no difference to allowing time travel snapshots.

I think it is actually hard assigning the value to `0` even after we pass the configuration here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/config.coffee#L251

This should likely be updated to allow the default configuration value if `isTextTerminal` and `--no-exit`.

**Comment by kruno321** [comment]
@jennifer-shehane Whats is the status of this? Can we still not see snapshots using cypress run?

**Comment by aguingand** [comment]
Workaround for now
#### plugins/index.js
```js
module.exports = (on, config) => {
  return {
    ...config,
    // allow time travel in run mode
    isTextTerminal: false,
    numTestsKeptInMemory: 50,
  }
}
```
