### ISSUE TITLE
Return Promise issues

### ISSUE THREAD

**Issue by Shila7** [cypress-io/cypress#2979]
![promiseerror](https://user-images.githubusercontent.com/42570834/50336398-36f66100-0536-11e9-9256-2cb840e18717.png)
![promisecode](https://user-images.githubusercontent.com/42570834/50336401-38278e00-0536-11e9-8876-ec2399302035.png)
@jennifer-shehane  How can I solve this issues?

**Comment by danhaasalert** [comment]
I would like to add I am having similar, inconsistent, behaivor with this error. In my scenario, this error only occurs when running all the tests together, and so far has only occured when the previous test case results in an error that's being addressed in [this ](https://github.com/cypress-io/cypress/issues/761) thread. 

Current Behaivor:
Occasionally, when running all tests, I will get the following error
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

```
The command that returned the promise was:

  > cy.visit()

The cy command you invoked inside the promise was:

  > cy.viewport()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

https://on.cypress.io/returning-promise-and-commands-in-another-command

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Register an unregistered th...'
```

In my before hook for this test case, I have the following code.

```
  before(() => {
    cy.viewport('macbook-15');
    cy.visit(Routes().dashboardBaseUrl);
    cy.get('input[name=email]').type(Accounts().activeIncidentEmail);
    cy.get('input[name=password]')
      .type(Accounts().activeIncidentPw)
      .type('{enter}');
  });
```

I have not overwritten the visit nor viewport method anywhere in any test case. This never happens when running a single test case by itself, but happens somewhat infrequently when running all tests.

**Comment by Dan195** [comment]
I would like to add I am having similar, inconsistent, behaivor with this error. In my scenario, this error only occurs when running all the tests together, and so far has only occured when the previous test case results in an error that's being addressed in [this ](https://github.com/cypress-io/cypress/issues/761) thread. 

Current Behaivor:
Occasionally, when running all tests, I will get the following error
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

```
The command that returned the promise was:

  > cy.visit()

The cy command you invoked inside the promise was:

  > cy.viewport()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

https://on.cypress.io/returning-promise-and-commands-in-another-command

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Register an unregistered th...'
```

In my before hook for this test case, I have the following code.

```
  before(() => {
    cy.viewport('macbook-15');
    cy.visit(Routes().dashboardBaseUrl);
    cy.get('input[name=email]').type(Accounts().activeIncidentEmail);
    cy.get('input[name=password]')
      .type(Accounts().activeIncidentPw)
      .type('{enter}');
  });
```

I have not overwritten visit nor viewport anywhere in any test case. This never happens when running a single test case by itself, but happens somewhat infrequently when running all tests.

**Comment by jennifer-shehane** [comment]
@Dan195 Are you using any custom commands anywhere within your test suite?

**Comment by danhaasalert** [comment]
Yes I am. None should be overwriting original commands. Am I missing
unintended side effects by utilizing them?

**Comment by jennifer-shehane** [comment]
Could you provide the code within your custom commands?

**Comment by danhaasalert** [comment]
module.exports = (lat, lng) => {
cy.window().then(window => {
cy.checkCorrectMapCoords(window.map, lat, lng);
});

Cypress.Commands.add('checkCorrectMapCoords', (mapWindow, lat, lng) => {
const screenToGeo = mapWindow.screenToGeo(0, 0);

expect(screenToGeo.lat.toString().substring(0, 4)).to.be.within(
Number(lat) - 2,
Number(lat) + 2
);

expect(screenToGeo.lng.toString().substring(0, 4)).to.be.within(
Number(lng) - 2,
Number(lng) + 2
);
});
};

Cypress.Commands.add('getIncidentLocation', mapView => {
console.log(mapView);
const latLongIncidentBlackList = mapView.getObjects()[1].o;
//assert the correct location of the incident blacklist marker.
expect(latLongIncidentBlackList.lat).to.equal(42.956941);
expect(latLongIncidentBlackList.lng).to.equal(-85.665241);
//ensure no additional markers exist.
expect(mapView.getObjects().length).to.equal(2);
});

Cypress.Commands.add('heartbeatViewBoundsRemainConstant', mapView => {
const originalViewBounds = getMapCoords(mapView.getViewBounds());
signInApi(
Accounts().haasFireAndEmsClientId,
Accounts().haasFireAndEmsSuperAdminPw,
response => {
postHeartBeat(
Accounts().haasFireAndEmsOrgId,
Accounts().haasFireAndEmsClientId,
Things().haasFireAndEmsThingId,
response.body.authentication_token,
() => {
const updatedViewBounds = getMapCoords(mapView.getViewBounds());
console.log(originalViewBounds, updatedViewBounds);
expect(originalViewBounds[0][0]).to.equal(updatedViewBounds[0][0]);
expect(originalViewBounds[0][1]).to.equal(updatedViewBounds[0][1]);

expect(originalViewBounds[1][0]).to.equal(updatedViewBounds[1][0]);
expect(originalViewBounds[1][1]).to.equal(updatedViewBounds[1][1]);
}
);
}
);
});

**Comment by jennifer-shehane** [comment]
Yeah, I'm not seeing anything from the examples provided that could be causing the error you provided unfortunately. You'd likely have to simplify the code some to find the smallest reproducible example that causes the error.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by wataruoguchi** [comment]
I've got the same error.

```
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.click()

The cy command you invoked inside the promise was:

  > cy.wait()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
```

The part getting the error in the test look like:
```
cy.someCustomCommand(arg);
cy.get('.modal button.btn').click();
```

In the script in `support` is:
```
Cypress.Commands.add('someCustomCommand', function(arg) {
  cy.window().should( (win) => {
    var someObject = win.someWindowObject;
    expect(someObject).to.not.be.undefined;
  }).then(() => {
    cy.log("Arg: " + arg);
  });
}
```

We see this error sometimes but not always. I hope it's helpful for debugging the issue.

**Comment by jennifer-shehane** [comment]
@wataruoguchi There must be some information missing from what is provided above. The error indicates the `cy.click()` is invoked inside a `cy.wait()` - can you paste where the `cy.wait()` is defined?

**Comment by wataruoguchi** [comment]
@jennifer-shehane Oddly, I don't see any `cy.wait()` in the test code 🤔

**Comment by CJ-Lab7** [comment]
I've been seeing the same error.  It always happens on the same tests, but only when using the test runner (not headless mode).  Also these tests were passing a couple of weeks ago.  

Here's an example of the error:
<img width="309" alt="Screen Shot 2019-06-03 at 11 07 15 AM" src="https://user-images.githubusercontent.com/42812152/58816775-d3498700-85ef-11e9-87c4-fdc789e34318.png">

**Comment by jennifer-shehane** [comment]
@CJ-Lab7 This error looks to be coming from your own application code. In the error, you can see it is coming from (http://127.0.0.1:32792/js/lims.50c0b27d.js:1) - this is your application's file. Click on the error with DevTools open to see more information about the error.

**Comment by elm9** [comment]
I just merged some unrelated changes into a new test branch, ran npm i, and the `cy.visit()` function began throwing this error. I find it odd because I haven't done anything regarding the visit command that is built into cypress. I even looked in the cypress repo to make sure there isn't a wait function inside . Is anyone else having this issue?

![Screen Shot 2019-06-18 at 12 29 11 PM](https://user-images.githubusercontent.com/42154853/59701976-b6eb4400-91c4-11e9-8c81-f2556c86ce0e.png)

Here is the piece of code that is throwing this error:
![Screen Shot 2019-06-18 at 12 39 30 PM](https://user-images.githubusercontent.com/42154853/59702645-2a418580-91c6-11e9-859d-1b804608308a.png)

**Comment by jennifer-shehane** [comment]
Unfortunately there is still not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by TimChebotarev** [comment]
I got the same error on the first type() command

```
describe('C T', () => {
  before(() => {
    cy.on('uncaught:exception', (err, runnable) => {
      if (err.match(/Uncaught Error: ResizeObserver loop limit exceeded/))
        return false
    })
  })
  beforeEach(() => {
    cy.server()
    cy.fixture('c/all.json').as('fxAllC')
    cy.route('**/T**').as('data')
    cy.route('GET',
      '**/C/T?dateFrom=**',
      '@fxAllC').as('fullData')

    cy.route('POST', '**/Search').as('search')

    cy.login()
    cy.visit('/c')
    cy.wait('@fullData', { timeout: 20000, })
  })
  it('Text search', () => {
    cy.contains('h1', 'Count')

    cy.get('.ct-search .aff input').type('leader')
    cy.wait('@search')
    cy.get('.aff-item').first().click()

    cy.get('.ct-search .aff input').type('11111111111111')
    cy.wait('@search')
    cy.get('.aff-item').should('not.exist')

    cy.get('.ct-search .aff input').type('{enter}')

    cy.get('.aff .aff-selected-item').should((items) => {
      expect(items).to.have.length(2)
      expect(items.eq(1)).to.contain('Leader 1')
      expect(items.eq(0)).to.contain('11111111111111')
    })
  })
})
```
![image](https://user-images.githubusercontent.com/11838916/60610601-d3929900-9dcc-11e9-81fd-879d3df036e1.png)

Also I have commands
```
Cypress.Commands.add('app', () => {
  cy.window().should('have.property', '$app')
  return cy.window().its('$app')
})

Cypress.Commands.add('login', () => {
  return api.login('User', '123456')
})
```

**Comment by oskargustafsson** [comment]
I see a similar issue, which occurs randomly when running a certain test:

```js
// all(...) creates it(...) permutations with different viewports and languages
all( 
  `${testProduct.name} can be found through navigation, sorting and filtering`,
  topCategoryPageUrl,
  ({ viewport, t }) => {
    assertBreadcrumbs(2, viewport);

    cy.get(`header h1`).should('exist');
		
    // Navigate to sub-category
    cy.get(el('CategoryList'))
      .find(
        `${el('CategoryListItem')} a[href$="${
          testProduct.subCategory
        }"]:visible`
      )
      .click();

    cy.location('href').should('include', testProduct.subCategory);

    cy.get(el('ProductListing', 'category', testProduct.subCategory)).as(
      'productList'
    );

    if (viewport !== 'mobile') {
      cy.get('@productList')
        .find(el('PanelHeader'))
        .contains(t('category', 'products.title'));
    }

    cy.get('@productList')
      .get(el('ProductCard'))
      .its('length')
      .should('be.gte', 2);

    // Sorting
    cy.get(el('SortOrderDropdown')).click();

    cy.get(
      `${el('SortOrderDropdown')} ${el('DropdownOption', 'value', 'price:asc')}`
    ).click();

    assertRouteLoad();

    const productPricesSelector = `${el(
      'ProductListing',
      'category',
      testProduct.subCategory
    )} ${el('ProductCard')} ${el('PriceLabel')}`;

    assertSorted({
      selector: productPricesSelector,
      parser: val => currency(val).value,
    });

    cy.get(el('SortOrderDropdown')).click();

    cy.get(
      `${el('SortOrderDropdown')} ${el(
        'DropdownOption',
        'value',
        'price:desc'
      )}`
    ).click();

    assertRouteLoad();

    assertSorted({
      selector: productPricesSelector,
      parser: val => currency(val).value,
      comparator: (a, b) => b - a,
    });

    // ... more test code
  }
);

// Some helper functions used in the above test code

export function assertRouteLoad() {
  cy.get(el('RouteLoader'), {
    timeout: Cypress.config('pageLoadTimeout'),
  }).should('exist');
  cy.get(el('RouteLoader'), {
    timeout: Cypress.config('pageLoadTimeout'),
  }).should('not.exist');
}

export function assertSorted({
  selector,
  timeout = Cypress.config('pageLoadTimeout'),
  parser = val => val,
  comparator = (a, b) => a - b,
}) {
  const startTime = Date.now();
  return new Cypress.Promise((resolve, reject) => {
    (function poll() {
      cy.get(selector).then(elements => {
        const values = elements
          .toArray()
          .map(element => parser(element.innerText));

        const sortedValues = values.slice().sort(comparator);
        const isSorted = equal(values, sortedValues);

        if (isSorted) {
          expect(values).to.eql(sortedValues);
          resolve(values);
          return;
        }

        if (startTime + timeout < Date.now()) {
          expect(values).to.eql(sortedValues);
          reject();
          return;
        }

        setTimeout(poll, 500);
      });
    })();
  });
}

// el(...) is a helper function that generates selector strings
```
This is the error:
![failing test](https://user-images.githubusercontent.com/4759832/60756941-40dc3f00-a004-11e9-81ae-e37a835f75fd.png)

As can be seen in the test code, `cy.get()` is never executed inside a `cy.click()` promise, which makes the error message kind of odd.

**Comment by zkilleb** [comment]
I am also experiencing this issue with cy.type() and cy.clear(). I only saw this issue when upgrading from 3.1.5 to 3.4.1.

**Comment by DamienCassou** [comment]
Do you use the `cypress-watch-and-reload` plugin? Can you reproduce without it?

**Comment by prostko** [comment]
Why did this issue get closed? There does not seem to be a resolution

**Comment by GeeWee** [comment]
I got a similar nonsensical error that led me to this issue.
![image](https://github.com/user-attachments/assets/46291028-9995-4630-a5a8-7ab1072e3927)

It seems to be because I had a "naked" await call not wrapped in `cy.then` or similar in my `beforeEach` function (that I had marked as async), and apparently that creates an error in a completely different location.
