### ISSUE TITLE
Cypress Login to Microsoft Dynamics Fails Due to Third-Party Cookie Restrictions

### ISSUE THREAD

**Issue by TuranKh** [cypress-io/cypress#31125]
### Current behavior

We are using Cypress (v13.12.0) for E2E testing of our web application and have successfully automated testing on our web page. We have part of our application functionality delivered by Microsoft Dynamics (under cmmetest.crm4.dynamics.com domain)

Flow Description: 
- The user signs in to Microsoft Dynamics.
- The user performs actions within Dynamics.
- The results are verified both on our web page and the Dynamics Dashboard.

The problem occurs after Cypress programmatically signs in to Microsoft Dynamics.

### Issue Analysis

- The issue seems related to third-party cookie restrictions on Microsoft Dynamics login.
- The problem also occurs in Chrome Incognito mode.
- Manually accepting cookies as suggested in this [Microsoft support](https://learn.microsoft.com/en-us/answers/questions/1071292/sign-in-to-continue-some-components-of-this-app-re) article resolves the issue in a regular browser.
- However, even with "Allow third-party cookies" enabled, the problem persists in Cypress's browser emulator and headless mode.

### Screenshot

<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/9e6c93ac-b508-4f75-928d-2515ebe63517" />

### Desired behavior

Proceed with fully working CRM

### Failing test:
```js
it('Microsoft login', () => {
        cy.session("azureAdSession", () => {
            const username = Cypress.env('aad_username');
            const password = Cypress.env('aad_password');

            cy.setCustomCookie('X-VERSIONS');
            cy.visit(`${BASE_URL}/hub/hbs-checkout`);

            cy.get('a').contains('Go to CRM').click();

            cy.origin(
                'login.microsoftonline.com',
                {
                    args: {
                        username,
                        password
                    }
                },
                ({ username, password }) => {
                    cy.get('input[type="email"]').type(username, {
                        log: false
                    });
                    cy.get('input[type="submit"]').click();

                    cy.get('input[type="password"]').type(password, {
                        log: false
                    });
                    cy.get('input[type="submit"]').click();
                    cy.get('#idSubmit_ProofUp_Redirect').click();
                }
            );

            cy.origin(
                'mysignins.microsoft.com',
                {
                    args: {
                        password
                    }
                },
                () => {
                    cy.get('button').contains('Skip setup').click();
                }
            );

            cy.origin(
                'login.microsoftonline.com',
                {
                    args: {
                        username,
                        password
                    }
                },
                ({ username, password }) => {
                    cy.get('#idSIButton9').click();
                }
            );

            cy.origin(
                'cmmetest.crm4.dynamics.com',
                {
                    args: {
                        username
                    }
                },
                () => {
                    cy.log('successfully logged in to CRM');
                    cy.wait(10_0000)
                }
            );
        })
    });
```

### Existing (simplified) config:
```js
module.exports = defineConfig({
  e2e: {
    // chromeWebSecurity: false,
    experimentalModifyObstructiveThirdPartyCode: true
  }
});
```

### Cypress Version

13.12.0

### Node version

20.16.0

### Operating System

macos 14.6.1

### Debug Logs

```shell

```

### Other

https://github.com/user-attachments/assets/daa93cc7-8ec2-45c2-b82c-9242fa1ef2df

**Comment by jennifer-shehane** [comment]
@TuranKh Could you try the tests on our latest Cypress version? 14.0.3? We fixed some issues around cross origin URLs and cookies in 14+ and I'd like to verify that this is not already fixed before investigating.

**Comment by TuranKh** [comment]
Hey, @jennifer-shehane  thanks for reaching me, I upgraded to the latest version: 14.0.3, the issue is still there
