### ISSUE TITLE
Entire test runner redirects to app's login page

### ISSUE THREAD

**Issue by powderham** [cypress-io/cypress#3517]
### Current behavior:

In our app when running tests, the test runner itself redirects to our login page, as per the below GIF.

![escaping-iframe](https://user-images.githubusercontent.com/18611511/52947488-26683880-3377-11e9-9374-a5698874ce60.gif)

### Desired behavior:

Redirects only happen within the ifrrame, not the entire test runner.

Note: I cannot reproduce this bug in a sterile environment, but was wondering if anyone has come across it before

**Comment by ryanlangton** [comment]
Having the same problem. I'm unable to run any of our e2e specs anymore due to this problem.
https://stackoverflow.com/questions/54750440/cypress-e2e-test-dock-closing-on-cy-visit

**Comment by powderham** [comment]
@ryanlangton i've upvoted your s.o. question for visibility

**Comment by jennifer-shehane** [comment]
This behavior usually happens when the application under test has some code to prevent framebusting. Cypress tries to work around this situation by replacing common code used to prevent framebusting - see https://on.cypress.io/configuration#modifyObstructiveCode

See if your application implements anything similar to [common framebusting patterns](https://github.com/cypress-io/cypress/issues/886#issuecomment-364779884) and let us know what this code is so we can extend Cypress to handle this situation. 

Otherwise, we'll need a url to visit ourselves to investigate.

**Comment by powderham** [comment]
I managed to fix it by updating Cypress 3.1.4 -> 3.1.5, which seems strange that it should fix it if it was indeed a framework issue.

For anyone who finds this in the future, I was using Meteor@1.8. I couldn't find any specific reference to framebusting code. My colleague running Linux didn't have this issue.

**Comment by ryanlangton** [comment]
Hmm this is not fixed for me and I am on 3.1.5. I will investigate for framebusting code

**Comment by ryanlangton** [comment]
This was happening for us because we were importing `hammerjs`. Once I removed that import it works fine.

**Comment by gvdp** [comment]
> Thanks for the help @jennifer-shehane
> 
> I managed to fix it by updating Cypress 3.1.4 -> 3.1.5, which seems strange that it should fix it if it was indeed a framework issue.
> 
> For anyone who finds this in the future, I was using Meteor@1.8. I couldn't find any specific reference to framebusting code. My colleague running Linux didn't have this issue.

Updating to 3.1.5 also worked for me. I don't think I was using any specific 'framebusting' code. Just a simple vue js app with Vuex.

**Comment by roc** [comment]
Following @jennifer-shehane's comment, we found our "don't make me think more about this" fix using the `experimentalModifyObstructiveThirdPartyCode` option in `cypress.config.js` when we were testing a stripe payment flow:

```
module.exports = defineConfig({
  e2e: {
    experimentalModifyObstructiveThirdPartyCode: true,
...
```

Docs here:
https://docs.cypress.io/guides/guides/web-security#Modifying-Obstructive-Third-Party-Code

> Updates the Sec-Fetch-Dest Metadata header from iframe to document in cases where requests come from the application under test.
