### ISSUE TITLE
Visibility assertion passes in situation where element is NOT visible. 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#410]
I've created a repo with the failing Cypress test that demonstrates the issue here: [overflow-visibility-issue](https://github.com/jennifer-mann/overflow-visibility-issue)

To summarize, I wanted to write a test to ensure that an element was visible in my app. My element was currently hidden, yet the test kept passing saying it was visible. The element was `position: absolute` with `top: -100px` and `left: -100px` so that it sat outside of it's container, and the container was `overflow: hidden` to not allow it to be seen.

```javascript
cy.get('.element').should('be.visible') // this incorrectly passes
cy.get('.element').click() //this correctly fails because the element is not visible.
```

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)

**Comment by Saibamen** [comment]
@brian-mann not fixed. See https://github.com/cypress-io/cypress/issues/3078
