### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by cdaguerre** [cypress-io/cypress#419]
I don't know if this is even possible but I was wondering if there are any plans to support Alpine Linux.

I don't know if it's helpful but here's an `ldd` on the `Cypress` executable from within Alpine:
```sh
root@6b425a4f775a[~/.cypress/Cypress] $ ldd ./Cypress 
	/lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	libnode.so => ./libnode.so (0x7f37b4b22000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x7f37b4557000)
	libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x7f37b42b5000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x7f37b4092000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x7f37b3d29000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x7f37b3b1d000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x7f37b3900000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x7f37b361b000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x7f37b33d8000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f37b3133000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f37b2ef7000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x7f37b2cb7000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x7f37b2a71000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x7f37b2862000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x7f37b2658000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x7f37b2455000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x7f37b224b000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x7f37b2048000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x7f37b1e38000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x7f37b1c32000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x7f37b1a28000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x7f37b1705000)
	libXtst.so.6 => /usr/lib/libXtst.so.6 (0x7f37b14ff000)
	libXss.so.1 => /usr/lib/libXss.so.1 (0x7f37b12fc000)
	libgconf-2.so.4 => /usr/lib/libgconf-2.so.4 (0x7f37b10c4000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x7f37b0ec0000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7f37b0bd1000)
	libnss3.so => /usr/lib/libnss3.so (0x7f37b08a8000)
	libnssutil3.so => /usr/lib/libnssutil3.so (0x7f37b067a000)
	libsmime3.so => /usr/lib/libsmime3.so (0x7f37b0453000)
	libnspr4.so => /usr/lib/libnspr4.so (0x7f37b0214000)
	libffmpeg.so => ./libffmpeg.so (0x7f37afe3d000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x7f37afb4b000)
	libcups.so.2 => /usr/lib/libcups.so.2 (0x7f37af8d3000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f37af6b3000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f37af362000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f37af150000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5603ddf7c000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f37aeec3000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x7f37aecaf000)
	libintl.so.8 => /usr/lib/libintl.so.8 (0x7f37aeaa1000)
	libz.so.1 => /lib/libz.so.1 (0x7f37ae88b000)
	libmount.so.1 => /lib/libmount.so.1 (0x7f37ae64a000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x7f37ae3ba000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f37ae18d000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x7f37adf89000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f37add63000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x7f37adb55000)
	libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f37ad948000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x7f37ad740000)
	libORBit-2.so.0 => /usr/lib/libORBit-2.so.0 (0x7f37ad4d9000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7f37ad27d000)
	libplc4.so => /usr/lib/libplc4.so (0x7f37ad078000)
	libplds4.so => /usr/lib/libplds4.so (0x7f37ace74000)
	libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x7f37acb60000)
	libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x7f37ac954000)
	libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x7f37ac745000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x7f37ac4f7000)
	libblkid.so.1 => /lib/libblkid.so.1 (0x7f37ac2bc000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x7f37ac0b9000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f37abeb3000)
	libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x7f37abc57000)
	libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x7f37aba47000)
	libnettle.so.6 => /usr/lib/libnettle.so.6 (0x7f37ab813000)
	libhogweed.so.4 => /usr/lib/libhogweed.so.4 (0x7f37ab5e0000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f37ab37c000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x7f37ab15c000)
	libuuid.so.1 => /lib/libuuid.so.1 (0x7f37aaf58000)
Error relocating ./libnode.so: __isinf: symbol not found
Error relocating ./libnode.so: __rawmemchr: symbol not found
Error relocating ./libnode.so: __isnan: symbol not found
Error relocating ./libnode.so: backtrace: symbol not found
Error relocating ./libffmpeg.so: __isnan: symbol not found
Error relocating ./libffmpeg.so: __isinf: symbol not found
Error relocating ./Cypress: __sbrk: symbol not found
Error relocating ./Cypress: __isnan: symbol not found
Error relocating ./Cypress: __res_ninit: symbol not found
Error relocating ./Cypress: __finite: symbol not found
Error relocating ./Cypress: backtrace: symbol not found
Error relocating ./Cypress: __isinf: symbol not found
Error relocating ./Cypress: backtrace_symbols: symbol not found
Error relocating ./Cypress: getcontext: symbol not found
Error relocating ./Cypress: __res_nclose: symbol not found
Error relocating ./Cypress: __cmsg_nxthdr: symbol not found
Error relocating ./Cypress: __libc_stack_end: symbol not found
```

**Comment by wavesoft** [comment]
Yeah, it looks like `Cypress` needs to be built against `musl` libc instead of `glibc`. I guess we would need to wait for a new build.

**Comment by brian-mann** [comment]
This likely has to do with `electron` and not necessarily Cypress. 

It may be easier opening an issue over there https://github.com/electron/electron/issues and ask about what it will take to build `Chromium` against Alpine.

It may already be possible, so any direction here would be helpful and we can look at adding a new dist when we release.

**Comment by jwalton** [comment]
This is a year old.  -_-

**Comment by tomatau** [comment]
Also would like this

**Comment by bahmutov** [comment]
I spent some time looking into this yesterday, and could not get all the required libraries work on Alpine. If anyone can actually build Electron on Alpine Linux, then we could potentially setup a CI chain that builds Alpine-specific Cypress version, but I expect the demand to be pretty low

**Comment by bahmutov** [comment]
I am going to close this for now, because Electron itself has their Alpine Linux build issue open https://github.com/electron/electron/issues/2727 (opened in 2015). If that issue is resolved successfully, we can revisit Alpine Linux support.

**Comment by simondiep** [comment]
It appears that Electron 3 no longer depends on gconf.  Could this issue be reopened?

**Comment by rohmanhm** [comment]
It's been two years.
Any way to support cypress work with alpine linux?

**Comment by jennifer-shehane** [comment]
This issue will be covered as part of our [4.0 release](https://github.com/cypress-io/cypress/issues/2840) - which [includes upgrading Electron](https://github.com/cypress-io/cypress/issues/2559).

**Comment by dsebastien** [comment]
Hello,

Any news about this issue?
I've just started setting up my CI/CD pipeline and since we're using node:alpine for our Dockerfile, I'm also using it for Gitlab CI, which has led me right here ;-)

**Comment by 502647092** [comment]
> Hello,
> 
> Any news about this issue?
> I've just started setting up my CI/CD pipeline and since we're using node:alpine for our Dockerfile, I'm also using it for Gitlab CI, which has led me right here ;-)

maybe you can try frolvlad/alpine-glibc image

**Comment by basickarl** [comment]
@dsebastien A lot of us are waiting for this still. As a workaround I only run tests using cypress in the cypress node image and everything else in alpine images. Then I'll just swap them out afterwards.

**Comment by kwuite** [comment]
Hi guys, I tried installing cypress via npm on alpine linux and ended up with:

![image](https://user-images.githubusercontent.com/6716689/68129554-0df67900-ff1a-11e9-91ea-dca77ecb44cb.png)

I got the [/usr/lib/libasound.so.2](https://pkgs.alpinelinux.org/package/edge/main/x86_64/alsa-lib) from:
- RUN apk add --no-cache alsa-lib

My first run was with alpine:3.10 but that did not get me anywhere. So I used this image: [frolvlad/alpine-glibc:alpine-3.9_glibc-2.29](https://hub.docker.com/r/frolvlad/alpine-glibc/)

Would it be an option to clone the git repo and just completely build Cypress against musl or is the problem with my libasound 2 library?

**Comment by kwuite** [comment]
Tried building on alpine linux and can confirm that my main problem is this error: 

`/usr/lib/libasound.so.2: no version information available (required by /home/root/cypress/build/linux/Cypress/Cypress)`

![image](https://user-images.githubusercontent.com/6716689/68133882-81e84f80-ff21-11e9-91ff-8cfa9fd171ba.png)

[StackOverflow answer](https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker)

Quote: Chris => `The "no version information available" means that the library version number is lower on the shared object. For example, if your major.minor.patch number is 7.15.5 on the machine where you build the binary, and the major.minor.patch number is 7.12.1 on the installation machine, ld will print the warning.`

Anybody got an idea to resolve this issue?

**Comment by kwuite** [comment]
UPDATE: 

I manually build alsa-lib to fix the version error with shared library /usr/lib/libasound.so.2 . Building without the `--without-versioned` solved the problem.

Unfortunately the following error still appears and make the build fail: ```Relink `/usr/lib/libgmp.so.10' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memset'```

![image](https://user-images.githubusercontent.com/6716689/68151511-267a8980-ff42-11e9-9d65-67752dbac9fe.png)

**Comment by ffxluca** [comment]
Installing the`alsa-lib` package (alpine 3.10) I didn't have any ALSA issue

**Comment by ffxluca** [comment]
I have installed the following packages using apk:
* chromium
* xvfb
* gtk+3.0-dev
* libnotify
* gconf
* nss
* libxscrnsaver
* alsa-lib
* xkbcomp
* `glibc-2.30-r0.apk`  (downloaded from sgerrand/alpine-pkg-glibc)


ℹ️Command `cypress verify` fail when it comes to load libgobject-2.0.so.0

ℹ️Other _mislinked_ libraries (found with ldd)
* `__isnan`: symbol not found
* `__isinf`: symbol not found
* `strtoll_l`: symbol not found
* `strtoull_l`: symbol not found
* `__sbrk`: symbol not found
* `__res_nclose`: symbol not found
* `__res_ninit`: symbol not found
* `__vsnprintf_chk`: symbol not found
* `__isnanf`: symbol not found
* `__isnan`: symbol not found
* `__isinf`: symbol not found
* `__longjmp_chk`: symbol not found
* `strtoll_l`: symbol not found
* `strtoull_l`: symbol not found
* `__fdelt_chk`: symbol not found
* `backtrace`: symbol not found
* `__strncat_chk`: symbol not found
* `__fprintf_chk`: symbol not found
* `__sprintf_chk`: symbol not found
* `initstate_r`: symbol not found
* `random_r`: symbol not found
* `__strcat_chk`: symbol not found
* `__isinff`: symbol not found
* `__vfprintf_chk`: symbol not found
* `__snprintf_chk`: symbol not found
* `gnu_get_libc_version`: symbol not found
* `__register_atfork`: symbol not found
* `__longjmp_chk`: symbol not found


This is as far as I could get with Alpine 3.10 and Cypress (base image being `php:7.3.8-fpm-alpine3.10` )

**Comment by Prabhakar-17** [comment]
> Hello,
> 
> Any news about this issue?
> I've just started setting up my CI/CD pipeline and since we're using node:alpine for our Dockerfile, I'm also using it for Gitlab CI, which has led me right here ;-)

Xvfb package enables you to run graphical applications without a display (e.g., browser tests on a CI server) so cypress needs xvfb package to be installed.

It is not going to work on node:alpine image as the xvfb package is not present.

Running on [markadams/chromium-xvfb-js](https://hub.docker.com/r/markadams/chromium-xvfb-js) docker image fixed the issue for me.

**Comment by eylonmalin** [comment]
> > Hello,
> > Any news about this issue?
> > I've just started setting up my CI/CD pipeline and since we're using node:alpine for our Dockerfile, I'm also using it for Gitlab CI, which has led me right here ;-)
> 
> Xvfb package enables you to run graphical applications without a display (e.g., browser tests on a CI server) so cypress needs xvfb package to be installed.
> 
> It is not going to work on node:alpine image as the xvfb package is not present.
> 
> Running on [markadams/chromium-xvfb-js](https://hub.docker.com/r/markadams/chromium-xvfb-js) docker image fixed the issue for me.

@Prabhakar-17 [markadams/chromium-xvfb-js](https://hub.docker.com/r/markadams/chromium-xvfb-js) is not based on alpine

**Comment by kwuite** [comment]
@ffxluca 

> Installing the`alsa-lib` package (alpine 3.10) I didn't have any ALSA issue

I never said I had an issue installing the library on alpine. It is the libasound driver that is packaged in alsa-lib that gave me the error about versioning. Which in return was solved by packaging it myself.

> This is as far as I could get with Alpine 3.10 and Cypress (base image being php:7.3.8-fpm-alpine3.10 )

As you can see in my post I am compiling Cypress with glibc. Not pulling it from some php based base image.

**Comment by jennifer-shehane** [comment]
Is this resolved? Previously it was believed that the issue was dependent on an Electron upgrade. We've upgraded Electron close to its most recent version now. Can anywhere verify?

**Comment by flotwig** [comment]
This issue still seems to exist even after [Electron 9.0.5](https://github.com/cypress-io/cypress/pull/7791).

**Comment by PlantDaddy** [comment]
Yeah I recently tried to get cypress running on alpine 3.12, with no luck. I was able to get all dependencies with the exception of gconf, which electron still seems to rely on

**Comment by x-yuri** [comment]
> Is this resolved? Previously it was believed that the issue was dependent on an Electron upgrade. We've upgraded Electron close to its most recent version now. Can anywhere verify?

@jennifer-shehane Actually I'm not sure where the idea came from that it has something to do with `gconf`. In the original post I see no:

> Error loading shared library libgconf-2.so.4: No such file or directory (needed by /root/.cache/Cypress/3.4.1/Cypress/Cypress)

What I see is:

https://gist.github.com/x-yuri/c96dd195e8293f292de824aba203ab3e

which supposedly means that Electron was built against `glibc`, and that is the reason it doesn't start.

I understand Cypress comes with a custom version of Electron? Why? How can I build one?

**Comment by flotwig** [comment]
> I understand Cypress comes with a custom version of Electron? Why? How can I build one?

@x-yuri Cypress uses the Electron binaries that get installed with `electron` from the NPM registry. You can actually reproduce this issue using the Electron binaries directly, without Cypress, see my comment: https://github.com/cypress-io/cypress/issues/419#issuecomment-642017901 It seems to be a generic issue with running Electron in Alpine.

**Comment by x-yuri** [comment]
Indeed, the issue can be reproduced w/o `cypress`. And they don't seem to want to support it:

> In order for this to happen someone would need to confirm that Chromium, Node, et al will run correctly on it and to add support for it in all the affected build scripts, so I don't think it's likely this will be on the project's supported roadmap.

> However MUSL-libc does indeed look cool. If a volunteer wrote the code to make this happen, I suspect the project would accept the code as an unsupported feature.

> Apr 15, 2018

https://github.com/electron/electron/issues/12610#issuecomment-381412186

> I'm closing this for now because we don't plan to support musl officially. I'm happy to offer what help I can, though!

> Sep 12, 2018

https://github.com/electron/electron/issues/9662#issuecomment-420480342

And there's at least one person who succeeded in those threads.

**Comment by veedfj** [comment]
Hi all. Can someone offer the latest update on whether or not there is currently support for latest Alpine Linux? Any progress?

**Comment by F1r3Hydr4nt** [comment]
I just stumbled upon this annoying issue and found the dependencies listed on [Cypress' website](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies), but could not find equivalent packages like this person: https://gitlab.com/gitterHQ/webapp/-/merge_requests/1852 so I tried the following:

```
sudo apk add libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev lib
gconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
ERROR: unable to select packages:
  libasound2 (no such package):
    required by: world[libasound2]
  libgbm-dev (no such package):
    required by: world[libgbm-dev]
  libgconf-2-4 (no such package):
    required by: world[libgconf-2-4]
  libgtk-3-0 (no such package):
    required by: world[libgtk-3-0]
  libgtk2.0-0 (no such package):
    required by: world[libgtk2.0-0]
  libnss3 (no such package):
    required by: world[libnss3]
  libxss1 (no such package):
    required by: world[libxss1]
  libxtst6 (no such package):
    required by: world[libxtst6]
```

Then I searched and found what I think might be suitable replacements:
```
sudo apk add xauth xvfb libxtst alsa-lib-dev libxscrnsaver nss l
ibnotify-dev mesa-gbm gtk+3.0 gtk+2.0

sudo apk add gconf --repository=http://dl-cdn.alpinelinux.org/alpine/
v3.8/main
```

To no avail:
```
yarn cy:open
yarn run v1.22.10
$ cypress open
It looks like this is your first time using Cypress: 6.3.0
  ✖  Verifying Cypress can run /home/alb/.cache/Cypress/6.3.0/Cypress
    → Cypress Version: 6.3.0
Cypress failed to start.

This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Command failed with ENOENT: /home/alb/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=980
spawn /home/alb/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT
----------
Platform: linux (Alpine Linux - 3.13.0)
Cypress Version: 6.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is not very verbose ^ where is the log file?

**Comment by x-yuri** [comment]
@F1r3Hydr4nt https://docs.cypress.io/guides/references/troubleshooting.html#Print-DEBUG-logs

**Comment by F1r3Hydr4nt** [comment]
@x-yuri Thank you, here is the output, it does not mention any specific missing dependency as far as I can see:
```
export DEBUG=cypress:*
hostname:~/Work/base$ yarn cypress open
yarn run v1.22.10
$ /home/Work/base/node_modules/.bin/cypress open
  cypress:cli:cli cli starts with arguments ["/usr/bin/node","/home/Work/base/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +3ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +160ms
  cypress:cli opening from options {"project":"/home/Work/base"} +0ms
  cypress:cli command line arguments ["--project","/home/Work/base"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +2ms
  cypress:cli checking if executable exists /home/.cache/Cypress/6.3.0/Cypress/Cypress +5ms
  cypress:cli Binary is executable? : true +13ms
  cypress:cli binaryDir is  /home/.cache/Cypress/6.3.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/.cache/Cypress/6.3.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 6.3.0 installed in: /home/.cache/Cypress/6.3.0/Cypress +14ms
  cypress:cli could not read binary_state.json file at "/home/.cache/Cypress/6.3.0/binary_state.json" +19ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +5ms
  cypress:cli running binary verification check 6.3.0 +0ms
It looks like this is your first time using Cypress: 6.3.0

  cypress:cli clearing out the verified version +5ms
  cypress:cli DISPLAY environment variable is set to :0.0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +4ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli disabling Electron sandbox +1ms
  **cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/.cache/Cypress/6.3.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command failed with ENOENT:** /home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452
spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress',
  path: '/home/.cache/Cypress/6.3.0/Cypress/Cypress',
  spawnargs: [ '--no-sandbox', '--smoke-test', '--ping=452' ],
  originalMessage: 'spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT',
  shortMessage: 'Command failed with ENOENT: /home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452\n' +
    'spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT',
  command: '/home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +24ms
  cypress:cli error message: Command failed with ENOENT: /home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452
spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT +2ms
  ✖  Verifying Cypress can run /home/.cache/Cypress/6.3.0/Cypress
    → Cypress Version: 6.3.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed with ENOENT: /home/.cache/Cypress/6.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=452
spawn /home/.cache/Cypress/6.3.0/Cypress/Cypress ENOENT

----------

Platform: linux (Alpine Linux - 3.13.0)
Cypress Version: 6.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Maybe this will help, not sure what the 'smoketest' is about

**Comment by x-yuri** [comment]
This will unlikely help. Does `/home/.cache/Cypress/6.3.0/Cypress/Cypress` exist? What `ldd /home/.cache/Cypress/6.3.0/Cypress/Cypress` says?

**Comment by F1r3Hydr4nt** [comment]
```
ldd /home/.cache/Cypress/6.3.0/Cypress/Cypres
s
	/lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
	libffmpeg.so => /home/.cache/Cypress/6.3.0/Cypress/libffmpeg.so (0x7f551108e000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x7f5511043000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7f5510f3c000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x7f5510d93000)
	libnss3.so => /usr/lib/libnss3.so (0x7f5510c87000)
	libnssutil3.so => /usr/lib/libnssutil3.so (0x7f5510c58000)
	libsmime3.so => /usr/lib/libsmime3.so (0x7f5510c32000)
	libnspr4.so => /usr/lib/libnspr4.so (0x7f5510bef000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x7f5510bc8000)
	libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x7f5510b94000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x7f5510a72000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x7f5510a6d000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f5510a46000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x7f55109fc000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x7f55109da000)
	libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x7f5510282000)
	libgdk-3.so.0 => /usr/lib/libgdk-3.so.0 (0x7f5510197000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x7f5510187000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x7f5510141000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x7f5510052000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x7f551004d000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x7f5510048000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x7f5510035000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x7f551002d000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x7f5510021000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f550fffe000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x7f550ffec000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x7f550ffaf000)
	libgbm.so.1 => /usr/lib/libgbm.so.1 (0x7f550ffa0000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x7f550fed9000)
	libcups.so.2 => /usr/lib/libcups.so.2 (0x7f550fe52000)
	libatspi.so.0 => /usr/lib/libatspi.so.0 (0x7f550fe1f000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f550fe05000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f551963e000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/.cache/Cypress/6.3.0/Cypress/Cypress)
	libffi.so.7 => /usr/lib/libffi.so.7 (0x7f550fdfa000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7f550fd9e000)
	libintl.so.8 => /usr/lib/libintl.so.8 (0x7f550fd91000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x7f550fd8c000)
	libz.so.1 => /lib/libz.so.1 (0x7f550fd72000)
	libmount.so.1 => /lib/libmount.so.1 (0x7f550fd21000)
	libplc4.so => /usr/lib/libplc4.so (0x7f550fd1a000)
	libplds4.so => /usr/lib/libplds4.so (0x7f550fd15000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x7f550fd10000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f550fd08000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x7f550fc66000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x7f550fc4f000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f550fc12000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f550fb5e000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x7f550fb41000)
	libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x7f550fb36000)
	libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x7f550fa26000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x7f550fa15000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x7f550fa05000)
	libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x7f550f9fc000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x7f550f9f7000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x7f550f9eb000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x7f550f9e6000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x7f550f950000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f550f91f000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x7f550f91a000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x7f550f90b000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x7f550f8ff000)
	libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x7f550f8ea000)
	libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x7f550f8dd000)
	libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x7f550f8cb000)
	libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x7f550f6f9000)
	libblkid.so.1 => /lib/libblkid.so.1 (0x7f550f6b1000)
	libbsd.so.0 => /usr/lib/libbsd.so.0 (0x7f550f69b000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x7f550f67c000)
	libuuid.so.1 => /lib/libuuid.so.1 (0x7f550f672000)
	libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f550f663000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x7f550f656000)
	libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x7f550f547000)
	libunistring.so.2 => /usr/lib/libunistring.so.2 (0x7f550f3d1000)
	libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x7f550f3bd000)
	libnettle.so.8 => /usr/lib/libnettle.so.8 (0x7f550f379000)
	libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x7f550f332000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f550f2cc000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x7f550f2a9000)
Error relocating /home/.cache/Cypress/6.3.0/Cypress/libffmpeg.so: __isnan: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/libffmpeg.so: __isinf: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/libffmpeg.so: strtoll_l: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/libffmpeg.so: strtoull_l: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __snprintf_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __sprintf_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __memcpy_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __fprintf_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __memmove_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: gnu_get_libc_version: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __fdelt_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __vsnprintf_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __strncpy_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __isnan: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __isinf: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __sbrk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __res_nclose: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __res_ninit: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __isnanf: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __longjmp_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __memset_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: strtoll_l: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: strtoull_l: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: backtrace: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __strncat_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: random_r: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: initstate_r: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __isinff: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __vfprintf_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __register_atfork: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __longjmp_chk: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: __libc_stack_end: symbol not found

```

**Comment by F1r3Hydr4nt** [comment]
> Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/.cache/Cypress/6.3.0/Cypress/Cypress)

This is taken care of by: `sudo apk add gcompat`

**Comment by x-yuri** [comment]
Which means (predictably) that you first need to [build `electron`][1], only then you can proceed with running Cypress, since the latter "uses the Electron binaries."

[1]: https://github.com/electron/electron/issues/9662#issuecomment-599019635

**Comment by F1r3Hydr4nt** [comment]
Aha yes, the _predictable_ libc vs musl roadblock because obviously Cypress _"uses the Electron binaries"_ how ignorant of me...
Despite the fact that chromium is available from the [community repo](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) work [building electron has stalled](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7310).  I tried installing the [void electron binary](https://void.johnnynator.dev/electron/) with [no luck either](https://pastebin.com/FA0y7yhA).

I wonder how we might force Cypress to point towards the unofficially supported alpine community repo Chromium?

**Comment by x-yuri** [comment]
Is this what you're looking for? https://docs.cypress.io/guides/guides/launching-browsers.html#Launching-by-a-path

**Comment by F1r3Hydr4nt** [comment]
Correct, thanks though it nearly worked and gave some better errors:
```
yarn cypress run --browser /usr/bin/chromium-browser 
yarn run v1.22.10
$ /home/Work/base/node_modules/.bin/cypress run --browser /usr/bin/chromium-browser
It looks like this is your first time using Cypress: 6.3.0

  ✖  Verifying Cypress can run /home/.cache/Cypress/6.3.0/Cypress
    → Cypress Version: 6.3.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: random_r: symbol not found
Error relocating /home/.cache/Cypress/6.3.0/Cypress/Cypress: initstate_r: symbol not found

----------

Platform: linux (Alpine Linux - 3.13.0)
Cypress Version: 6.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by scott-f9** [comment]
Any chance of support for Alpine Linux? Cypress still will not run on it. Alpine Linux is integral to many testing pipelines that use Docker, so it'd be really great to get support.

**Comment by salarhfz-fs** [comment]
Same here. Please support Alpine Linux. All of our organization pipelines are on Alpine. It's really necessary.

**Comment by x-yuri** [comment]
@scott-f9 @salarhfz-fs The issue is with [Electron][a], not with Cypress. If you can provide step-by-step instructions on how to build Electron under Alpine Linux that would be a major push in this direction.

[a]: https://github.com/cypress-io/cypress/issues/419#issuecomment-661311049

**Comment by akauppi** [comment]
To widen the envelope a bit, the browser engine doesn't need to be Electron, right? The original poster doesn't define which engine they want to run.

This comment [mentions}(https://github.com/cypress-io/cypress/issues/419#issuecomment-289461984) it in 2017:

>This likely has to do with electron and not necessarily Cypress.
>
>It may be easier opening an issue over there https://github.com/electron/electron/issues and ask about what it will take to build Chromium against Alpine.

**Comment by x-yuri** [comment]
@akauppi Correct me if I'm wrong, but in order to run Cypress you need Electron, even if you run your tests in Edge down the road.

By the way, I just noticed that there's a [`chromium`][a] package under Alpine Linux. Which makes me think that the hardest part is done. But it's been there at least since v3.3, which might suggest that there's more to it than that.

[a]: https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.16&arch=x86_64

**Comment by cbleek** [comment]
I have also stumbled across this problem. I am under the impression that it has now been described in detail and that someone familiar with the components involved can do it for little money.

I would be willing to give $100 to the person who summarizes the details found and describes what needs to be done.

$500 I would pay for the implementation.

How do you guys see this. Am I completely wrong on this or is this realistic.

**Comment by F1r3Hydr4nt** [comment]
Here are steps to build electron for libc: https://www.electronjs.org/docs/latest/development/build-instructions-linux
And for musl (alpine), you have to patch as discussed in this [thread](https://github.com/electron/electron/issues/9662#issuecomment-591719521).

**Comment by cbleek** [comment]
I've created an $500 offer. https://www.upwork.com/jobs/~01a73a498cdd7bd7f5

**Comment by JuliaFoerster** [comment]
Hi @cbleek The offer is not on the website anymore. Has someone completed it? Is so, can you share the image? If not, will I get 500 USD if I share the image with you? It's a win & win situation for me ;-) Unless you dont reply.

**Comment by cbleek** [comment]
It's a task that takes a lot of time. Rather weeks than days. At least that's what I was told by a very good developer who wanted to try. 

> Unfortunately I didn't make much substantial progress worth sharing, I was just trying to build electron with musl-libc by trying to apply the patches from alpine's chromium package, that kinda worked but there were still plenty of failures to fix.. TBH, even if I would have gotten it to build, it isn't clear how it would been incorporated into the electron project..

**Comment by JessicaSachs** [comment]
👋🏻 Hey friends. Perhaps I could get a quick status update here? @flotwig do you know what the deal is w/ Alpine? I'm going through like 8 repositories at work and adding Cy in is particularly painful because the Docker setups are Alpine-based 😸

**Comment by liam-verta** [comment]
It looks like there's a package for `electron` in the `testing` repository for Alpine: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/electron

**Comment by tobiasbueschel** [comment]
Linking a related issue of the `cypress-docker-images` repository: https://github.com/cypress-io/cypress-docker-images/issues/110

**Comment by damianobarbati** [comment]
@tobiasbueschel @liam-verta @cbleek did you manage to find a solution for this?
Alpine is maybe the most used base image in docker, how can this still be an issue? 😢

**Comment by leordancarmona07** [comment]
### Your system is missing the dependency: Xvfb

**Ecountered**: 

```
$ npm run RunTCOnChrome
> cy-cucumber-test@1.0.0 RunTCOnChrome
> cypress run --browser chrome
It looks like this is your first time using Cypress: 13.8.1
[STARTED] Task without title.
[FAILED] Your system is missing the dependency: Xvfb
[FAILED] 
[FAILED] Install Xvfb and run Cypress again.
[FAILED] 
[FAILED] Read our documentation on dependencies for more information:
[FAILED] 
[FAILED] https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] If you are using Docker, we provide containers with all required dependencies installed.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Error: spawn Xvfb ENOENT
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Debian - 12)
[FAILED] Cypress Version: 13.8.1
Your system is missing the dependency: Xvfb
Install Xvfb and run Cypress again.
Read our documentation on dependencies for more information:
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Error: spawn Xvfb ENOENT
----------
Platform: linux-x64 (Debian - 12)
Cypress Version: 13.8.1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
```

**gitlab-ci.yml**
```
stages:
  - test

e2eChrome:
  image: cypress/browsers:node18.12.0-chrome107
  stage: test
  script:
    - npm ci
    - npm run RunTCOnChrome
```

**package.json**
```
"scripts": {
    "test": "cypress open",
    "RunTCOnChrome": "cypress run --headless --browser chrome",
    "RunTCOnElectron": "cypress run --headless --browser electron"
}
```

**Requesting assistance please, I need it on our company project.**

@jennifer-shehane @MikeMcC399

**Comment by MikeMcC399** [comment]
@leordancarmona07

> Requesting assistance please, I need it on our company project.

You can request assistance from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

You can also refer to the [GitLab CI documentation](https://docs.cypress.io/guides/continuous-integration/gitlab-ci) for using Cypress in this environment. In the example given on the documentation site, the Cypress Docker version used is `cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1`. This is not the latest version, however it is a lot newer than the image `cypress/browsers:node18.12.0-chrome107` you mention in your post.

Since this issue is marked as https://github.com/cypress-io/cypress/labels/type%3A%20feature and it not listed on the [Cypress App Priorities](https://github.com/orgs/cypress-io/projects/13) dashboard it is unlikely to meet your needs in the short term.

**Comment by nightswimmings** [comment]
Is there a way at least to run with other browsers without initialising electron?

Im trying desperately something like CYPRESS_BROWSER=chromium CYPRESS_SKIP_VERIFY=true ELECTRON_RUN_AS_NODE=1 DEBUG=cypress:* npx cypress run --component --browser chromium --config video=false,trashAssetsBeforeRuns=false --no-exit

but still it looks that when cypress binary is spawned, it still uses electron (assumption by the comments in this thread)

  cypress:cli verifying Cypress app +0ms
  cypress:cli Using CYPRESS_SKIP_VERIFY from environment variable +5ms
  cypress:cli skipping verification of the Cypress app +2ms
  cypress:cli:run processing run options { key: null, spec: null, reporter: null, reporterOptions: null, project: '/test_project' } +0ms
  cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY +4ms
  cypress:cli:run run to spawn.start args ["--run-project","/test_project"] +1ms
  cypress:cli Environment variable ELECTRON_RUN_AS_NODE detected, xvfb is not needed +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +4ms
  cypress:cli spawn args [ '/root/.cache/Cypress/14.3.0/Cypress/resources/app/index.js', '--run-project', '/test_project', '--cwd', '/test_project', '--userNodePath', '//node-v18.20.8-linux-x64-musl/bin/node', '--userNodeVersion', '18.20.8' ] { detached: false, stdio: 'inherit' } +17ms
  cypress:cli spawning Cypress with executable: /root/.cache/Cypress/14.3.0/Cypress/Cypress +5ms
Error relocating /root/.cache/Cypress/14.3.0/Cypress/Cypress: posix_fallocate64: symbol not found
Error relocating /root/.cache/Cypress/14.3.0/Cypress/Cypress: __res_init: symbol not found

**Comment by MikeMcC399** [comment]
Alpine Linux is `musl` based (rather than being based on `libc`) (as already mentioned several years ago in https://github.com/cypress-io/cypress/issues/419#issuecomment-287076886).

Cypress' Docker images are based on Debian (`libc`) with fully supported Node.js components. The base image used is [debian:slim](https://hub.docker.com/_/debian) with minimal packages added that are needed to support Cypress runtime usage.

The `musl` builds of Node.js required for Alpine Linux belong to the "Experimental" category and are produced by https://unofficial-builds.nodejs.org/, so this is a whole ecosystem issue, not just one that depended on Electron.

**Comment by gsouf** [comment]
Why trying to fix electron, and not just get cypress not to depend on electron? Do you really need electon to run headless using chrome/firefox?

We've run nodejs in alpine for years, I'm not sure to understand why it's a "whole ecosystem issue"
