### ISSUE TITLE
RangeError: Maximum call stack size exceeded error thrown on DocumentFragments

### ISSUE THREAD

**Issue by covaHL** [cypress-io/cypress#4373]
### Current behavior:

Currently i am start using cypress in a Salesforce based web, but when i try to use the Lightning elements that salesforce provides i receive the error for maximum call stack
Just for the record for every element it works fine only in elements like this one:

The element is the following: `label lightning-input_input=""`
 
![image](https://user-images.githubusercontent.com/51169712/58827684-3693e300-8609-11e9-8446-aee2638f8047.png)

### Desired behavior:

I want that elements such as `lightning-input` can be clickable or you can write on them

### Steps to reproduce: (app code and test code)

.
### Versions

3.3.1

**Comment by jennifer-shehane** [comment]
- Can you provide the test code you are running?
- Please click on the 'maximum call stack' error with DevTools open, please provide screenshot of this error printed in console.
- Ideally a way to run this locally on my side is needed to look into it.

**Comment by covaHL** [comment]
Hi Jennifer  I already sent you the code via email here is what the console shows
![image](https://user-images.githubusercontent.com/51169712/58986580-53641e00-87a3-11e9-9cd3-ea432ad528c8.png)

**Comment by viral222** [comment]
Hi Jennifer i am getting same error also using Salesforce cannot get to navigation cypress gives error 
"RangeError: Maximum call stack size exceeded"
![Screen_Shot_2019-06-25_at_2_54_26_PM](https://user-images.githubusercontent.com/24903381/60132698-48286080-9759-11e9-81df-0b3db205a8f7.png)
![Screen_Shot_2019-06-25_at_2_53_14_PM](https://user-images.githubusercontent.com/24903381/60132732-57a7a980-9759-11e9-82c8-815fcce02f86.png)

**Comment by jennifer-shehane** [comment]
@viral222 Are you using version 3.3.2 of Cypress? Some changes were made in there. 

@covaHL Can you try using version 3.3.2 of Cypress? Does the issue still persist?

Id the issue still persists, we will need a way to reproduce this locally on our machine, if you can provide a way for us to reproduce.

**Comment by viral222** [comment]
@jennifer-shehane  yes i am using Version 3.3.2 
![Screen_Shot_2019-07-08_at_9_24_29_AM](https://user-images.githubusercontent.com/24903381/60822506-c83fc480-a162-11e9-9cea-a27f1a148df5.png)

**Comment by covaHL** [comment]
@jennifer-shehane @viral222  I am using 3.3.2 as well and did a debug session looks like it stucks in the method elIsHiddenByAncestors due to a wrap that it does to the element, that method can be found in cypress_runner.js line code 87101

due is a recursive function it throws the maximum call stack size exceeded, working on a workaround meanwhile cypress team can troubleshoot or reproduce the issue

**Comment by covaHL** [comment]
Results of debug session
![image](https://user-images.githubusercontent.com/51169712/60838888-68144700-a191-11e9-89a3-0fed5638b3f9.png)
![image](https://user-images.githubusercontent.com/51169712/60838904-76faf980-a191-11e9-99dc-66b28a85b6bf.png)
from the span that is marked i want to climb as elIsHiddenByAncestors but it gets stucked as you can see below because $(el).parent() selects the same element
![image](https://user-images.githubusercontent.com/51169712/60839010-bb869500-a191-11e9-84d2-8414e560bf18.png)

**Comment by covaHL** [comment]
@viral222 @jennifer-shehane this is a duplacted of this issue
https://github.com/cypress-io/cypress/issues/144
in the third bullet it shows the same behaviour

**Comment by ZwapKillrath** [comment]
Having issues after I updated from Cypress 3.3.1 to 3.4.1. I am getting "Uncaught RangeError: Maximum call stack size exceeded." all over the place in the console now. Did not get that before. I use Electron 61 and Chrome 76. Both shows the same
![image](https://user-images.githubusercontent.com/49122691/62542239-b3d31280-b85b-11e9-8871-59d156848615.png)

**Comment by jennifer-shehane** [comment]
Can anyone provide code for our team to run to reproduce this problem? We really want to help, but we can’t begin solving any of your problems without that.

**Comment by jennifer-shehane** [comment]
I have been given a way to reproduce this. It is narrowed down to the `elIsHiddenByAncestors` function. 

In this case for some reason getting the `parent()` of a lightning input element yields itself, so we call up the parent recursively, but it essentially just calls the same function on itself forever. 

This is what `$el` and `$el.parent()` and `parentNode` evaluate as through 3 loops of the function.

<img width="893" alt="Screen Shot 2019-10-04 at 4 23 10 PM" src="https://user-images.githubusercontent.com/1271364/66237668-ab645000-e6c3-11e9-8802-3a2181f614c4.png">

I'd like to try this on our newer version of jQuery, but also there could be some other super strange reason this isn't working that I don't understand yet.

**Comment by Bkucera** [comment]
This issue may be fixed with #4913 , as I suspect it is due to us overriding focus in 3.4.1. 

However, we have still not been able to reproduce the issue

**Comment by jennifer-shehane** [comment]
@Bkucera I have a reproducible example, albeit too complex to add to our own testing suite - I will pull down `develop` to see and confirm if this is fixed.

**Comment by jennifer-shehane** [comment]
Unfortunately #4913, nor any other PR in the 3.5 prerelease, fixes this issue. 

This also continues to happen down to version 3.0.0, so I've seen no evidence that this was a bug introduced in a version after 3.0.0.

We've spent a lot of time on this issue to be honest. We have a reproducible example, but it's quite complex and takes a long time to run and we haven't been able to reproduce or narrow the issue down any further. We believe Salesforce is doing some strange things - like potentially reassigning the DOM elements parentNode. 

If someone can give a smaller reproducible example, we may be able to spend more time on this. IE: **An html file and a Cypress test visiting that HTML file.**

**Comment by jennifer-shehane** [comment]
I have a small reproducible example here in this repo: https://github.com/jennifer-shehane/sf-lightning-bug

**Comment by c32hedge** [comment]
I'm seeing this same error when upgrading from 3.2.0 to 3.4.1 or 3.5.0 -- it happens for me on a `cy.task` call. I will work on creating a minimum reproducible example, but in the meantime here's an edited stack trace:

```
CypressError: cy.task(<our task name>) failed with the following error:

> RangeError: Maximum call stack size exceeded
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144418:23)
    at <redacted>/__cypress/runner/cypress_runner.js:144489:34
    at arrayEach (<redacted>/__cypress/runner/cypress_runner.js:142314:11)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144483:7)
    at <redacted>/__cypress/runner/cypress_runner.js:144489:34
    at arrayEach (<redacted>/__cypress/runner/cypress_runner.js:142314:11)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144483:7)
    at Function.cloneDeep (<redacted>/__cypress/runner/cypress_runner.js:152886:14)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:26)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
From previous event:
    at runCommand (<redacted>/__cypress/runner/cypress_runner.js:100007:14)
    at next (<redacted>/__cypress/runner/cypress_runner.js:100142:14)
    at <redacted>/__cypress/runner/cypress_runner.js:100165:18
From previous event:
    at next (<redacted>/__cypress/runner/cypress_runner.js:100142:34)
From previous event:
    at <redacted>/__cypress/runner/cypress_runner.js:100179:37
From previous event:
    at run (<redacted>/__cypress/runner/cypress_runner.js:100171:15)
    at Object.cy.<computed> [as task] (<redacted>/__cypress/runner/cypress_runner.js:100537:11)
    at Context.runnable.fn (<redacted>/__cypress/runner/cypress_runner.js:100724:20)
    at callFn (<redacted>/__cypress/runner/cypress_runner.js:30931:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:30924:7)
    at <redacted>/__cypress/runner/cypress_runner.js:103593:28
From previous event:
    at Object.onRunnableRun (<redacted>/__cypress/runner/cypress_runner.js:103582:17)
    at $Cypress.action (<redacted>/__cypress/runner/cypress_runner.js:97300:30)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:102519:20)
    at next (<redacted>/__cypress/runner/cypress_runner.js:31274:10)
    at <redacted>/__cypress/runner/cypress_runner.js:31296:5
    at timeslice (<redacted>/__cypress/runner/cypress_runner.js:26364:27)
```

Let me know if there's anything else I can do to help pinpoint the error. It's also possible this is a separate issue that's causing the same error message, since my code is working in 3.2.0--let me know if I should create a separate issue.

**Comment by c32hedge** [comment]
Going back through Cypress versions, it looks like the error I'm seeing was first introduced in Cypress 3.3.2, but the stack trace in 3.3.2 is slightly different than the one above (which was 3.5.0):

```
CypressError: cy.task(<our task name>) failed with the following error:

> RangeError: Maximum call stack size exceeded
    at baseKeys (<redacted>/__cypress/runner/cypress_runner.js:32294:22)
    at keys (<redacted>/__cypress/runner/cypress_runner.js:42114:60)
    at baseGetAllKeys (<redacted>/__cypress/runner/cypress_runner.js:31864:20)
    at getAllKeys (<redacted>/__cypress/runner/cypress_runner.js:34664:14)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:31496:39)
    at Function.cloneDeep (<redacted>/__cypress/runner/cypress_runner.js:39895:14)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:26)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
From previous event:
    at runCommand (<redacted>/__cypress/runner/cypress_runner.js:80052:14)
    at next (<redacted>/__cypress/runner/cypress_runner.js:80136:14)
    at <redacted>/__cypress/runner/cypress_runner.js:80148:18
From previous event:
    at next (<redacted>/__cypress/runner/cypress_runner.js:80136:34)
From previous event:
    at <redacted>/__cypress/runner/cypress_runner.js:80155:37
From previous event:
    at run (<redacted>/__cypress/runner/cypress_runner.js:80153:15)
    at Object.cy.<computed> [as task] (<redacted>/__cypress/runner/cypress_runner.js:80380:11)
    at Context.runnable.fn (<redacted>/__cypress/runner/cypress_runner.js:80518:20)
    at callFn (<redacted>/__cypress/runner/cypress_runner.js:52609:21)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:52602:7)
    at <redacted>/__cypress/runner/cypress_runner.js:83512:28
From previous event:
    at Object.onRunnableRun (<redacted>/__cypress/runner/cypress_runner.js:83507:20)
    at $Cypress.action (<redacted>/__cypress/runner/cypress_runner.js:78777:51)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:82573:20)
    at next (<redacted>/__cypress/runner/cypress_runner.js:52948:10)
    at <redacted>/__cypress/runner/cypress_runner.js:52970:5
    at timeslice (<redacted>/__cypress/runner/cypress_runner.js:48211:27)
```

**Comment by gabbersepp** [comment]
FOr me it looks like `.slds-badge` is a document fragment that is not part of the DOM. See: https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment

> The DocumentFragment interface represents a minimal document object that has no parent.

If I start your example @jennifer-shehane I see following:

![image](https://user-images.githubusercontent.com/3234900/67816684-0c0c6000-faab-11e9-9136-981b8868dd59.png)

Which then leads to an infinite loop as this case is not catched by `getFirstFixedOrStickyPositionParent` in `driver/src/dom/elements.ts`

**Comment by gabbersepp** [comment]
See the attached PR. This fixes your example on my machine @jennifer-shehane

**Comment by gabbersepp** [comment]
I tried to create a situation where the document-fragment remains in the DOM but did not succeed. Maybe another ones can give this a try.

According to the html5 documentation, the document-fragment should be empty after appending it to the DOM.

**Comment by JasonFairchild** [comment]
@covaHL or @viral222 or anyone else. Have you had much success testing sites built entirely or partly from Salesforce Lightning web components? I have such a site and can't seem to reference any elements on them. I believe it is because of this polyfill DOM/document-fragment issue that comes about because of SF's implementation of shadow DOM. I'd really like to know if anyone has already found a consistent way to get around this obstacle while using Cypress.

**Comment by gabbersepp** [comment]
@JasonFairchild  If you want to work with shadowdom, please see https://github.com/cypress-io/cypress/issues/144 and https://github.com/cypress-io/cypress/issues/830#issuecomment-449411701 (taken from https://docs.cypress.io/guides/references/trade-offs.html#Permanent-trade-offs-1 ). I have not had issues with shadowdom because we do not use it. But a quick search in google revealed a dedicated cypress plugin. maybe this will help you?

**Comment by JasonFairchild** [comment]
Thank you, but yes. I have read those threads extensively. It was helpful for context, but I think my issue goes a bit beyond them. I'm still learning lots =)

**Comment by mksjha** [comment]
Hi @jennifer-shehane  is that lightning bug fixed in cypress?

![image](https://user-images.githubusercontent.com/18157727/73819912-a74c6880-4844-11ea-8448-f596b5979aaf.png)

I am unable to get element cy .get('.slds-checkbox_faux').click()

**Comment by JasonFairchild** [comment]
It isn't fixed yet. Are you getting the maximum call stack size exceeded error? If you are trying to get an element that is in an lightning web component (and from the screen shot, you look like you are), you will probably have issues beyond this one. See #5528 #6058 and maybe #144

**Comment by mksjha** [comment]
No I am getting never found error. How cypress find element under lighting component?

**Comment by JasonFairchild** [comment]
Well, if you are trying to grab the element directly, and it lives inside a shadow or shadow-like component, then never found is exactly what you are going to get. For sure if you are using LWCs, and maybe if you are using aura web components from SF. Part of the problem is SF locker service, see my explanation in #6058 for that. The next problem after that is solved is #5528 the fact that once a document-fragment is attempted to be grabbed in cypress, you get the maximum stack size exceeded, because LWC elements live inside document-fragments.

**Comment by mksjha** [comment]
hi @JasonFairchild yes. i am getting maximum stack size error with below code now.
cy.shadowGet('flowruntime-flow-screen-input').shadowFind('flowruntime-input-wrapper2').shadowFind('lightning-input').shadowFind('.slds-checkbox_faux').click()

I am planning to use cypress for salesforce test automation and we cannot use cypress due to this issue . Any solution for this issue?

**Comment by mksjha** [comment]
Hi @JasonFairchild  @gabbersepp i see this issue will be fixed by https://github.com/cypress-io/cypress/pull/5528 solution proposed by @gabbersepp. Could you please let us know when it will be available? We cannot use cypress to test salesforce lightning web component due to this issue. Salesforce have explained about document fragment here
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.testing_dom_api

**Comment by JasonFairchild** [comment]
No solution yet until someone comes up with a current fix that has a sufficient test along with it, like Jenifer said near the end of #5528 I think a fix could be close and simple, just no one that both knows cypress and LWC really well has had the time to investigate it thoroughly. Or such person doesn't exist. I certainly don't yet consider myself either a cypress or SF LWC expert. Nonetheless, I may try an attempt at proposing a fix for this, when I get enough time myself.

However, I feel confident enough to tell you that if you were to try to overcome this obstacle with selenium, it is not going to be easy, even though there may not be explicit bugs in the way (UNLESS, maybe you have a really robust and mature selenium framework for your app already...). Basically what SF has done is implemented a detail with their service that presents challenges for any UI testing, period. They have basically admitted as much. Personally, I feel that cypress comes best equipped to deal with said challenge, out of the box. It just has this unfortunately specific current bug. My hope is once it is resolved, it will be mostly smooth sailing with cypress from there.

**Comment by mksjha** [comment]
hi @jennifer-shehane  could you please prioritize this bug? this is blocking testing for whole salesforce platform.

**Comment by jennifer-shehane** [comment]
The code for this is done in #5528, but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
