### ISSUE TITLE
Cookies not being sent in redirect in 3.5.0 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5432]
### Current behavior:

I'm not sure what the issue is, but our Single Sign On Recipe is failing here: https://dashboard.cypress.io/#/projects/6p53jw/runs/32571/failures 

<img width="526" alt="Screen Shot 2019-10-23 at 6 21 12 PM" src="https://user-images.githubusercontent.com/1271364/67438606-ffc36700-f5c1-11e9-9a17-c25944f58943.png">

### Desired behavior:

The Single Sign On should log in and reroute to dashboard page.

### Steps to reproduce: (app code and test code)

1. Pull down https://github.com/cypress-io/cypress-example-recipes
2. Bump `cypress` dependency to `3.5.0`
3. `npm i` in root directory
4. `cd examples/logging-in__single-sign-on`
5. `npm start`
6. in a new tab `npm run cypress:open`

Smallest amount of code to run:

```js
it('can authenticate with cy.request', function () {
  cy.getCookie('cypress-session-cookie').should('not.exist')
  cy.request({
    method: 'POST',
    url: 'http://auth.corp.com:7075/login',
    qs: {
      redirectTo: 'http://localhost:7074/set_token',
    },
    form: true,
    body: {
      username: 'jane.lane',
      password: 'password123',
    },
  })
  .then((resp) => {
    expect(resp.status).to.eq(200)
    expect(resp.body).to.include('<h1>Welcome to the Dashboard!</h1>')
  })
})
```

### Versions

3.5.0

**Comment by joshpzero** [comment]
Confirmed 3.5.0 also broke our SSO on multiple different auth types

**Comment by bahmutov** [comment]
hmm, in this project when I open Cypress 3.5.0 I get still the old version of Electron in the list of browsers, which is really really weird
<img width="801" alt="Screen Shot 2019-10-23 at 6 41 06 PM" src="https://user-images.githubusercontent.com/2212006/67445527-407baa00-f5db-11e9-82b1-1fda7a51e875.png">

**Comment by bahmutov** [comment]
When opening Electron 61 it for real shows in the log
```
cypress:server:browsers opening browser { displayName: 'Electron', family: 'electron', info: 'Electron is the default browser that comes with Cypress. This is the browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.', isChosen: true, majorVersion: '61', name: 'electron', path: '', version: '61.0.3163.100', isHeaded: true, isHeadless: false }
```

**Comment by bahmutov** [comment]
yeahs, seems the `process` shows Electron at 61 for some reason

**Comment by bahmutov** [comment]
ok, I had alpha version of 3.5.0 on my machine, now getting the right one

**Comment by bahmutov** [comment]
## Passing test in 3.4.1
<img width="1279" alt="Screen Shot 2019-10-23 at 6 30 06 PM" src="https://user-images.githubusercontent.com/2212006/67446514-d5cc6d80-f5de-11e9-975a-a55f150d3e21.png">

<img width="1279" alt="Screen Shot 2019-10-23 at 6 30 29 PM" src="https://user-images.githubusercontent.com/2212006/67446521-dbc24e80-f5de-11e9-83a3-40529520f74f.png">

## Failing test in 3.5.0

Notice 4 requests instead of 3

<img width="1279" alt="Screen Shot 2019-10-23 at 9 47 10 PM" src="https://user-images.githubusercontent.com/2212006/67446536-ec72c480-f5de-11e9-91bb-35296e43dffd.png">

**Comment by bahmutov** [comment]
The logs in 3.5.0 (I have added `DEBUG=sso` to this recipe)
```
GET /__cypress/tests?p=cypress/integration/logging-in-single-sign-on-spec.js-945 200 537.970 ms - -
  sso in /login +0ms
  sso checking username "jane.lane" and password "password123 +1ms
  sso username and password match, redirecting to "http://localhost:7074/set_token" +0ms
  sso redirecting to 'http://localhost:7074/set_token?id_token=abc123def456' +1ms
POST /login?redirectTo=http%3A%2F%2Flocalhost%3A7074%2Fset_token 302 17.207 ms - 75
  sso /set_token, query token is abc123def456 +5s
  sso redirecting to /dashboard +1ms
GET /set_token?id_token=abc123def456 302 3.774 ms - 32
  sso nope, redirecting to /unauthorized +14ms
GET /dashboard 302 0.537 ms - 35
  sso rendering unauthorized +10ms
GET /unauthorized 200 1.080 ms - 293
```

**Comment by bahmutov** [comment]
The logs for 3.4.1, the same test "can authenticate with cy.request"
```
GET /__cypress/tests?p=cypress/integration/logging-in-single-sign-on-spec.js-057 200 955.854 ms - -
  sso in /login +0ms
  sso checking username "jane.lane" and password "password123 +2ms
  sso username and password match, redirecting to "http://localhost:7074/set_token" +0ms
  sso redirecting to 'http://localhost:7074/set_token?id_token=abc123def456' +1ms
POST /login?redirectTo=http%3A%2F%2Flocalhost%3A7074%2Fset_token 302 19.954 ms - 75
  sso /set_token, query token is abc123def456 +21s
  sso redirecting to /dashboard +0ms
GET /set_token?id_token=abc123def456 302 3.992 ms - 32
  sso session has id token +13ms
  sso rendering dashboard +0ms
GET /dashboard 200 1.891 ms - 155
  sso session has id token +82ms
  sso rendering dashboard +0ms
GET /dashboard 200 1.346 ms - 155
```

**Comment by bahmutov** [comment]
@flotwig seems like a cookie is not being sent in 3.5.0 after redirect

**Comment by skylock** [comment]
In **3.4.1**
![Screenshot 2019-10-24 at 07 42 01](https://user-images.githubusercontent.com/4140367/67455049-f9220780-f634-11e9-91ce-247236f2fe34.png)
Cypress sets all cookies from request response headers set-cookie array

**In 3.5.0**
![Screenshot 2019-10-24 at 08 01 13](https://user-images.githubusercontent.com/4140367/67455119-43a38400-f635-11e9-8be1-8ea906f66b53.png)
Cypress sets only first cookie element from request response headers set-cookie array

**Comment by jennifer-shehane** [comment]
There's a PR open to fix this here: https://github.com/cypress-io/cypress/issues/5432

**Comment by pete-om** [comment]
Heads up for anyone else encountering this, until a patch comes out I'm working around this issue by manually iterating through the set-cookies array, parsing all the key/values out, and calling cy.setCookie(name, value, etcetc) on each cookie

**Comment by codybarr** [comment]
Are we certain this was fixed? It's in the changelog for 3.6.0 but I'm still having issues with our company's login command, keeps bringing us back to the login page. It appears that certain essential cookies are being set in 3.4.1 but not 3.5.0 or 3.6.0.

Not sure if it helps, but our auth has multiple redirects, all of which are apparently followed but cookies aren't being set along the way.

**Comment by skylock** [comment]
> In **3.4.1**
> ![Screenshot 2019-10-24 at 07 42 01](https://user-images.githubusercontent.com/4140367/67455049-f9220780-f634-11e9-91ce-247236f2fe34.png)
> Cypress sets all cookies from request response headers set-cookie array
> 
> **In 3.5.0**
> ![Screenshot 2019-10-24 at 08 01 13](https://user-images.githubusercontent.com/4140367/67455119-43a38400-f635-11e9-8be1-8ea906f66b53.png)
> Cypress sets only first cookie element from request response headers set-cookie array

it reproduces on 3.6 also

**Comment by flotwig** [comment]
@codybarr @skylock So both of you are still experiencing the issue even after upgrading to 3.6.0?

We did definitely fix an issue with setting cookies on redirects in 3.6.0, although it's possible that you guys are experiencing a different issue.

Can you try running your tests with [debug logs enabled][debug], and share the complete logs from your session here? It will show some more information which we can use to get to the root of the issue.

* On Linux/macOS: `DEBUG=cypress:* cypress ...`
* On Windows: `npx cross-env DEBUG=cypress:* cypress cypress ...`

[debug]: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

Note: please make sure you scrub any sensitive data (production credentials, proxy URLs...) before sharing your logs.

**Comment by codybarr** [comment]
Hey @flotwig Thanks for getting back so quick. I've attached logs for a simple test run in 3.4.1 and 3.6.0. I've scrubbed a bunch of data, but hopefully it's still usable.

Let me know if you need anything else.

[3.4.1-output.txt](https://github.com/cypress-io/cypress/files/3798483/3.4.1-output.txt)
[3.6.0-output.txt](https://github.com/cypress-io/cypress/files/3798484/3.6.0-output.txt)

**Comment by pete-om** [comment]
@flotwig I'm also seeing the same problem with 3.6.0

Our login page returns a set-cookie array of length 2 in the response header during a 302 redirect that 1) tries to expire an existing cookie, and 2) sets an auth token cookie
- If a test navigates to the login page, fills the form out manually and submits, both cookies are processed correctly
- If I do a cy.request() to the endpoint that handles the login (ie: programmatic login), only the first cookie from the set-cookie array in the resulting 302 result is processed.

To expand on that last point, when I watch cypress running this test in UI with dev tools open, I can see the first cookie getting expired as expected, but the auth token cookie never gets set.

In 3.4.1 (and earlier), it works fine.

[3.6.0.txt](https://github.com/cypress-io/cypress/files/3802731/3.6.0.txt)
[3.4.1.txt](https://github.com/cypress-io/cypress/files/3802732/3.4.1.txt)
^ scrubbed data, let me know if there's anything else I can do to help.  Thanks!!

**Comment by brian-mann** [comment]
We'll try to get a patch release out soon to fix this.

**Comment by PsySolix** [comment]
I can confirm, even with 3.6.0. The tests that pass in 3.4.1 (using cookies), all still fail in 3.6.0..

**Comment by jhappoldt** [comment]
Thanks @brian-mann.  Should this issue be reopened until the issue is resolved?

**Comment by emijmker** [comment]
@brian-mann Same issue here so +1 on reopening. Tests with login fail on 3.6.0 and pass in 3.4.1. I see something about a release in 3.6.0 3 days ago, but when I download cypress again from https://docs.cypress.io/guides/getting-started/installing-cypress.html#Direct-download, I still get the 31st October version. Can this issue be reopened please? Thanks!

**Comment by flotwig** [comment]
Reopening since there are still some bugs with cookies + redirects. There is a PR open that should fix the issues people here are having: #5478

**Comment by emijmker** [comment]
@brian-mann I've tried the 3.6.1 version but still facing the same problem, so forced to stick to 3.4.1. 

We do a BE call that generates a url with jwt token that redirects us to the final url we can visit and start testing FE from there. 

https://hostname.com/somename/eyJhbetcetcSomeLongJwtToken
redirects to
https://hostname.com/pagetotest

In all versions after 3.4.1 something seems to happen to those jwt-urls so they're not valid and giving us a 504 when trying to visit them. The call to the BE in both cases gives us a 200 and produces a url.

The only difference I've been able to spot is in the response headers when selecting that call in the left Cypress menu and looking into dev tools:
In 3.4.1 no set-cookie
In 3.6.1 a set-cookie: Array(8)
My assumption is that those new (?) cookies (csrf, token) are messing up with the original ones. 

Does this give any clues? Hope to hear back from you, many thanks!

**Comment by flotwig** [comment]
Hey @emijmker -

In Cypress 3.6.1 we fixed some cookie issues. Specifically, cookie within a redirect would not always be set on the correct domain.

Now, if you follow a redirect flow like this:

* www.example.com - sets foo = bar and redirects to auth.example.com
* auth.example.com - sets quuz = quux and redirects to www.example.com/cb
* www.example.com/cb - sets bing = baz and returns HTTP 200

You'll end up with these cookies:

* on www.example.com
	* foo = bar
	* quuz = quux
* on auth.example.com
	* bing = baz

Since this isn't working for you, do you think you could clearly describe the expected redirect flow + final cookies that you expect to be set, like I've done above? That will enable me to create a test case that I can use to figure out why it's not working as you expect.

**Comment by pete-om** [comment]
Still not fixed for me either.

Without a workaround (grabbing the set-cookies element in the redirect response header and manually setting the cookies myself), my authentication script fails in 3.6.1.  It's still only processing the first cookie in the set-cookie array.

Everything works as expected in 3.4.1

**Comment by djaromir** [comment]
I have similar issue authenticating using cy.request() too
Works fine in 3.4.1
In 3.6.1 it works in Electron but not in Chrome 78, desired cookies are not set after cy.request()

**Comment by flotwig** [comment]
@pete-om Thanks a ton for sharing these details! I will get to work on reproducing this and tracking down the issue. These details are awesome.

FYI, I moved your comment to an issue so we can track this more clearly, as this thread is getting messy. New issue: #5688 You might want to watch it to receive updates.

**Comment by codybarr** [comment]
I'm also still experiencing issues on 3.6.1... :/

**Comment by mbcopp** [comment]
Also experiencing issues on 3.6.1

Keep going back to 3.4.1

**Comment by hornta** [comment]
Should this be reopened? I can confirm it doesn't work in 3.6.1 but it works in 3.4.1

**Comment by tozes** [comment]
+1, also having issues on 3.6.1

**Comment by flotwig** [comment]
#5688 is being used to track another known cookie bug in 3.6.1, the specific bug from this issue has been fixed.
