### ISSUE TITLE
type() expects input type to be lowercase

### ISSUE THREAD

**Issue by dvf** [cypress-io/cypress#550]
- Operating System: macOS 10.12.5
- Cypress Version: 0.19.4
- Browser Version: Chrome 59

### Is this a Feature or Bug?

This is a bug.

### Current behavior:

I have a form with an input field `<input type="PASSWORD" id="PASSWORD" />`. 

I get the error:

```
CypressError: cy.type() can only be called on textarea or :text. Your subject is a: <input autocomplete="off" class="focus" id="PASSWORD" name="PASSWORD" onkeypress="DetectCapsLock()" type="PASSWORD">
```

### Desired behavior:

This is an input element, so I would expect the input to be entered.

### How to reproduce:

Create an input with `type = "PASSWORD"` (uppercase), and try `type()`.

#### Test code:

```js
describe('Test can do stuff', () => {
  it('logs in', () => {
    cy
      .visit('https://example.com/login.html')
      .get('#USERNAME')
      .type('dvf')
      .get('#PASSWORD')
      .type('my password', {force: true});
  });
});
```

**Comment by jennifer-shehane** [comment]
Have confirmed bug.

**Comment by chrisbreiding** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)

**Comment by caseybaggz** [comment]
I'm still getting an error similar to this. I have 3 inputs that dynamically show depending on a button click. Typing in the first input works, however typing in the second fails with this error:
```
Command:     type
Typed:       James
Applied To:  <input type=​"input" value id=​"field_middleName" placeholder=​"Middle Name (optional)​" autocomplete=​"off">​
Error:       CypressError: cy.type() can only be called on textarea or :text. Your subject is a: <input type="input" value="" id="field_middleName" placeholder="Middle Name (optional)" autocomplete="off">
```

**Comment by jennifer-shehane** [comment]
@caseybaggz This is actually related to this issue: https://github.com/cypress-io/cypress/issues/586 This error is displaying because type='input' is not a valid input type: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by caseybaggz** [comment]
@jennifer-shehane wow...I have been working too much lately to have overlooked that. Thanks for the humble comment.

![bitmoji](https://render.bitstrips.com/v2/cpanel/d47e2e62-bfa8-405a-b539-03b5adccbc66-13d1204f-dc05-4017-96f4-b795256c8b3f-v1.png?transparent=1&palette=1&width=246)
