### ISSUE TITLE
Handling socks proxy

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#584]
### Current behavior:

After setting up SOCKS proxy to my staging server, my local chrome browser can have access to it, but Cypress not, it loads the website forever.

### Desired behavior:

Cypress should respect SOCKS proxy system settings and be able to access websites which are proxied through given proxy server. 

### How to reproduce:

1. Set up socks proxy in macOS:

<img width="594" alt="screen shot 2017-08-08 at 2 40 33 pm" src="https://user-images.githubusercontent.com/829242/29056800-fcfcb25a-7c48-11e7-82d4-13aa54d36d75.png">

(Preferences / Network / Advanced / Proxies)

2. Forward port from staging machine:

```
ssh -D 9999 my-staging-machine.com
```

3. Try to access staging website which should be available internally only for `my-staging-machine.com`

- Operating System: macOS Sierra 10.12.5
- Cypress Version: 0.19.2
- Browser Version: Chrome 60.0.3112.90

**Comment by vjefri03** [comment]
Cypress is an extension on chrome. I was running into the same issue and getting 503. I fixed it by enabling permissions on the extension. Upper right hand where the three dots for settings
<img width="65" alt="screen shot 2017-10-19 at 9 37 55 pm" src="https://user-images.githubusercontent.com/25537543/31805468-dce18a1c-b515-11e7-8714-1e399de99562.png">
go to extensions and allow permissions
<img width="508" alt="screen shot 2017-10-19 at 9 37 35 pm" src="https://user-images.githubusercontent.com/25537543/31805471-e1856a3e-b515-11e7-8bde-d6d674354a41.png">

<img width="788" alt="screen shot 2017-10-19 at 9 39 47 pm" src="https://user-images.githubusercontent.com/25537543/31805507-1be986c4-b516-11e7-8c33-8f0176ed7ab8.png">

**Comment by timothystone** [comment]
@pawelgalazka @brian-mann @jennifer-shehane I've never seen `node` processes look to the OS proxy configuration. Not saying that you can't expose OS configurations, but it's far more typical to see `rc` or pick your favorite `shell` export these to the runtime.

In my own financial institution, besides SOCKS being strictly locked down, the OS proxy is not exposed to `node` and every developer has documentation to set up their shell, e.g., `.zshenv`, correctly.

Additionally, SOCKS support does not look like something out of the box for `node`, requiring a module. `node` supports most `http_proxy` variables.

**Comment by asyazwan** [comment]
Seems like this is node-specific.

- Setting browser SOCKS5 proxy via extension still fails, but accessing my resource on another tab of Cypress-launched browser works.
- Setting `http_proxy` env to use `socks5` or `socks5h` will spit out error during test run:
```HEAD / 500 3.096 ms - 21
Error: Invalid protocol: socks5h:
    at Request.init (/Users/syazwan/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:454:31)
```

So node itself is not using proxy settings from extension. With the env set, other CLI like `curl` works as expected, but not Cypress.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by dejwsz** [comment]
is it fixed? or socks5 proxy cannot be just used with cypress?

**Comment by jennifer-shehane** [comment]
@dejwsz I did not confirm. We haven't had comments on this issue in years, so hopefully it is fixed.

**Comment by dejwsz** [comment]
Well, after my tests with latest cypress it looks like it isn't. Finally I have just used another proxy so when you have already working socks5 proxy you can add another http -> socks5 one and configure cypress with it. And it works fine. So there is no direct support for socks5 as I found. I have used python's pproxy: https://pypi.org/project/pproxy/. Additionally for the node itself I had set: "npm config set proxy http://localhost:8080" before executing cypress process. For cypress I set such envs: --env HTTP_PROXY=http://localhost:8080,HTTPS_PROXY=http://localhost:8080,NO_PROXY=localhost
Important thing to me was to send also DNS requests via it what is possible over socks5 and pproxy supports it too over http.
