### ISSUE TITLE
Cypress get wrong field in some case

### ISSUE THREAD

**Issue by lippomano** [cypress-io/cypress#5858]
### Current behavior:

Running my tests in angular 8 application I have a strange error happening when I try to write in a specific field. In my case, I want to write in a material autocomplete field but Cypress for some reason select another field that does not have the same selector.

I have about 70 test and this wrong behavior happens only in a specific view and in a specific field.
(it happens in the invoice page when I try to write in customer autocomplete)

If I run 2 tests sequentially and in both of them I try to select the customer autocomplete input, the second one fails every time, and if I try to invert the order of the tests fails always the second one. 

### Desired behavior:

After every test, I have a page reload, after that, I try to write in customer autocomplete to select the customer.

### Steps to reproduce: 

I can't share all the code, it is on a complex page and also in different components.
Here you can see the error in a video:
https://drive.google.com/open?id=1_pDxDW3q4rzoAfQt9G5ba-EsjlQMcd5L

Here you can find cypress code:
[codeshare](https://codeshare.io/a3mROv)

```js
it('update the total amount with manual item', () => {
  cy.route('GET', '**/contacts**').as('contacts');

  cy.visit("/documents/new?documentType=SALES_ORDER");
  cy.wait('@current');
  cy.get('#documentTitle').should('be.visible');

  cy.get('[data-cy=contactSearchAutocomplete]').type('test');

  cy.wait('@contacts');
  cy.wait(1000); // wait auotcomplete
  cy.get('[data-cy=contactSearchAutocomplete]').type('{downarrow}');
  cy.get('[data-cy=contactSearchAutocomplete]').type('{enter}');


  cy.get('#unitPrice0').type('25');
  cy.get('#percentageDiscount0').type('10');
  cy.get('#discountAmount0').type('5');
  cy.get('#taxRate0').click();
  cy.get('#taxRate0').type('{enter}');

  cy.get('[data-cy=totalAmount]').should('contain', '17,50');
});
```

Here the field code:
https://codeshare.io/ayW4gb

```html
<input
  (blur)="hideSearchContactHint()"
  (focus)="showSearchContactHint()"
  (keydown)="onKeydown($event)"
  [formControl]="contactSearchField"
  [matAutocomplete]="customerAuto"
  autocomplete="off"
  matInput
  data-cy="contactSearchAutocomplete"
  name="_ch"
  placeholder="{{ 'searchcomponent.labels.searchcontact' | translate }}"
  type="search"
/>
```

[stackoverflow](https://stackoverflow.com/questions/59030616/cypress-get-wrong-field-in-some-case?noredirect=1#comment104528497_59030616)

### Versions

cypress 3.6 and 3.7
chrome 78
node 12.1
angular 8.2.13
windows 10

**Comment by AlbertoMontalesi** [comment]
I'm getting a similar error where Cypress would target a wrong field.
Also using Angular 8 and Cypress 3.7.

**Comment by jpike88** [comment]
@lippomano can you figure out exactly which version of cypress breaks this issue?

Did you upgrade any other dependencies in your angular project at the same time?

**Comment by lippomano** [comment]
@jpike88 I have these tests from the 3.6 of cypress so I always had this issue.
this is my package.json
https://codeshare.io/5Pq8YY

**Comment by NoriSte** [comment]
Other people reported me similar behaviors in the 3.5 version too but I don't have more details to share at the moment unfortunately...

**Comment by lippomano** [comment]
If I retry multiple times the same test (with this problem), sometimes fails and sometimes not, also if it is the first test, when it fails I see always that cypress write in the same wrong input field

**Comment by AlbertoMontalesi** [comment]
In the end I had to revert to 3.4.1 again to make my tests pass, not to mention that 3.7 was also making certain tests take much longer as addressed here https://github.com/cypress-io/cypress/issues/5824

**Comment by lippomano** [comment]
After some digging, I figure out that probably it's a focus problem, my component makes cypress to lose focus on the selected field exactly when it tries to type in it.
 Strange thing is that the first test always passes (probably it's slower or faster) and if I put some random delay before type in the first field the tests work well.

**Comment by NoriSte** [comment]
Good to know, thank you!!

**Comment by jennifer-shehane** [comment]
We will need a fully reproducible example provided in order to begin investigating (HTML + test code). Can someone provide this? 

Also, please update to the [current version of Cypress](https://on.cypress.io/changelog) as we have fixed several regressions already that were introduced in 3.5 in regards to typing.

**Comment by AlbertoMontalesi** [comment]
@jennifer-shehane updating to 3.8 fixed the issue we were having with Cypress targeting the wrong field, but the performance issue is still there. Cypress 3.4.1 took 14 minutes to run our specs, Cypress 3.8 took 19.30. Same exact specs, same environment, browser was chrome 69.

**Comment by jennifer-shehane** [comment]
@lippomano Is this issue still happening in Version 3.8.0 of Cypress? Please confirm.

**Comment by lippomano** [comment]
It is related to my code, in some case I put focus in some field programmatically, so it makes cypress to lose focus on the field, if I see the get instruction in the console it seems to get the correct field but after that, it writes in another field because I put focus in specific field that is not he selected one.
Now I put some timeout (1 sec) before this operation and It works

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
