### ISSUE TITLE
More comprehensive fix is needed for React 16 to fire change events

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#647]
Issue #536 hacked around the way React works to fire onChange events.

The problem is that this was specific to React and essentially was a quick workaround.

A more comprehensive approach is necessary.

React (and other frameworks) keep the value of an input in sync by overwriting the `value` sett on `HTMLInputElement`.

When Cypress sets this, it triggers the framework to "think" the value has changed and to process that change immediately.

The problem is that when using native events, the browser modifies the value under the hood without it touching the overridden `value` setter.

What we should do is detect when that property is not the default, and instead call underneath it to the original `value` setter so it does not trigger framework code and would work the same way as it does natively.

**Comment by skidding** [comment]
@brian-mann is there a workaround for this in the meantime? Context: I have a search input which updates some React state on change, and I use Cypress to test that the list of items has been filtered based on the query in that input. Any way to force React (v16) to receive the change events?

**Comment by brian-mann** [comment]
Yes. One of our users posted this in the gitter channel

```js
import ReactTestUtils from 'react-dom/test-utils'

Cypress.Commands.add('type', {prevSubject: 'element'}, (sub, value) => {
    const el = sub.get(0)
    el.value = value
    ReactTestUtils.Simulate.change(el)
})
```

The basic idea here is that you can simply require and use React's own test utils to cause the events to be fired.

Instead of replacing `cy.type` as this one user did, I would instead just add a new command like `change`, which then enables you to cause the change event whenever you want to on whichever element you'd like.

**Comment by brian-mann** [comment]
I haven't tried this but you can likely just use our own `cy.trigger` for this as well. React normalized the `change` event to fire over many different types of events so you could try doing something like:

```js
cy.get('input').type(...).trigger('change') // trigger change event or another event type that React listens to and causes the onChange event to fire
```

**Comment by brian-mann** [comment]
At the end of the day, because you have native access to everything in Cypress, this really just comes down to making React fire, which you can do by using its own utilities or firing events directly on the DOM.

**Comment by HugoGiraudel** [comment]
> I haven't tried this but you can likely just use our own cy.trigger for this as well. React normalizes the onChange handler to fire over many different types of events so you could try doing something like:

For the record, this does not work.

**Comment by skidding** [comment]
Thanks @brian-mann for the quick reply. Here is my experience.

> I haven't tried this but you can likely just use our own cy.trigger for this as well

Didn't work for me either.

> Yes. One of our users posted this in the gitter channel

Creating a new Cypress command eventually worked, but with two caveats:
1. The Cypress command must be defined inside the client bundle, and can't be put in the Cypress support files. TestUtils won't be able to trigger the event in the latter case.
2. Building up on the first point, the client bundle must be a development build. Building a file that imports `react-dom/test-utils` for production will error and crash, which means that Cypress can only run on a development build with this workaround.

Happy to hear alternatives!

**Comment by brian-mann** [comment]
We just need to fix this properly. I don't even think it's that difficult, but there are other higher priority tasks like getting `1.0.0` out first.

**Comment by HugoGiraudel** [comment]
Alright. Can we help fixing that? What is the problem exactly? Any pointer?

**Comment by brian-mann** [comment]
Sure. I mean - its nothing magical, its just coming up with a solution for JavaScript.

My idea is this - when we go to change the `.value=` of an input, we first check to see if that property has been overwritten using `Object.getOwnPropertyDescriptor`. If we reset it to 
`HTMLInputElement.prototype.value` or even just call the setter function directly with the `input` as context. That'll end up setting the value and bypass the overridden method.

These kinds of problems mostly just take understanding the problem and knowing how to work around it in JavaScript. Then all you need to do is setup a test that demonstrates the problem - likely an `e2e` test in the `packages/driver` area. You'll see us doing that for other similar things.

**Comment by kanwei** [comment]
👍 Running into this also when we updated to React v16

**Comment by brian-mann** [comment]
Got this fixed. Just need to make sure `<select>` elements don't need this as well.

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by skidding** [comment]
> The code for this is merged, but it has not been released yet.

Awesome! Please do drop another comment when it is released.

**Comment by brian-mann** [comment]
Fixed in [`1.0.2`](https://docs.cypress.io/guides/references/changelog.html#1-0-2).

**Comment by HugoGiraudel** [comment]
Out of curiosity, is it possible that your fix did not fix it for `email` typed inputs?

**Comment by skidding** [comment]
I can confirm this worked for me. Thank you @brian-mann! 🍻

**Comment by Fjoggs** [comment]
Hi, I'm seeing some results that indicate that this fix might not be working for Electron? (If i choose that from the dropdown menu in the Cypress GUI)

My test code:
```js
    it.only('Selecting price changes url', () => {
        cy
            .fillFieldById('price_from', 1337)
            .isInCurrentUrl('price_from=1337')

            .fillFieldById('price_to', 7331)
            .isInCurrentUrl('price_to=7331');
    });
```

FillFieldById command:
```js
Cypress.Commands.add('fillFieldById', (id, value, force = false) => {
    cy.get(`#${id}`).type(value, { force });
});
```

The onChange for these components are not being triggered when running from the terminal (using headless electron), or selecting Electron in the dropdown menu. 
They ARE triggered if I use Chrome.
I can also trigger the onChange if I type the values in myself manually in the Electron window, which is consistent with what happened in Chrome before the fix (and still is, I suppose)

**Comment by chodorowicz** [comment]
I have the same problem, all works flawlessly in Chrome but not in Electron.

**Comment by imvetri** [comment]
This this fixed? I gave cypress a try and still facing this problem with react

**Comment by jennifer-shehane** [comment]
Please open a new issue if you are experiencing similar behavior.
