### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by mjsutherland** [cypress-io/cypress#6776]
### Current behavior:
Brand new Windows 10 laptop. Trying to install Cypress via "npm install cypress --save-dev"
Get error messages (see below) referring to "This is related to npm not being able to find a file"
My node version is v12.16.1
My npm version is 6.13.4
I have tried various things, none of which helped:
+ running "npm init" to create a package.json file
+ creating an empty "node_modules" folder
+ creating by hand a package.json file with devDependencies of "cypress": "^4.1.0" 

```
PS C:\Users\mrmic\Code\Cypress> npm install cypress --save-dev
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
```
[2020-03-18T18_03_54_770Z-debug.log](https://github.com/cypress-io/cypress/files/4350574/2020-03-18T18_03_54_770Z-debug.log)
[2020-03-18T18_03_54_770Z-debug.log](https://github.com/cypress-io/cypress/files/4350577/2020-03-18T18_03_54_770Z-debug.log)

### Desired behavior:

Cypress installed.

### Versions

Trying to install whatever is the latest version of Cypress.
Windows 10.

**Comment by wmyers** [comment]
I'm also finding the `npm install` hanging for the latest release, but earlier releases (e.g. `4.0.1`) are installing ok

**Comment by mjsutherland** [comment]
hi @wmyers, I'm not an expert in npm - what do I need to do to use it to install an earlier version like 4.0.1? Many thanks in advance

**Comment by wmyers** [comment]
just do `npm install cypress@4.0.1`

**Comment by faiezkh** [comment]
hu @wmyers, thanks for the tip, npm install cypress@4.0.1 it works fine.

**Comment by lencioni** [comment]
I think this is fixed by https://github.com/cypress-io/cypress/pull/6777 but that change has not been published yet.

**Comment by lukebettridge** [comment]
Experiencing the same issue, just out of the blue 🤷‍♂

**Comment by Phenomite** [comment]
4.1.0 was the last working copy for people using a staging system like Sonar Nexus, manually adding binary packages for later versions is still not working due to seemingly-hardcoded call to cypress/request library:

Retrying git command: ls-remote -h -t https://github.com/cypress-io/request.git attempt # 2

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/6752 

This issue was introduced in 4.2.0 and will be fixed in our next release. Please roll back to 4.1.0 for now.

**Comment by marzoditch** [comment]
> just do `npm install cypress@4.0.1`

please advise us whats the different between npm install cypress@4.0.1`
 and command npm install cypress --save-dev

**Comment by jennifer-shehane** [comment]
@marzoditch Please refer to `npm install` docs for specifics on how npm install command works: https://docs.npmjs.com/cli/install

**Comment by sophiegaudreaulogient** [comment]
I had the same issue on my side with node.js version 14.15.4 and 15.5.1 installed on my system
After uninstalling node.js and installing version 11.10.1 of node.js, I was able to install cypress without problem.
