### ISSUE TITLE
Issue with antd Table when scroll.x is true

### ISSUE THREAD

**Issue by bn3t** [cypress-io/cypress#7611]
### Current behavior:

The issue is this weird behaviour when `scroll={ x: true }` is used on a Antd Table component (https://ant.design/components/table/#API).

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1102723/83944988-d204f880-a807-11ea-984c-13eabe2154c7.png">

The problem is happening only with cypress >= 4.6.0 and when a parameter scroll x is specified. For example:

```html
<Table
  loading={this.state.loading}
  bordered
  size="small"
  scroll={{ x: true }}
  columns={columns}
  dataSource={this.state.data}
  pagination={{
    pageSize: 5,
    hideOnSinglePage: true,
  }}
/>
```

This is the weirdest behaviour. 

### Desired behavior:

This error should not happen.

### Test code to reproduce

Test project: https://github.com/bn3t/cypress-test-table. The test shows 2 use cases:

* Failing test: http://localhost:3000/
* Succeeding test when scroll.x true is not used: http://localhost:3000/no-scroll-x.

### Versions

Cypress 4.6.0 >= 0, MacOS, Chrome, Firefox, Edge.

**Comment by jennifer-shehane** [comment]
Yah, I can recreate this. It has something to do with the combination of scroll: x and the imported `antd/dist/antd.css`. 

Smallest reproducible code is below. Run:

- `npm start`
- `npm cypress:open`

`package.json`

```json
{
  "name": "my-application",
  "version": "1.2.3",
  "scripts": {
    "start": "react-scripts start",
    "cypress:open": "cypress open"
  },
  "devDependencies": {
    "cypress": "4.7.0",
    "typescript": "^3.9.5"
  },
  "dependencies": {
    "antd": "^4.3.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "^3.4.1"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

`src/index.js`

```js
import React from "react";
import ReactDOM from "react-dom";
import { Table } from "antd";
import "antd/dist/antd.css";

ReactDOM.render(
  <Table
    scroll={{ x: true }}
  />,
  document.getElementById("root")
)
```

`public/index.html`

```html
<html>
<body>
  <div id="root"></div>
</body>
</html>
```

**Comment by jennifer-shehane** [comment]
This was fixed in 4.9.0 so that now it displays the correct error thrown from the application as it did prior to 4.5.0. Probably fixed in https://github.com/cypress-io/cypress/issues/7590

### 4.5.0

<img width="446" alt="Screen Shot 2020-07-09 at 3 01 10 PM" src="https://user-images.githubusercontent.com/1271364/87016708-1152aa80-c1f5-11ea-994e-edf1ca444dc0.png">


### 4.6.0

<img width="448" alt="Screen Shot 2020-07-09 at 3 02 12 PM" src="https://user-images.githubusercontent.com/1271364/87016815-334c2d00-c1f5-11ea-91e0-f7e879240732.png">


### 4.9.0+

<img width="442" alt="Screen Shot 2020-07-09 at 3 09 42 PM" src="https://user-images.githubusercontent.com/1271364/87017643-3f84ba00-c1f6-11ea-8ddd-65a06ef3c798.png">

**Comment by bn3t** [comment]
There is no change in behaviour in 4.9.0, test is still failing and it should not.

Please don't close.

<img width="1795" alt="image" src="https://user-images.githubusercontent.com/1102723/87048676-4f9f9800-c1fc-11ea-85c8-da8257c91c87.png">

**Comment by jennifer-shehane** [comment]
The test is failing because the application is throwing an error about ResizeObserver loop limit exceeded. This is not an error coming from Cypress. 

Cypress fails tests when uncaught exceptions are thrown from the application under test. You can ignore this error by added the following to your tests. 

```js
Cypress.on('uncaught:exception', (err) => {
  if (err.message.includes('ResizeObserver')) {
    // returning false here prevents Cypress from
    // failing the test
    return false;
  }
  return true;
});
```

**Comment by bn3t** [comment]
Thanks for the info. It was really confusing because the application does not show any sign of a thrown exception. Only Cypress is getting this error. Furthermore, my real application has several tests with such a table containing the scroll feature. These tests behave correctly in 4.5.0.

Thank you for your help.
