### ISSUE TITLE
Cypress does not yet provide an option to disable websecurity for Firefox

### ISSUE THREAD

**Issue by nandansam89** [cypress-io/cypress#7677]
### Problem:
I am unable to run Cypress on Firefox due to its adherence to [same origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). This issue can be fixed on chrome by setting the `chromeWebSecurity` to `false` in configuration.
 
Cypress should provide such a solution for the firefox browser.
The error message received on ``cy.visit()``:
```Permission denied to access property "addEventListener" on cross-origin object```

### Versions

Cypress version : 4.8.0
O.S: Ubuntu 18.04
Browser : Firefox 77

**Comment by estefafdez** [comment]
I'm in on this proposal. I would love to be able to use iframes on firefox, but now I can't. thanks!

**Comment by carlosthe19916** [comment]
My application uses [Keycloak](https://www.keycloak.org/) and it is not possible to test Cypress with Firefox because of `Permission denied to access property "addEventListener" on cross-origin object`. Any update on this?

**Comment by levmillr** [comment]
Using [cypress-keycloak-commands](https://www.npmjs.com/package/cypress-keycloak-commands) is working for me in firefox. I am on windows 10 firefox 83 and 84 dev edition- I haven't tried in ubuntu, however.

**Comment by alokverma75** [comment]
I am trying to run testcases using run command via command line and build is failing with below message for FireFox version 87:
 SecurityError: Permission denied to access property "addEventListener" on cross-origin object

Is there any solution to this issue though test run well when tested from open mode and run the test?

**Comment by teymurbabayev** [comment]
We are experiencing the exact same issue.
Any feedback from the Cypress team whether there are plans to address this?

**Comment by oembe** [comment]
Currently having the same problem. Any update? Testing in Firefox would be great!

**Comment by LuckyTembhurne** [comment]
For cross-browser Testing, need this feature in Firefox as well.
Any update from Cypress team about this?

**Comment by bahmutov** [comment]
Unfortunately, there is nothing we can do right now because it is up to the Firefox team to add a similar feature to the Firefox browser. We cannot "bypass" or add this from the Cypress side.

**Comment by veronicamirada** [comment]
Has someone opened an issue to firefox related to this? Maybe the cypress team can do it and have more visibility than a normal dev. For now we are going to skip tests in firefox until there is a solution.

**Comment by IAmNatch** [comment]
This has been an ongoing discussion on the firefox threads for the past 6 years:
https://bugzilla.mozilla.org/show_bug.cgi?id=1039678

Although I'd like to see resolution, it seems as though we'd need buy-in from the firefox team to make this a reality.

**Comment by faith-berroya** [comment]
Hello, I'm currently encountering the same issue. Do we have an update for this? I'm using Firefox 100 with `"chromeWebSecurity": false,` but it says it will not have an effect in Firefox.

**Comment by alokverma75** [comment]
Please check latest version of Cypress as multiple domains are now allowed
and firefox issues are resolved now.

**Comment by jakob-lilliemarck** [comment]
I have a similar, if not the same, issue when running tests using `cy.origin` for firefox using cypress 9.7.0. Works with chrome and electron thugh.

Im getting the error while trying to authenticate with auth0 according to their latest documentation on how to authenticate during cypress tests using `cy.session` and `cy.origin`. Would love a fix or some insight!

**Comment by faith-berroya** [comment]
I updated to 9.7.0 already with Firefox 100 and I'm still having some issues. Do we have an alternative for `"chromeWebSecurity": false,` in Firefox? In Chrome and Edge it works fine.

**Comment by faith-berroya** [comment]
Hi @jennifer-shehane , do we have a timeline from Cypress team for this? We're really looking forward to this.

**Comment by 787681277** [comment]
I updated to Cypress 10.9.0 already with Firefox v106 and I'm still having some issues. Do we have an alternative for "chromeWebSecurity": false, in Firefox? In Chrome, it works fine.

**Comment by pavelloz** [comment]
It would be very nice to be able to test oAuth flows on Firefox :)

**Comment by sajjad541** [comment]
Hi @jennifer-shehane  Any update regarding Firefox webSecurity flag?

**Comment by GrayedFox** [comment]
> Has someone opened an issue to firefox related to this? Maybe the cypress team can do it and have more visibility than a normal dev. For now we are going to skip tests in firefox until there is a solution.

Please see this 9 year old thread on the Bugzilla forums - if you want to see a simple switch added that achieves similar or the same functionality in Firefox - make a Bugzilla account and upvote this thread:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1039678

**Comment by mudit94** [comment]
adding cy.wait() fixed this for me

**Comment by alex-grinberg** [comment]
Do we have any news on the flag off for web security with firefox?
Some tests on my side requires me to disable for it work. Off course with chrome using the **_chromeWebSecurity: false_** works.

**Comment by jennifer-shehane** [comment]
We'll close this issue. Since this functionality does not exist in Firefox as noted in this thread, there's nothing we can do to offer this. https://bugzilla.mozilla.org/show_bug.cgi?id=1039678 

If you want to test across origins. We recommend using [cy.origin](https://docs.cypress.io/api/commands/origin) and not disabling web security on any browser.

**Comment by svetlana-napris-elucid** [comment]
@jennifer-shehane what you suggest in case we use different subdomain? In this case we can't use cy.origin and Cypress team not going to fix it. So, for us the problem remains.
