### ISSUE TITLE
Missing information about git branch in cypress dashboard runs for BuildKite

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#777]
### Current behavior:

Lack of information about the git branch in Cypress Dashboard runs

<img width="873" alt="screen shot 2017-10-20 at 11 48 37 am" src="https://user-images.githubusercontent.com/829242/31800471-ddc59e1a-b58c-11e7-8f5c-3aaf514712c8.png">

I couldn't find anything about that in the docs, issues and in configuration.

### Desired behavior:

See information from what git branch Cypress test runs comes from.

- Operating System: Linux Debian - 8.8
- Cypress Version: 1.0.2
- Browser Version: Electron 53.0.2785.143
- CI service: Buildkite

**Comment by bahmutov** [comment]
We might not grab the branch for buildkite CI, hope there is env var with this info. Or we can call git to find out

**Comment by brian-mann** [comment]
Seeing 113 tests pass with 0 failures makes me happy ;-)

This function is responsible for figuring out the branch:
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/record.coffee#L25

It uses env vars for a few known CI providers, otherwise it pulls it from `git`. Not sure why it would not be able to read it off correctly.

**Comment by pawelgalazka** [comment]
Would be great to provide to cypress env name which store info about the branch.

**Comment by brian-mann** [comment]
We could just add buildkite branch to the function

https://buildkite.com/docs/builds/environment-variables

**Comment by pawelgalazka** [comment]
Also would be great to fill out `CI` field as for buildkite it just shows `unknown`

**Comment by bahmutov** [comment]
I think git cannot determine the branch there, because (I am playing with Buildkite now) it does a trick to check (it is not a branch)
```
$ git checkout -f FETCH_HEAD
--
  | Note: checking out 'FETCH_HEAD'.
  |  
  | You are in 'detached HEAD' state. You can look around, make experimental
  | changes and commit them, and you can discard any commits you make in this
  | state without impacting any branches by performing another checkout.
  |  
  | If you want to create a new branch to retain commits you create, you may
  | do so (now or later) by using -b with the checkout command again. Example:
  |  
  | git checkout -b <new-branch-name>
```

**Comment by brian-mann** [comment]
@pawelgalazka We setup buildkite on a project here, and the Dashboard captured the CI provider correctly. 

Our code had already taken into account Buildkite. Click on the env vars tab on one of your builds to see if Buildkite is exporting the env vars correctly.

As long as it exports BUILDKITE we will pick it up. Code for that is here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.coffee#L15

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).

**Comment by pawelgalazka** [comment]
Hmm... I'm using `1.0.3` and I still see missing branch info in dashboard.

**Comment by bahmutov** [comment]
Weird, we do have branch in our Buildkite test runs on production

![screen shot 2017-10-31 at 9 34 41 am](https://user-images.githubusercontent.com/2212006/32226352-ca16f37e-be1e-11e7-9959-f802b81eaa13.png)

Can you check yourself by printing environment variables starting with `BUILDKITE` using this module to confirm that branch is there? https://github.com/bahmutov/print-env

Otherwise I suggest debugging this yourself to find what is going wrong?

**Comment by ArieLevs** [comment]
Hi,

Was this issue resolved?
I'm using Jenkins and Github with Cypress version 3.0.1, and `Branch` is still blank

<img width="1005" alt="screen shot 2018-07-11 at 13 53 39" src="https://user-images.githubusercontent.com/34907201/42567582-d6a38d30-8512-11e8-9a9d-2e2e3c00fda4.png">

**Comment by jennifer-shehane** [comment]
@ArieLevs Could you open a new issue please? The issue with BuildKite's links were resolved. Each CI service unfortunately requires different code to get these variables working. ☺️

**Comment by grrowl** [comment]
In our case, we're running tests on all branches as buildkite is being fired via webhook on `pull_request` and on `push` events. We also run tests on `master`, which never has an associated PR, so the "Branch:" in cypress dashboard is blank in these cases. It would be great to use `BUILDKITE_BRANCH` or fall back to it when `_PULL_REQUEST_BRANCH` is empty. Our environment variables look like this:

In our case we 

```
BUILDKITE_BRANCH="feature/QUAL-165_Add_article_test"
BUILDKITE_PULL_REQUEST="false"
BUILDKITE_PULL_REQUEST_BASE_BRANCH=""
BUILDKITE_PULL_REQUEST_REPO=""
```

**Comment by benyamini** [comment]
We are exporting all variables but Cypress is failing to resolve the CI provider and branch name. Other variables appear (see screenshot) but not provider or branch :/

![screen shot 2019-01-09 at 5 53 20 pm](https://user-images.githubusercontent.com/22406673/50882190-12f0b600-1438-11e9-9605-1abceed7a136.png)

Our buildkite env looks something like this (n.b. not from same branch as above screenshot):

```
BUILDKITE="true"
BUILDKITE_AGENT_ID="a20ed7b0-b114-475a-9bab-70aed6dbba56"
BUILDKITE_AGENT_META_DATA_AWS_AMI_ID="ami-0r541d0604bff3890"
BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_ID="i-01493f25dfd354b95"
BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE="m4.2xlarge"
BUILDKITE_AGENT_META_DATA_BUILDKITE_AWS_STACK="v4.0.2"
BUILDKITE_AGENT_META_DATA_DOCKER="18.09.0"
BUILDKITE_AGENT_META_DATA_QUEUE="elastic"
BUILDKITE_AGENT_META_DATA_STACK="buildkite"
BUILDKITE_AGENT_NAME="buildkite-i-01493f25dfd354b95-1"
BUILDKITE_ARTIFACT_PATHS="cypress/videos/*;cypress/screenshots/*;cypress/videos/**/*;cypress/screenshots/**/*"
BUILDKITE_BRANCH="revert-2049"
BUILDKITE_BUILD_CREATOR="John Smith"
BUILDKITE_BUILD_CREATOR_EMAIL="john@good-emails.com.au"
BUILDKITE_BUILD_ID="191fe9b1-9a48-437f-a184-fe12023f2400"
BUILDKITE_BUILD_NUMBER="5162"
BUILDKITE_BUILD_URL="https://buildkite.com/company/company-cypress/builds/5162"
BUILDKITE_COMMAND="ops/run_cypress.sh"
BUILDKITE_COMMIT="33423047139422c078a34fbb74ced922f0033b88"
BUILDKITE_JOB_ID="9298a7ce-cd71-48c8-8bcf-92bbe6f5f13d"
BUILDKITE_LABEL=":chrome: Run Cypress Tests %n"
BUILDKITE_MESSAGE="Revert \"SK-3131""
BUILDKITE_ORGANIZATION_SLUG="company"
BUILDKITE_PARALLEL_JOB="0"
BUILDKITE_PARALLEL_JOB_COUNT="2"
BUILDKITE_PIPELINE_DEFAULT_BRANCH="master"
BUILDKITE_PIPELINE_PROVIDER="github"
BUILDKITE_PIPELINE_SLUG="company-cypress"
BUILDKITE_PULL_REQUEST="false"
BUILDKITE_PULL_REQUEST_BASE_BRANCH=""
BUILDKITE_PULL_REQUEST_REPO=""
BUILDKITE_REBUILT_FROM_BUILD_ID=""
BUILDKITE_REBUILT_FROM_BUILD_NUMBER=""
BUILDKITE_REPO="git@github.com:company/company.git"
BUILDKITE_REPO_SSH_HOST="github.com"
BUILDKITE_RETRY_COUNT="0"
BUILDKITE_SCRIPT_PATH="ops/run_cypress.sh"
BUILDKITE_SOURCE="trigger_job"
BUILDKITE_TAG=""
BUILDKITE_TIMEOUT="false"
BUILDKITE_TRIGGERED_FROM_BUILD_ID="c1fbed18-c175-457e-a429-12c738cba2b0"
BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER="12611"
BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG="company"
CI="true"
```

**Comment by bahmutov** [comment]
@benyamini Can I ask you to run on BuiltKite CI with environment variable `DEBUG=cypress:server,commit-info` please? This will print a lot more additional messages, and we will see what information we get from provider. These are strings like `git commit existing info`.

Note: before pasting the relevant part of the log here (we are only interested in the commit and provider information) make sure to remove all sensitive values, like record keys.

**Comment by bahmutov** [comment]
@benyamini I still do not see how this error could happen, the unit tests report correct info with these environment variables. For now I have added DEBUG printing of a few more variables in https://github.com/cypress-io/cypress/pull/3131 which will allow us to pinpoint the problem a little bit more in the future runs.

**Comment by benyamini** [comment]
@bahmutov same here... everything seems to be in the correct place. Thanks for your work on this one. Hopefully something pops out.

**Comment by tnrich** [comment]
I'm seeing a more extreme version of this when running our tests from within HerokuCI: 

![image](https://user-images.githubusercontent.com/2730609/55094947-90f64d80-5074-11e9-93b5-7585cc320e62.png)

Branch, Author, Commit, Message and CI are all blank. 


What's the recommended way of troubleshooting this? Thanks!

**Comment by flotwig** [comment]
@tnrich it doesn't look like we're set up to pull Heroku CI environment variables in: https://on.cypress.io/continuous-integration#Examples

I'm not sure why it's not automatically pulling them from the commit, maybe Heroku CI doesn't build with the `.git` directory available and so `commit-info` fails.

We could potentially add Heroku CI environment variables and support pulling the info in that way in [`ci_provider.js`](https://github.com/cypress-io/cypress/blob/e2e454262bf461f31e947da9f9fdc0a8fa23baf8/packages/server/lib/util/ci_provider.js), but I couldn't find much documentation about what environment variables Heroku makes available besides [this](https://devcenter.heroku.com/articles/heroku-ci#immutable-environment-variables).

**Comment by hvuong-sigma** [comment]
Bump - I have `BUILDKITE_BRANCH` set in the environment variables but it's still not properly being extracted and displayed in the Cypress dashboard.

Everything else besides `branch` and `ci` is filled in on the specs summary page.

**Comment by hvuong-sigma** [comment]
@benyamini Were you able to extract the info for `branch` and `ci`?

**Comment by LiuVII** [comment]
we running cypress `3.3.2`
from what we tested there are two necessary environment settings that should fill in `branch` and `ci` fields for the dashboard:
1. `BUILDKITE = true`
2. `BUILDKITE_BRANCH = your-branch-name-here`
both should be available/set in the same environment context where you do `cypress run ...` (like if you have Dockerfile that you're building inside your CI which you use to run cypress you should set these variables inside the image or container)

**Comment by bahmutov** [comment]
@tnrich Heroku CI does not seem to provide any commit information as environment variables, if you have that information you should set it yourself via `COMMIT_INOF_*` environment variables https://github.com/cypress-io/commit-info#fallback-environment-variables

For now, I am closing this issue, since BuiltKite env variables should be available I believe.
