### ISSUE TITLE
Issue after SSO Autentication - opens window with a '_/' at the end

### ISSUE THREAD

**Issue by rushipatel238** [cypress-io/cypress#7871]
I'm just starting to write a simple test case to visit an internal application. The URL redirects to SSO login properly. After entering the username and password, Cypress opens up a new blank window, with '_/' in the end after the URL.

I have set the "chromeWebSecurity": false in Cypress.json file. 

Since I cannot write down exact code due to security, below are the only steps written in the test case. (three lines of code)
1. cy.visit('http://myapp.mydomain.com') 
2. It gets redirected to SSO (https://smusath.net.mydomain.com/)
3. When entered, Cypress opens 'http://myapp.mydomain.com/__/' and is blank

Is this because of application being on 'http' and SSO is happening over 'https'? After SSO login, I see the next page for a split second before the blank page shows up.

Error I see in developer tool console is:
WebSocket connection to 'ws://myapp.mydomain.com/__socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
cypress_runner.js:187146

### Desired behavior:

Proceed after SSO properly authenticates  

I'm running Cypress 4.9.0. Any guidance is highly appreciated.

Thank You

**Comment by jennifer-shehane** [comment]
@rushipatel238 We have a potential fix available for this starting in [`4.6.0`](https://on.cypress.io/changelog#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by rushipatel238** [comment]
Thank you for a quick response, but unfortunately it still throws the same error even after adding **"experimentalSourceRewriting": true** to the cypress.json file. 

Error:
WebSocket connection to 'ws://myapp.mydomain.com/__socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

Would posting a direct request to SSO help? Or is there any other way?

Thank You
Rushi

**Comment by jennifer-shehane** [comment]
We believe a fix for this was released in [`7.3.0`](https://on.cypress.io/changelog#7-3-0) as part of https://github.com/cypress-io/cypress/pull/15995. Please upgrade to the new version.

If you're still experiencing an issue after upgrade, open a new issue with a fully reproducible example of the issue that we can run.
