### ISSUE TITLE
Cannot Type a single space using .type(" ")

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#807]
- Operating System: Windows 10
- Cypress Version: Beta Version 1.0.2
- Browser Version: Chrome 61

### Is this a Feature or Bug? 
Bug

### Current behavior:
`cy.get([some_object]).type(" ")`
results in the following in the console:
*CypressError: cy.type() cannot accept an empty String. You need to actually type something.*

### Desired behavior:
`cy.get([some_object]).type(" ")`
causes a single space to be typed in [some_object]

### How to reproduce:
`cy.get([some_object]).type(" ")`

#### Test code:

```
cy.get([some_object]).type(" ")
```

**Comment by jennifer-shehane** [comment]
The culprit line of code can be found here: https://github.com/metcorne/cypress/blob/issue-760/packages/driver/src/cy/commands/actions/type.coffee#L112-L113

**Comment by brian-mann** [comment]
Hah... good catch. Surprised it took 10MM tests before this one cropped up.

**Comment by calvinballing** [comment]
Someone mentioned this in the Gitter back in June this year, but I didn't see a corresponding issue created

**Comment by brian-mann** [comment]
Yah, if there wasn't an issue opened it will not ever get looked at. Thank you for opening this.

**Comment by brian-mann** [comment]
Fixed in [`1.0.3`](https://docs.cypress.io/guides/references/changelog.html#1-0-3).

**Comment by Joelasaur** [comment]
This is still broken with a null string (""). The fix only works if there is at least 1 character in the string, in the OP's example, a space " "). 

cy.get([some_object]).type(" ") works, but

cy.get([some_object]).type("") doesn't.

**Comment by jennifer-shehane** [comment]
Hey @Joelasaur, what behavior are you expecting within an input when passing an empty string into `cy.type()`? What behavior are you trying to test in the input with this? Wouldn't this essentially be Cypress typing nothing?

**Comment by Joelasaur** [comment]
Yes, the idea is to test submitting empty strings. Perhaps the user clicked on the box but entered nothing, not even a space, and then hit submit.

**Comment by bahmutov** [comment]
Would it be the same as using cy.focus().blur() and then submit?

**Comment by Joelasaur** [comment]
That probably would work. Just thought it was strange behavior to not allow empty strings.

**Comment by jennifer-shehane** [comment]
@RangerMauve Are you getting an error when running that test code? What is the error that is printed?

**Comment by RangerMauve** [comment]
@jennifer-shehane There's no error, it just doesn't type the empty space. I was in a bit of a rush so I put further investigation on hold. It might be a problem with the code we have around the input itself. I'll look into it more this week.

**Comment by Ravinderkaur04** [comment]
Hello, I have a similar issue with forward slashes and semi-colons. I'm trying to fill in date and time and my input looks like this for ex: 2019/4/18 10:11. Can someone look into this?
