### ISSUE TITLE
XHR server is unavailable or missing

### ISSUE THREAD

**Issue by Sameeksha-Sen** [cypress-io/cypress#8742]
### Current behavior
CypressError: The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message.

### Test code to reproduce

```js
beforeEach(function () {
        cy.login()
        cy.server();

      cy.route({
            method: "GET",
            url: baseUrl + "/gateway/directory/search?q=John&pageNumber=1",
            response: require("../../../fixtures/directorySearch.json")
        }).as("search");

        cy.visit(baseUrl + "/intranet/search?q=John&tab=directory&", {
            onBeforeLoad: win => {
                win.fetch = null;
            }
        });

        cy.wait("@search")
    });

    it('Directory Search result page should be visible', () => {
        cy.get('.search-result-count__total').should('be.visible')
        cy.get('.search-result-count__query').should('contain.text', 'John')
    });
```

### Versions

Cypress: 4.12(Chrome, headless)

**Comment by muzahir-12** [comment]
That should be fixed and ready to run

**Comment by Sameeksha-Sen** [comment]
I am still getting this error while running tests with cy.server() in beforeEach block.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Is the problem still happening with the latest Cypress?

**Comment by sainthkh** [comment]
Closing because of inactivity.
