### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute when testing Twilio Flex Plugin

### ISSUE THREAD

**Issue by robmosca-travelperk** [cypress-io/cypress#8941]
### Current behavior
We are testing a plugin for Twilio Flex (flex.twilio.com). We obtain programmatically a saml token for logging in to the plugin, using Okta's SSO, and then build the plugin's entrypoint URL including that token.
When we visit the entrypoint:

```typescript
cy.get('@twilioEntryPoint').then(entryPoint => {
    cy.visit(entryPoint)
  })
```

we get the following error message:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://assets.flex.twilio.com/releases/flex-ui/1.22.1/twilio-flex.unbundled-react.min.js' with computed SHA-256 integrity 'A7ZDPBZEwXEl6u6AkyuzoIuVADFjYD8KCA22FCuaIg8='. The resource has been blocked.
```

The response page contains the following signature:

```html
<script src="https://assets.flex.twilio.com/releases/flex-ui/1.22.1/twilio-flex.unbundled-react.min.js" crossorigin="anonymous" integrity="sha512-hKyJA/zBSBt+vSG+H6UNZ/JPHx+XE1ygX7GyQ/0sFE2+X31n4YntUC9gD7xTXwfQQreZBaH+KKUuqe/7uex0KQ=="></script>
```

if we add

```
"experimentalSourceRewriting": true,
```

to `cypress.json` the request times out.

### Desired behavior
The request succeeds without a SRI error.

### Test code to reproduce
Here the code we use to calculate the entrypoint:

```typescript
beforeEach(function () {
  // First we get an Okta session token
  const optionsSessionToken = {
    method: 'POST',
    url: 'https://${Cypress.env('OKTA_SUBDOMAIN')}.okta.com/api/v1/authn',
    body: {
      username: Cypress.env('TEST_ACCOUNT_USERNAME'),
      password: Cypress.env('TEST_ACCOUNT_PASSWORD'),
      options: {
        warnBeforePasswordExpired: 'true',
      },
    },
  }
  cy.request(optionsSessionToken).then(function (resp) {
    const sessionToken = resp.body.sessionToken
    // Then we hit Okta sessionCookieRedirect with the token to obtain the
    // SAML response
    const optionsSessionCookieRedirect = {
      method: 'GET',
      url: `https://${Cypress.env('OKTA_SUBDOMAIN')}.okta.com/login/sessionCookieRedirect?checkAccountSetupComplete=true&token=${sessionToken}&redirectUrl=${Cypress.env('OKTA_REDIRECT_URL')}`,
      form: true,
      followRedirect: true,
    }
    cy.request(optionsSessionCookieRedirect).then(function (resp) {
      const doc = new DOMParser().parseFromString(resp.body, 'text/html')
      const samlResp = doc
        .getElementsByName('SAMLResponse')[0]
        .getAttribute('value')
      const relayState = doc
        .getElementsByName('RelayState')[0]
        .getAttribute('value')
      const formData = new URLSearchParams()
      formData.append('SAMLResponse', samlResp || '')
      formData.append('RelayState', relayState || '')
      const samlRequestOptions = {
        method: 'POST',
        url: `https://iam.twilio.com/v1/Accounts/${Cypress.env(
          'TWILIO_ACCOUNT_SID'
        )}/saml2`,
        form: true,
        body: formData.toString(),
        followRedirect: false,
      }
      // Then we submit a request to Twilio's Saml2 endpoint with the SAML
      // response and we get the Twilio Flex entry point URL
      cy.request(samlRequestOptions)
        .its('body.redirect_to')
        .then(function (redirectUrl) {
          const entryPointParameters = redirectUrl.split('?')[1]
          const entryPoint = `/?path=%2F/agent-desktop%2F&${entryPointParameters}`
          cy.wrap(entryPoint).as('twilioEntryPoint')
        })
    })
  })
})
```

### Versions

Cypress 5.4.0

**Comment by robmosca-travelperk** [comment]
Hi, does anyone have any suggestion on how we could overcome this problem?

**Comment by HartiganHM** [comment]
@robmosca-travelperk  We were running into a similar issue on our end when attempting to login via Okta SSO and the error was identical. We were running Cypress version `5.5.0` and the issue seems to have resolved by upgrading to version `5.6.0`. Hope this helps!

**Comment by robmosca-travelperk** [comment]
Hi Hartigan,

thank you for your answer! We just tried with Cypress 5.6.0 but our issue is still there :( No matter what we get an SRI error and when we activate `experimentalSourceRewriting` the request just times out... 🤔 

I know we don't have too many details about the problem but... any suggestions? :)

**Comment by robmosca-travelperk** [comment]
I see there doesn't seem to be any insight on how to solve this. I will close this issue for the time being.
