### ISSUE TITLE
webpack-preprocessor cleanError throws TypeError

### ISSUE THREAD

**Issue by lenntt** [cypress-io/cypress#8948]
https://github.com/cypress-io/cypress/blob/5082238e42013c17a78396ab1abf9cf4ddc77708/npm/webpack-preprocessor/index.ts#L379

` TypeError: err.replace is not a function`
It seems `err` is an `Error` in my case, not a `string`.

I'm not familiar enough to make sure it would break anything else, but changing the js output locally to `err.message.replace`fixes things for me.

My real error was:
`"Module not found: Error: Can't resolve '../../src/Component' in '<mypath>/cypress/component'"`

**Comment by kwuite** [comment]
+1 I have the exact same issue. Copy pasted example code from npm, used any example I could find but to no avail. It all ends with the same error. 
![image](https://user-images.githubusercontent.com/6716689/97693022-d2e14400-1aa0-11eb-9c2e-44cbc9ad3bc6.png)

**Comment by kwuite** [comment]
New package was released today by version [5.4.9](https://www.npmjs.com/package/@cypress/webpack-preprocessor) and the dist folder is completely empty.

Starting version 4.1.1 I get the `err.replace is not a function`. 

This al feels very broken.

I need to fix webpack because currently even the most simplest of files are 6MB in size after compilation and it takes on average 4,5 second just to build it (not even importing it to the browser).

**Comment by epashkov** [comment]
I have the same issue.

**Comment by epashkov** [comment]
There is no problems with webpack@4.44.2

**Comment by mkalam-alami** [comment]
I got this by upgrading to Webpack 5, which I cancelled for the time being. Does this bug mean `@cypress/webpack-preprocessor` does not support Webpack 5 yet, or is it something new?

Not sure if related but the preprocessor files have received some fairly recent changes which may have broken something.

(To the maintainers: in passing I've just come across some merge markers left in webpack.js https://github.com/cypress-io/cypress/blob/master/npm/vue/src/preprocessor/webpack.js#L79)

**Comment by echenley** [comment]
The underlying problem here seems to be that the webpack instance started by cypress is using a flawed `require.resolve` algorithm. You can use `cypress-webpack-preprocessor-v5` to fix the `err.replace` error, but the underlying issue remains where the modules required by webpack dependencies are not using the normal node resolution algorithm.

In my case, babel-loader throws an error `validateOptions is not a function` because it is resolving the wrong version of `schema-utils`. I added some logs to the top of `node_modules/babel-loader/lib/index.js` to prove this:

```js
console.log(require.resolve.paths('schema-utils'));
// [
//   <rootDir>/node_modules/babel-loader/node_modules
//   <rootDir>/node_modules
//   etc.
// ]
// ^ schema-utils is installed in both places, meaning it should resolve to the
// version located at babel-loader/node_modules/schema-utils

console.log(require.resolve('schema-utils'));
// <rootDir>/node_modules/schema-utils/dist/index.js
// ^ instead, it resolves to the version in <rootDir>/node_modules/schema-utils
```

**Comment by har-preet** [comment]
+1 same issue.

**Comment by abeluck** [comment]
I landed here after getting the `TypeError: err.replace is not a function` error while trying to use cypress for the first time (not a great first impression). I followed the quick start, added the recomended tsconfig, then added a basic typescript test.

Is there a workaround?

**Comment by chrizzle** [comment]
+1 same issue

**Comment by or2008** [comment]
+1

**Comment by christopherread** [comment]
+1

**Comment by vranky** [comment]
+1

**Comment by mkalam-alami** [comment]
Please prefer thumbing up the issue over posting "+1" comments (each one of them sends unnecessary email notifications). Thanks

**Comment by sainthkh** [comment]
Can anyone provide a reproducible example? We cannot merge the code to the main branch without writing some test codes.

**Comment by jennifer-shehane** [comment]
Cypress webpack-preprocessor does not yet support Webpack 5 as explained in this issue: https://github.com/cypress-io/cypress/issues/8900

We released a temporary version of this package that supports webpack v5 – npmjs.com/package/cypress-webpack-preprocessor-v5

```
npm i cypress-webpack-preprocessor-v5
```

Is anyone getting this error outside of using Webpack 5? Because we will close this issue if not as it's a duplicate of https://github.com/cypress-io/cypress/issues/8900

**Comment by chris-hmmr** [comment]
> Cypress webpack-preprocessor does not yet support Webpack 5 as explained in this issue: #8900
> 
> We released a temporary version of this package that supports webpack v5 – npmjs.com/package/cypress-webpack-preprocessor-v5
> 
> ```
> npm i cypress-webpack-preprocessor-v5
> ```
> 
> Is anyone getting this error outside of using Webpack 5? Because we will close this issue if not as it's a duplicate of #8900

Hi, using the **cypress-webpack-preprocessor-v5** fixes the issue for me.

**Comment by ThaiChingChong** [comment]
Hi, 
   I am still facing the above issue after trying to install this package **cypress-webpack-preprocessor-v5** . I am still seeing the following errors when I tried to run my tests. 

```
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file 
TypeError: err.replace is not a function
```
My package.json dependancies

"devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@cypress/webpack-preprocessor": "^5.5.0",
    "@newsint/nu-sun-linting": "^1.3.1",
    "@types/amphtml-validator": "^1.0.1",
    "@types/cypress-image-snapshot": "^3.1.2",
    "amphtml-validator": "^1.0.29",
    "babel-loader": "^8.2.2",
    "cypress": "^6.1.0",
    "cypress-image-snapshot": "^3.1.1",
    "cypress-wait-until": "^1.6.1",
    "fs": "0.0.1-security",
    "lint-staged": "7.2.2",
    "path": "^0.12.7",
    "tsify": "^4.0.1",
    "typescript": "3.8.3",
    "webpack": "^5.11.0"
  },

Am I missing something here?

**Comment by jennifer-shehane** [comment]
@ThaiChingChong You need to install `cypress-webpack-preprocessor-v5`, this is not listed in your dev dependencies. Uninstall `@cypress/webpack-preprocessor` and install `cypress-webpack-preprocessor-v5`

```js
{
  "devDependencies": {
    "cypress": "6.1.0",
    "cypress-webpack-preprocessor-v5": "^5.0.0-alpha.1"
  }
}
```

**Comment by ThaiChingChong** [comment]
> @ThaiChingChong You need to install `cypress-webpack-preprocessor-v5`, this is not listed in your dev dependencies. Uninstall `@cypress/webpack-preprocessor` and install `cypress-webpack-preprocessor-v5`
> 
> ```js
> {
>   "devDependencies": {
>     "cypress": "6.1.0",
>     "cypress-webpack-preprocessor-v5": "^5.0.0-alpha.1"
>   }
> }
> ```

Thanks Jennifer. It's working fine now. I've uninstalled the original `@cypress/webpack-preprocessor` and reinstalled `cypress-webpack-preprocessor-v5` and now I'm getting a different error when trying to launch Cypress tests. At least its a different errors now.  :)

**Comment by Maleckidd** [comment]
> @ThaiChingChong You need to install `cypress-webpack-preprocessor-v5`, this is not listed in your dev dependencies. Uninstall `@cypress/webpack-preprocessor` and install `cypress-webpack-preprocessor-v5`
> 
> ```js
> {
>   "devDependencies": {
>     "cypress": "6.1.0",
>     "cypress-webpack-preprocessor-v5": "^5.0.0-alpha.1"
>   }
> }
> ```

Hi Jeniffer. Similar problem here. Its occurs randomly. I have tried this solution but it didn't help.
Error message: Uncaught TypeError: display.replaceAll is not a function

```
"cypress": "4.0.2",
"webpack": "4.44.1",
```

**Comment by Donaab** [comment]
I have the same issue. I have installed cypress globally and I have installed dependancies from the project 
`{
    "name": "cypress-tests",
    "version": "0.1.0",
    "dependencies": {
        "@bahmutov/cy-api": "^1.4.2",
        "cypress-commands": "^1.1.0",
        "cypress-file-upload": "^4.0.7",
        "is-my-json-valid": "^2.20.4",
        "ts-loader": "^8.0.1",
        "typescript": "^4.1.2",
        "@typescript-eslint/parser": "^4.9.0",
        "@testing-library/cypress": "^7.0.2"
    }
}`

I have tried with cypress 6.1.0 and 6.3.0. Also I have tried to install the mentioned cypress-webpack-preprocessor-v5 but I didn't use it before so I didn't add any other configuration for it like adding it to the plugins file etc.

**Comment by Donaab** [comment]
> The underlying problem here seems to be that the webpack instance started by cypress is using a flawed `require.resolve` algorithm. You can use `cypress-webpack-preprocessor-v5` to fix the `err.replace` error, but the underlying issue remains where the modules required by webpack dependencies are not using the normal node resolution algorithm.
> 
> In my case, babel-loader throws an error `validateOptions is not a function` because it is resolving the wrong version of `schema-utils`. I added some logs to the top of `node_modules/babel-loader/lib/index.js` to prove this:
> 
> ```js
> console.log(require.resolve.paths('schema-utils'));
> // [
> //   <rootDir>/node_modules/babel-loader/node_modules
> //   <rootDir>/node_modules
> //   etc.
> // ]
> // ^ schema-utils is installed in both places, meaning it should resolve to the
> // version located at babel-loader/node_modules/schema-utils
> 
> console.log(require.resolve('schema-utils'));
> // <rootDir>/node_modules/schema-utils/dist/index.js
> // ^ instead, it resolves to the version in <rootDir>/node_modules/schema-utils
> ```
> 
> I've also seen this same issue manifest with different versions of `enhanced-resolve` installed in `node_modules/webpack/node_modules/enhanced-resolve` and `node_modules/enhanced-resolve`. I would not be surprised if there are other variations of the same issue.

Yes got the same issue after the fixing `TypeError: err.replace is not a function`

**Comment by myyellowshoe** [comment]
For anyone looking for a workaround on this. You can downgrade to webpack 4 and that at least solves the issue in the near term. In my case I didn't have any packages that depended on webpack 5, so I was ok.

**Comment by Donaab** [comment]
> For anyone looking for a workaround on this. You can downgrade to webpack 4 and that at least solves the issue in the near term. In my case I didn't have any packages that depended on webpack 5, so I was ok.

@myyellowshoe How to downgrade webpack if I don't have it my project dependancies and cypress is installed globaly?

**Comment by myyellowshoe** [comment]
@Donaab maybe install webpack 4 globally? though can't say for sure if that's a good idea or not. But couldn't hurt to try as a band-aid

**Comment by JohnnyFun** [comment]
fwiw, to make `cypress-webpack-preprocessor-v5@5.0.0-alpha.1` work with my webpack@5.x configuration, I had to also tell webpack how to handle node.js's `path` since the preprocessor code requires it in. Webpack used to auto-fill node.js stuff, but doesn't anymore, so I needed this:

```
resolve: {
    ...
    fallback: {
      path: false,
    }
  },
```

`cypress-webpack-preprocessor-v5` could could probably fill in `fallback.path` if nothing's there, assuming what I'm doing here is necessary.

It seems to be super slow to start tests though...not sure what that's about. Will update if I figure something out.

**Comment by JohnnyFun** [comment]
Hmm, seems like `cypress-webpack-preprocessor-v5@5.0.0-alpha.1` may also need to set `publicPath: ''` or give option to override `webpackOptions.output.publicPath`. Otherwise, I get an error on some tests "".

I'll just fork the project for now, but just wanted to put a note about that here in case it helps someone.

**Comment by jryom** [comment]
> The underlying problem here seems to be that the webpack instance started by cypress is using a flawed `require.resolve` algorithm. You can use `cypress-webpack-preprocessor-v5` to fix the `err.replace` error, but the underlying issue remains where the modules required by webpack dependencies are not using the normal node resolution algorithm.
> 
> In my case, babel-loader throws an error `validateOptions is not a function` because it is resolving the wrong version of `schema-utils`. I added some logs to the top of `node_modules/babel-loader/lib/index.js` to prove this:
> 
> ```js
> console.log(require.resolve.paths('schema-utils'));
> // [
> //   <rootDir>/node_modules/babel-loader/node_modules
> //   <rootDir>/node_modules
> //   etc.
> // ]
> // ^ schema-utils is installed in both places, meaning it should resolve to the
> // version located at babel-loader/node_modules/schema-utils
> 
> console.log(require.resolve('schema-utils'));
> // <rootDir>/node_modules/schema-utils/dist/index.js
> // ^ instead, it resolves to the version in <rootDir>/node_modules/schema-utils
> ```
> 
> I've also seen this same issue manifest with different versions of `enhanced-resolve` installed in `node_modules/webpack/node_modules/enhanced-resolve` and `node_modules/enhanced-resolve`. I would not be surprised if there are other variations of the same issue.

I'm facing this exact problem too in a project. This is _not_ Webpack 5, but rather `4.46.0`. I'm seeing this error:

`TypeError: validateOptions is not a function
    at new SourceMapDevToolPlugin (~/code/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:107:3)`

Logging out `require.resolve` and `require.resolve.paths` for `schema-utils` in `SourceMapDevToolPlugin.js` gives this:

```js
console.log(require.resolve.paths('schema-utils'));
// [
//   '~/code/project/node_modules/webpack/lib/node_modules',
//   '~/code/project/node_modules/webpack/node_modules',
//   '~/code/project/node_modules',
//   '~/code/node_modules',
//   '~/node_modules',
//   '/Users/node_modules',
//   '/node_modules',
//   '~/.node_modules',
//   '~/.node_libraries',
//   '~/Library/Caches/Cypress/6.8.0/Cypress.app/Contents/Frameworks/Cypress Helper.app/Contents/lib/node'
// ]

console.log(require.resolve('schema-utils'));
// ~/code/project/node_modules/schema-utils/dist/index.js
```

Did you find a workaround, @echenley?

**Comment by xpostudio4** [comment]
@jryom did you found a solution to your problem?

**Comment by jryom** [comment]
> @jryom did you found a solution to your problem?

Unfortunately not. This issue seems to describe the cause quite well: https://github.com/cypress-io/cypress/issues/14646

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

I had this problem and found out the problem was my Cypress tests written in Typescript had type errors.

How I figured this out is by adding `console.log(err)` before the `err.replace` line, which output:
```js
{
  file: '/Users/bchinn/leapyear/leapyear-beta/auth/cypress/integration/saml.spec.ts',
  loc: '23:12-32',
  message: '\u001b[90m[tsl] \u001b[39m\u001b[1m\u001b[31mERROR\u001b[39m\u001b[22m\u001b[1m\u001b[31m in \u001b[39m\u001b[22m\u001b[1m\u001b[36m/Users/bchinn/leapyear/leapyear-beta/auth/cypress/integration/saml.spec.ts(23,13)\u001b[39m\u001b[22m\n' +
    '\u001b[1m\u001b[31m      TS2769: No overload matches this call.\u001b[39m\u001b[22m\n' +
    '\u001b[1m\u001b[31m  The last overload gave the following error.\u001b[39m\u001b[22m\n' +
    "\u001b[1m\u001b[31m    Argument of type '(res: Response) => void' is not assignable to parameter of type '(this: ObjectLike, currentSubject: Response) => void'.\u001b[39m\u001b[22m\n" +
    "\u001b[1m\u001b[31m      Types of parameters 'res' and 'currentSubject' are incompatible.\u001b[39m\u001b[22m\n" +
    "\u001b[1m\u001b[31m        Type 'Response' is missing the following properties from type 'Response': ok, redirected, trailer, type, and 8 more.\u001b[39m\u001b[22m",
  details: undefined,
  stack: undefined
}
```
This is rather annoying, and it'd be great to get this fixed. It seems like it's mostly a matter of changing
```js
return err.replace(...)
```
to
```js
const message = typeof err === 'string' ? err : err.message
return message.replace(...)
```

**Comment by inspiraller** [comment]
@brandon-leapyear 
Hi I'd like to try your solution. Can you elaborate on where you put this code? And where err.replace(..) exists?
regards

**Comment by inspiraller** [comment]
actually I realise now I've edited this file directly in my node_modules folder:

**node_modules/@cypress/webpack-preprocessor/diest.index.js**
Adding line - console.log('err = ', err); // add this line
```javascript
function cleanseError(err) {
    console.log('err = ', err); // add this line
    return err.replace(/\n\s*at.*/g, '').replace(/From previous event:\n?/g, '');
}
```

Now running cypress I can see the typescript errors I need to fix.
thankyou

**Comment by rkrisztian** [comment]
Opened https://github.com/nrwl/nx/issues/5906 for nrwl/nx users, as I couldn't find a way to replace `cypress-webpack-preprocessor` with `cypress-webpack-preprocessor-v5` there.

**Comment by msmith1114** [comment]
> > The underlying problem here seems to be that the webpack instance started by cypress is using a flawed `require.resolve` algorithm. You can use `cypress-webpack-preprocessor-v5` to fix the `err.replace` error, but the underlying issue remains where the modules required by webpack dependencies are not using the normal node resolution algorithm.
> > In my case, babel-loader throws an error `validateOptions is not a function` because it is resolving the wrong version of `schema-utils`. I added some logs to the top of `node_modules/babel-loader/lib/index.js` to prove this:
> > ```js
> > console.log(require.resolve.paths('schema-utils'));
> > // [
> > //   <rootDir>/node_modules/babel-loader/node_modules
> > //   <rootDir>/node_modules
> > //   etc.
> > // ]
> > // ^ schema-utils is installed in both places, meaning it should resolve to the
> > // version located at babel-loader/node_modules/schema-utils
> > 
> > console.log(require.resolve('schema-utils'));
> > // <rootDir>/node_modules/schema-utils/dist/index.js
> > // ^ instead, it resolves to the version in <rootDir>/node_modules/schema-utils
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've also seen this same issue manifest with different versions of `enhanced-resolve` installed in `node_modules/webpack/node_modules/enhanced-resolve` and `node_modules/enhanced-resolve`. I would not be surprised if there are other variations of the same issue.
> 
> I'm facing this exact problem too in a project. This is _not_ Webpack 5, but rather `4.46.0`. I'm seeing this error:
> 
> `TypeError: validateOptions is not a function at new SourceMapDevToolPlugin (~/code/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:107:3)`
> 
> Logging out `require.resolve` and `require.resolve.paths` for `schema-utils` in `SourceMapDevToolPlugin.js` gives this:
> 
> ```js
> console.log(require.resolve.paths('schema-utils'));
> // [
> //   '<rootDir>/node_modules/webpack/lib/node_modules',
> //   '<rootDir>/node_modules/webpack/node_modules',
> //   '<rootDir>/node_modules',
> // 	 ...
> // ]
> 
> console.log(require.resolve('schema-utils'));
> // <rootDir>/node_modules/schema-utils/dist/index.js
> ```
> 
> Did you find a workaround, @echenley?

@jryom I am seeing the exact same `validateOptions` error as well, with the same webpack. Did you ever find a resolution?

**Comment by jryom** [comment]
@msmith1114 for me the error went away after updating to Cypress 7.x 🤷

**Comment by krogfast** [comment]
@jryom as for me. 
Last week I use and was ok.
Today, this BS.
Any tips?

**Comment by inspiraller** [comment]
@krogfast 
Its worth noting that whenever you do an npm install, if you have any custom plugins in cypress plugins folder they get overwritten. Check that hasn't happened and restore it if you had it working previously.

**Comment by mhamri** [comment]
i'm facing the same issue, I put a `console.log()` to see what is the error and look like it's an object. calling `.replace` on error doesn't make sense 

here is my error 

```
{
  file: 'src/integration/00010-login/login.spec.ts:9:10',
  message: "\x1B[90mTS2339: \x1B[39mProperty 'waitForLoadingModalClose' does not exist on type 'cy & EventEmitter'.\r\n" +
    '  \x1B[0m \x1B[90m  7 |\x1B[39m     beforeEach(\x1B[36mfunction\x1B[39m () {\x1B[0m\r\n' +
    "  \x1B[0m \x1B[90m  8 |\x1B[39m       cy\x1B[33m.\x1B[39mvisit(\x1B[32m'auth/login'\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n" +
    '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m  9 |\x1B[39m       cy\x1B[33m.\x1B[39mwaitForLoadingModalClose()\x1B[33m;\x1B[39m\x1B[0m\r\n' +
    '  \x1B[0m \x1B[90m    |\x1B[39m          \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
    '  \x1B[0m \x1B[90m 10 |\x1B[39m       \x1B[90m// to solve some login page test failures due to incomplete page load\x1B[39m\x1B[0m\r\n' +
    `  \x1B[0m \x1B[90m 11 |\x1B[39m       cy\x1B[33m.\x1B[39m\x1B[36mget\x1B[39m(\x1B[32m'button span:contains("Login")'\x1B[39m\x1B[33m,\x1B[39m { timeout\x1B[33m:\x1B[39m \x1B[35m60000\x1B[39m })\x1B[33m.\x1B[39mshould(\x1B[32m'be.visible'\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n` +
    '  \x1B[0m \x1B[90m 12 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m',
  details: undefined,
  stack: "Error: \x1B[90mTS2339: \x1B[39mProperty 'waitForLoadingModalClose' does not exist on type 'cy & EventEmitter'.\r\n" +
    '  \x1B[0m \x1B[90m  7 |\x1B[39m     beforeEach(\x1B[36mfunction\x1B[39m () {\x1B[0m\r\n' +
    "  \x1B[0m \x1B[90m  8 |\x1B[39m       cy\x1B[33m.\x1B[39mvisit(\x1B[32m'auth/login'\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n" +
    '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m  9 |\x1B[39m       cy\x1B[33m.\x1B[39mwaitForLoadingModalClose()\x1B[33m;\x1B[39m\x1B[0m\r\n' +
    '  \x1B[0m \x1B[90m    |\x1B[39m          \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
    '  \x1B[0m \x1B[90m 10 |\x1B[39m       \x1B[90m// to solve some login page test failures due to incomplete page load\x1B[39m\x1B[0m\r\n' +
    `  \x1B[0m \x1B[90m 11 |\x1B[39m       cy\x1B[33m.\x1B[39m\x1B[36mget\x1B[39m(\x1B[32m'button span:contains("Login")'\x1B[39m\x1B[33m,\x1B[39m { timeout\x1B[33m:\x1B[39m \x1B[35m60000\x1B[39m })\x1B[33m.\x1B[39mshould(\x1B[32m'be.visible'\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\r\n` +
    '  \x1B[0m \x1B[90m 12 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '    at C:\\repo\\PPMS2\\frontend-temp\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tapAfterCompileToGetIssues.js:38:27\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Object.<anonymous> (C:\\repo\\PPMS2\\frontend-temp\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tapAfterCompileToGetIssues.js:37:16)\n' +       
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (C:\\repo\\PPMS2\\frontend-temp\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tapAfterCompileToGetIssues.js:5:58)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
```

it's a ts error as it can't find the definition for the `waitForLoadingModalClose`, a solution for that would be to add the definition into th support folder

**Comment by mhamri** [comment]
for god sake fix it, it's as easy as this, this error is there since version 4

```js
function cleanseError (err) {
  if (typeof err!=="string"){
    err= Object.values(err).join('\n\n');
  }

  return err.replace(/\n\s*at.*/g, '').replace(/From previous event:\n?/g, '');
}
```
and it will shows the error correctly 

![image](https://user-images.githubusercontent.com/8991783/132388935-81a29742-c72b-45e8-a837-467e066541e4.png)

**Comment by pavankjadda** [comment]
> Cypress webpack-preprocessor does not yet support Webpack 5 as explained in this issue: #8900
> 
> We released a temporary version of this package that supports webpack v5 – npmjs.com/package/cypress-webpack-preprocessor-v5
> 
> ```
> npm i cypress-webpack-preprocessor-v5
> ```
> 
> Is anyone getting this error outside of using Webpack 5? Because we will close this issue if not as it's a duplicate of #8900

This still does not fix the issue.

**Comment by rkrisztian** [comment]
While we're waiting for a fix, we can use [patch-package](https://github.com/ds300/patch-package) with @mhamri's [code line changes](https://github.com/cypress-io/cypress/issues/8948#issuecomment-914504685), to alleviate the problem a bit (just in case you didn't know).

**Comment by mhamri** [comment]
@rkrisztian my code is already part of the package, even the double `\n` 🤣

**Comment by amitasil** [comment]
Getting issue with Cypress 9.0 now, with a new installation

**Comment by stavares843** [comment]
same, any ETA?

**Comment by stavares843** [comment]
using `nvm install 16.13.0` fixed the issue

seems was an issue with using node 17

**Comment by andrei-dascalu** [comment]
I am also getting this with node 17

**Comment by JimLynchCodes** [comment]
Cypress seems to be still broken on node v17. None of the above solutions worked for me so I just downgraded npm... 🤷‍♂️

**Comment by emilyrohrbough** [comment]
@JimLynchCodes are you having this issue with cypress >= 7.7.0? Can you confrim you are using the latest version of @cypress/webpack-preprocessor version 5.11.0?
cypress/webpack-preprocessor  version 5.9.1+ should handle [the scenario when the error is not a string](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/index.ts#L406) and was pulled into Cypress 7.7.0.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
