### ISSUE TITLE
MacBook crashing when running cypress tests

### ISSUE THREAD

**Issue by vedsampang** [cypress-io/cypress#9195]
### Current behavior

I upgraded my MacBook to Big Sur and now my MacBook crashes each time I try to run my cypress tests. I tried both Chrome and Electron.

### Versions
macOS Big Sur
Version: 11.0.1 (20B29)
Cypress package version: 5.6.0
Cypress binary version: 5.6.0

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

Although I believe this is due to issue from Electron not running in Big Sur, which is what we run Cypress on under the hood. https://github.com/electron/electron/issues/24319

**Comment by vedsampang** [comment]
I ran cypress using:
DEBUG=cypress:* npx cypress open

My MacBook crashes when I run my test every time. Where can I get the log file?

**Comment by kvs713** [comment]
This also happens in Catalina (10.15.7). When I ran cypress open everything would start fine until about 10 seconds into a run and then my macbook would restart. This only happens with cypress open, not run. I'm also figuring out how to collect logs since my laptop crashes before I can save anything. 

macOS: Catalina 10.15.7
Cypress versions: 4.9.0 and 5.6.0

**Comment by vedsampang** [comment]
My MacBook crashes when I run my tests using "npx cypress run".

**Comment by kvs713** [comment]
I was able to resolve my issues by setting this in cypress.json
`"numTestsKeptInMemory": 1`

**Comment by kvs713** [comment]
Turns out my issue is only limited to running cypress open with Firefox selected as my browser. Chrome and Electron seem to work just fine.

**Comment by SanitarskiyDima** [comment]
I have the same issue. Every time I run cypress tests MacBook crashes.

**Comment by jennifer-shehane** [comment]
@kvs713 Your issues seems unrelated to Big Sure upgrade and is a performance issue with the runner in general. 

@vedsampang Can you provide an example of a test suite that fails in Big Sur? We've seen others be able to upgrade without any issues, so it'd be good to track down your exact issue so we know it's fixed with our fixes. Thanks!

**Comment by Onkar1992** [comment]
@jennifer-shehane 
Fail in: Big Sur 11.0.1

Please find the below log if it is helpful
GET /__/ 200 12.290 ms - -
GET /__cypress/runner/cypress_runner.css 200 6.138 ms - -
GET /__cypress/runner/cypress_runner.js 200 4.597 ms - -
GET /__cypress/static/favicon.ico 200 5.411 ms - -
GET /__cypress/iframes/integration/FirstTest.js 200 7.181 ms - 922
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 8.360 ms - 76120
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 2301.442 ms - -
GET /chrome-variations/seed?osname=mac&channel=stable&milestone=86 304 3549.825 ms - -
GET /v1/pages/Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRIqCcZMdmV0j2p6EgkNkWGVThIAGgASCQ0viD6CEgAaABIJDZFhlU4SABoA?alt=proto 200 1217.453 ms - -
HEAD / - - ms - -
HEAD / - - ms - -
HEAD / - - ms - -
GET /__cypress/tests?p=cypress/integration/FirstTest.js 200 3036.571 ms - -
GET /__cypress/tests?p=cypress/support/index.js 200 3047.996 ms - -
GET /__/ 200 2.713 ms - -
GET /__cypress/runner/cypress_runner.css 200 4.634 ms - -
GET /__cypress/runner/cypress_runner.js 200 3.323 ms - -
GET /__cypress/iframes/integration/FirstTest.js 200 1.931 ms - 928
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 22.330 ms - 76120
GET /__cypress/tests?p=cypress/support/index.js 200 5.724 ms - -
GET /__cypress/tests?p=cypress/integration/FirstTest.js 200 6.761 ms - -
GET /__cypress/runner/fonts/fa-regular-400.woff2 200 2.092 ms - 13600
GET /v1/pages/Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRIqCer-nGY98W2fEgkNkWGVThIAGgASCQ0viD6CEgAaABIJDZFhlU4SABoA?alt=proto 200 154.240 ms - -
GET / 200 36.124 ms - -
GET /bundles/qhd2yleepc_jlote-mu6hm0u5ov-hp2vfvfd-kzezis.min.css 200 117.999 ms - -
GET /images/thumbs/0000009_apparel_450.jpeg 200 113.879 ms - -
GET /images/thumbs/0000079_banner_1.jpg 200 305.444 ms - -
GET /images/thumbs/0000080_banner_2.jpg 200 291.534 ms - -
GET /Themes/DefaultClean/Content/images/logo.png 200 455.852 ms - -
GET /images/thumbs/0000005_electronics_450.jpeg 200 406.683 ms - -
GET /Themes/DefaultClean/Content/images/menu-icon.png 200 236.478 ms - -
GET /Themes/DefaultClean/Content/images/shopping-bag.png 200 117.797 ms - -
GET /Plugins/Widgets.NivoSlider/Content/nivoslider/themes/custom/loading.gif 200 103.646 ms - -
GET /bundles/kjzy1mfbtwtm9zgjw9hl6h1ultbl5nkaj7i9v-g5yaw.min.js 200 349.901 ms - -
GET /images/thumbs/0000013_digital-downloads_450.jpeg 200 118.883 ms - -
GET /images/thumbs/0000020_build-your-own-computer_415.jpeg 200 144.381 ms - -
GET /images/thumbs/0000041_htc-one-m8-android-l-50-lollipop_415.jpeg 200 138.865 ms - -
GET /images/thumbs/0000074_25-virtual-gift-card_415.jpeg 200 135.527 ms - -
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.addContext (_tls_wrap.js:1407:32)
    at /Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:222:23
    at tryCatcher (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:456:21)
 {
  library: 'PEM routines',
  function: 'OPENSSL_internal',
  reason: 'NO_START_LINE',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.addContext (_tls_wrap.js:1407:32)
    at /Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:222:23
    at tryCatcher (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/user1/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:456:21)

GET /Themes/DefaultClean/Content/images/rating1.png 200 203.649 ms - -
GET /Themes/DefaultClean/Content/images/rating2.png 200 179.263 ms - -
GET /Themes/DefaultClean/Content/images/wishlist-button.png 200 108.554 ms - -
GET /images/thumbs/0000024_apple-macbook-pro-13-inch_415.jpeg 200 270.616 ms - -

**Comment by bahmutov** [comment]
We have another issue with exact crash with reproducible example, I opened it a few days ago

**Comment by vedsampang** [comment]
The problem with my MacBook was that Norton was interfering and causing it to crash. Not sure why it was crashing only when I was running the cypress scripts. I removed Norton and my test are running fine now.

**Comment by jennifer-shehane** [comment]
@bahmutov Can you link to the issue? I couldn't find another issue with the same crash info.

**Comment by bahmutov** [comment]
It is https://github.com/cypress-io/cypress/issues/9220

```
GET /__cypress/tests?p=cypress/support/index.js 200 1268.985 ms - -
Error [ERR_TLS_REQUIRED_SERVER_NAME] [ERR_TLS_REQUIRED_SERVER_NAME]: "servername" is required parameter for Server.addContext
    at Server.addContext (_tls_wrap.js:1400:11)
    at /Users/gleb/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:222:23
    at tryCatcher (/Users/gleb/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gleb/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
```

**Comment by july-nym** [comment]
Hay guys, I found the same issue here with: 
Mac OS High Sierra version 10.13.6


<img width="1440" alt="Screen Shot 2020-12-07 at 09 55 24" src="https://user-images.githubusercontent.com/54060438/101301056-93adcc00-3872-11eb-94b3-6ce05100f257.png">

**Comment by rubyaryat** [comment]
I too just experienced my mac crashing when running some Cypress tests, which had previously worked.  

The cause turned out to be **Cisco AMP for endpoints**, or more specifically, the system extension: **com.cisco.endpoint.svc.networkextension**

After crashing I checked the OSX kernel panic logs via the console app (you find the panic logs in **Log Reports**, and are named with the convention: panic-full-_[datestamp]_.ips). These couple of lines in the panic log pointed me in direction of Cisco AMP:

"macOSPanicString" : "panic(cpu 10 caller 0xffffff800dec054f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: \/AppleInternal\/BuildRoot\/Library\/Caches\/com.apple.xbs\/Sources\/xnu\/xnu-6153.141.10\/bsd\/net\/content_filter.c, line: 1067\nBacktrace (CPU 10), Frame : Return Address\n0xffffffa3f2d63730 

and:

SD process name corresponding to current thread: com.cisco.endpoi\n

I recalled that yesterday I had approved the AMP Network Extension to load. After disabling this extension, the cypress tests run without crashing. You can see if you have com.cisco.endpoint.svc.networkextension loaded by:
% systemextensionsctl list

Instructions to deactivate or uninstall the extension are available here:
[https://www.cisco.com/c/en/us/support/docs/security/amp-endpoints/216232-manual-uninstall-procedure-for-amp-for-e.html#anc2](url)

The relevant part was:
10.
For macOS versions 10.15.5 and newer:
/Applications/Cisco\ AMP\ for\ Endpoints/AMP\ for\ Endpoints\ Service.app/Contents/MacOS/AMP\ for\ Endpoints\ Service deactivate content_filter
Enter password when prompted.

Cypress 6.1.0
OSX 10.15.7
AMP for Endpoints Mac Connector 1.14

Hope this solves someone else's crashing issues. 
Adam

**Comment by july-nym** [comment]
Hay @jennifer-shehane .
May I know the update on this issue? Because I cannot use the cypress until today.
Hope everything will good.
thank you,

**Comment by verheyenkoen** [comment]
I also had to switch to dockered solutions for running my tests locally which is far from ideal for debugging.

**Comment by akumarn74** [comment]
Any solution yet for crashing when running cypress tests.If any can someone let us know ?

**Comment by verheyenkoen** [comment]
@akumarn74 They already upgraded Electron in the previous release (6.2.0?) so the issue was already resolved back then I guess. Haven't tested todays' release (6.3.0) yet though but that also has an Electron upgrade.

**Comment by akumarn74** [comment]
Thanks @verheyenkoen. I have updated the latest released version works fine!

**Comment by akumarn74** [comment]
@verheyenkoen I have updated to cypress version 6.3.0 and Electron version 11.12.0 and the node version i am using 14.15.3,
still crashes MAC, when i run the tests.My MAC version 10.15.7 (Catalina).

**Comment by jennifer-shehane** [comment]
We did not determine why Cypress is cashing Mac in some cases. So there is no proposed solution for now. As mentioned above, you could run Cypress in docker to get around this crashing locally.

**Comment by StevenGBrown** [comment]
Or downgrade to Cypress 5.4.0. Works for me at least.

**Comment by verheyenkoen** [comment]
@akumarn74 I'm running Node v12.18.3. Maybe you can try that (or use [NVM](https://github.com/nvm-sh/nvm) to manage multiple versions on one machine)?

**Comment by verheyenkoen** [comment]
I just remembered I also had a Big Sur upgrade (11.1) a couple of weeks ago. Maybe that resolved the issue for me. Also tested in Cypress 6.3.0 on Node.js 14.15.4 now which also works (both in GUI and CLI). Can't really pin it down for me but my best guess would be the Big Sur upgrade fixed it for me.

**Comment by akumarn74** [comment]
@verheyenkoen  Thanks.I have tried MAC OS Mojave version and tests working fine.I guess the issue with Mac OS Catalina version.

**Comment by Aleh-root** [comment]
I got the same issue as @july-nym and @Onkar1992 after updating my MacOs to **10.15.7**

It is pretty common that the OPENSSL version is 'updated' at the same time as the os. Thus Homebrew will crash and most things that requires openssl will stop working. 

What need to be done is to checkout a previous version of Homebrew, and install a previous version of openssl:

- Go to Homebrew: `cd /usr/local/Homebrew/`
- Checkout a previous version: `git checkout 2.3.0` (this one worked for me)
- Install the previous version openssl: `brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb`
- Then checkout master again

_This should fix the cypress issue and openssl related issues. Dont update brew unless you absolutely need, no one can predict what will happen.._

**Comment by debasisj** [comment]
Hi Guys, 
Any update on this? 
This is what observed lately after upgrading to Big Sur and Cypress 8
1. On first test run on Cypress Test - It's takes time to load the test
2. On cmd - same issue 
3. However after fresh runs - it is quite ok 
4
However in my last instance - my macbook 15 (2020) GPU crashed  and i need to log back in  (kill Cypress Helper/renders)  !!:(

**Comment by HanyR** [comment]
This happens also in macOS Monterey 12.6.1

**Comment by nagash77** [comment]
@HanyR are you able to provide a a reproducible example using a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny)?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
