### ISSUE TITLE
cy.intercept causes problems when using delayMs

### ISSUE THREAD

**Issue by ray1618** [cypress-io/cypress#9436]
I migrated from Cypres 5.5 to 6.0.1 but my test will fail now sometimes. It seems like the delayMs is counted from the start of the test. Also the test below will fail when all other tests are active but it will success when it's the only one I run.

**My old test that will always succeed:**
```js
it.only('checks initial state and send the form with succes', () => {
      cy.server();
      cy.route({
      method: 'POST',
      url: '**/apiPath',
      response: '',
      delay: 1000,
      status: 200
       }).as('lasForm');

      cy.get('.clr-input-wrapper select').select('Test');

      cy.get('#clr-form-control-2')
        .should('not.have.text')
        .type('123abc-+')
        .should('have.value', '123abc-+');

      // send form
      cy.get('.btn-primary')
        .contains('Overschrijven')
        .click();

      cy.get('[data-cy="spinnerContainer"]').contains('Even geduld a.u.b.…');

      cy.wait('@lasForm');

      // form should have succes status
      cy.get('.btn-primary')
        .contains('LAS opgeslagen')
        .should('be.disabled');
      // success toaster alert should be visible
      cy.get('.alert.alert-success').should(
        'contain.text',
        'Opgeslagen.'
      );
    });
```

Below an example with intercept
It will throw: **Cannot read property 'tagName' of undefined**
on  .should('have.value', '123abc-+');

The test will success when I run the test with it.only
But I need to set the delayMs to 3000

**With intercept :**
```js
it.only('checks initial state and send the form with succes', () => {
      cy.intercept('POST', '**/o/beheer/las/SchoolCredentials', {
        statusCode: 200,
        body: '',
        delayMs: 1000
      }).as('lasForm');

      cy.get('.clr-input-wrapper select').select('Test');

      cy.get('#clr-form-control-2')
        .should('not.have.text')
        .type('123abc-+')
        .should('have.value', '123abc-+');

      // send form
      cy.get('.btn-primary')
        .contains('Overschrijven')
        .click();

      cy.get('[data-cy="spinnerContainer"]').contains('Even geduld a.u.b.…');

      cy.wait('@lasForm');

      // form should have succes status
      cy.get('.btn-primary')
        .contains('LAS opgeslagen')
        .should('be.disabled');
      // success toaster alert should be visible
      cy.get('.alert.alert-success').should(
        'contain.text',
        'Opgeslagen.'
      );
    });
```

**Comment by jennifer-shehane** [comment]
I'm not able to recreate the issues described around the `delayMs` value. The request below is delayed by 5 seconds. 

Can you provide a reproducible example that we can run? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

```js

it('test', () => {
  cy.wait(5000)
})

it('test 2', () => {
  cy.wait(5000)
})

it('test 3', () => {
  cy.wait(5000)
  cy.intercept('POST', 'url', {
    statusCode: 200,
    body: '',
    delayMs: 5000
  }).as('postUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/url')
    xhr.send()
  })
  cy.wait('@postUrl').then(({ request, response }) => {
  })
})
```

<img width="616" alt="Screen Shot 2020-12-04 at 11 18 53 AM" src="https://user-images.githubusercontent.com/1271364/101123229-bfd30e00-3622-11eb-889a-3fe98ea76ad4.png">

**Comment by ray1618** [comment]
The issues seems fixed with the new 6.1.0 update.
The only difference between the route and intercept function now is that delay: 1000  in route is enough. With intercept the loader seems to be done a bit to soon. Changing the delayMs to 1300 seems to do the trick.

**Comment by kimsy** [comment]
I can verify that this is still a problem in 6.3.0. The problem is not that delayMs is counted from the start of the test, but rather from when the intercept is defined (which is at the start of the test in the example by @ray1618 ). I would expect the delay to start counting when the request is initiated instead.

This can be reproduced with a small tweak to @jennifer-shehane's example, putting the 5000ms delay after the intercept:

`it.only('test 3', () => {
    cy.intercept('POST', 'url', {
      statusCode: 200,
      body: '',
      delayMs: 5000
    }).as('postUrl')
    cy.wait(5000)
    cy.visit('https://example.com')
    cy.window().then((win) => {
      const xhr = new win.XMLHttpRequest()
      xhr.open('POST', '/url')
      xhr.send()
    })
    cy.wait('@postUrl').then(({ request, response }) => {
    })
  });`

**Comment by gihan9a** [comment]
🔖  I landed here because of the same issue when trying to solve another https://github.com/cypress-io/cypress/discussions/14860

**Comment by jennifer-shehane** [comment]
@kimsy @gihan9a @ray1618 I think this may have been fixed in 6.4.0 as part of https://github.com/cypress-io/cypress/pull/14708 Can you update and see if this is resolved?

**Comment by gihan9a** [comment]
@jennifer-shehane Yes. I can confirm it has fixed in 6.4.0 👍 

The following screenshot is with different `delay|delayMs` configurations

![image](https://user-images.githubusercontent.com/787394/106567097-3d4dc880-6557-11eb-9972-092dfd4dffe1.png)

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by kimsy** [comment]
> @kimsy @gihan9a @ray1618 I think this may have been fixed in 6.4.0 as part of #14708 Can you update and see if this is resolved?

I also can confirm that this works now. Thanks for the help :)
